'use client';
import { supabase } from '@/lib/supabase';
import React, { useState, useEffect } from 'react';
import Link from 'next/link';

// Asegurate de que este fixture sea igual al de predicciones
const fixture = [
    { id: '1', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO A', local: 'MÉXICO', bandera_local: '🇲🇽', visitante: 'SUDÁFRICA', bandera_visitante: '🇿🇦', fecha: '11 de Junio', fecha_iso: '2026-06-11', hora: '16:00', jugadores: ['Raúl Rangel', 'Carlos Acevedo', 'Guillermo Ochoa', 'César Montes', 'Johan Vásquez', 'Mateo Chávez', 'Jesús Gallardo', 'Israel Reyes', 'Jorge Sánchez', 'Erik Lira', 'Luis Romo', 'Obed Vargas', 'Brian Gutiérrez', 'Oberlín Pineda', 'Edson Álvarez', 'Gilberto Mora', 'César Huerta', 'Álvaro Fidalgo', 'Luis Chávez', 'Roberto Alvarado', 'Alexis Vega', 'Julián Quiñones', 'Santiago Gimenez', 'Guillermo Martínez', 'Armando González', 'Raúl Jiménez',
         'Ronwen Williams', 'Ricardo Goss', 'Sipho Chaine', 'Khuliso Mudau', 'Olwethu Makhanya', 'Bradley Cross', 'Aubrey Modiba', 'Thabang Matuludi', 'Nkosinathi Sibisi', 'Ime Okon', 'Samukele Kabini', 'Mbekezeli Mbokazi', 'Kamolego Sebelebele', 'Khulumani Ndamane', 'Teboho Mokoena', 'Thalente Mbatha', 'Jayden Adams', 'Shephelo Sithole', 'Oswin Appollis', 'Tshepang Moremi', 'Evidence Makgopa', 'Lyle Foster', 'Ioraam Rayners', 'Relebohile Mofokeng', 'Themba Zawne', 'Thapelo Maseko'] },
    { id: '2', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO A', local: 'COREA DEL SUR', bandera_local: '🇰🇷', visitante: 'REP. CHECA', bandera_visitante: '🇨🇿', fecha: '11 de Junio', fecha_iso: '2026-06-11', hora: '23:00', jugadores: ['Son Heung-Min', 'Kim Min-jae', 'Cho Gue-sung', 'Hwang In-beom', 'Jo Hyeon-woo', 'Lee Jae-sung', 'Paik Seung-ho', 'Oh Hyeon-gyu', 'Seol Young-woo', 'Kim Seung-Gyu', 'Song Bum-keun', 'Kim Moon-hwan', 'Kim Tae-hyeon', 'Park Jin-seop', 'Jens Castrop', 'Lee Ki-hyuk', 'Lee Tae-seok', 'Lee Han-beom', 'Cho Yu-min', 'Kim Jin-gyu', 'Jun-Ho Bae', 'Yang Hyun-jun', 'Eom Ji-sung', 'Lee Kang-in', 'Lee Dong-gyeong', 'Hwang Hee-chan',
         'Jindřich Staněk', 'Matěj Kovář', 'Lukáš Horníček', 'Vladimír Coufal', 'Tomáš Holeš', 'David Jurásek', 'Jaroslav Zelený', 'Ladislav Krejčí', 'Štěpán Chaloupek', 'Robin Hranáč', 'David Douděra', 'David Zima', 'Tomáš Souček', 'Lukáš Provod', 'Michal Sadílek', 'Pavel Šulc', 'Vladimír Darida', 'Alexandr Sojka', 'Lukáš Červ', 'Tomáš Ladra', 'Hugo Sochurek', 'Pavel Bucha', 'Denis Višinský', 'Tomáš Chorý', 'Patrik Schick', 'Mojmír Chytil', 'Jan Kuchta', 'Christophe Kabongo', 'Adam Hložek'] },
    { id: '3', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO B', local: 'CANADÁ', bandera_local: '🇨🇦', visitante: 'BOSNIA Y HERZEGOVINA', bandera_visitante: '🇧🇦', fecha: '12 de Junio', fecha_iso: '2026-06-12', hora: '16:00', jugadores: ['Maxime Crépeau', 'Owen Goodman', 'Dayne St. Claire', 'Moïse Bombito', 'Derek Cornelius', 'Alphonso Davies', 'Luc de Fougerolles', 'Alistair Johnston', 'Alfie Jones', 'Richie Laryea', 'Niko Sigur', 'Joel Waterman', 'Ali Ahmed', 'Tajon Buchanan', 'Mathieu Choinière', 'Stephen Eustáquio', 'Marcelo Flores', 'Ismaël Koné', 'Liam Millar', 'Jonathan Osorio', 'Nathan Saliba', 'Jacob Shaffelburg', 'Jonathan David', 'Promise David', 'Cyle Larin', 'Tani Oluwaseyi',
         'Edin Džeko', 'Sead Kolašinac', 'Ermedin Demirovic', 'Amar Dedić', 'Benjamin Tahirović', 'Nikola Vasilj', 'Martin Zlomislić', 'Osman Hadžikić', 'Nihad Mujakić', 'Nikola Katić', 'Tarik Muharemović', 'Stjepan Radeljić', 'Dennis Hadžikadunić', 'Nidal Čelik', 'Amir Hadžiahmetović', 'Ivan Šunjić', 'Ivan Bašić', 'Dženis Burnić', 'Ermin Mahmić', 'Amar Memić', 'Armin Gigović', 'Kerim Alajbegović', 'Esmir Bajraktarević', 'Jovo Lukić', 'Samed Baždar', 'Haris Tabaković'] },
    { id: '4', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO D', local: 'ESTADOS UNIDOS', bandera_local: '🇺🇸', visitante: 'PARAGUAY', bandera_visitante: '🇵🇾', fecha: '12 de Junio', fecha_iso: '2026-06-12', hora: '22:00', jugadores: ['Matt Freese', 'Matt Turner', 'Chris Brady', 'Max Arfsten', 'Sergiño Dest', 'Alex Freeman', 'Mark McKenzie', 'Tim Ream', 'Chris Richards', 'Antonee Robinson', 'Miles Robinson', 'Joe Scally', 'Auston Trusty', 'Tyler Adams', 'Sebastian Berhalter', 'Weston McKennie', 'Cristian Roldán', 'Brenden Aaronson', 'Christian Pulisic', 'Gio Reyna', 'Malik Tillman', 'Tim Weah', 'Alejandro Zendejas', 'Folarin Balogun', 'Ricardo Pepi', 'Haji Wright',
      'Orlando Gill', 'Roberto Jr. Fernández', 'Gastón Olveira', 'Juan José Cáceres', 'José Canale', 'Fabián Balbuena', 'Omar Alderete', 'Gustavo Gómez', 'Alexandro Maidana', 'Junior Alonso', 'Gustavo Velázquez', 'Braian Ojeda', 'Damián Bobadilla', 'Andrés Cubas', 'Diego Gómez Gómez', 'Alejandro Romero Gamarra', 'Mauricio Prado', 'Matías Galarza', 'Ramón Sosa', 'Gustavo Caballero', 'Miguel Almirón', 'Gabriel Ávalos', 'Isidro Pitta', 'Álex Arce', 'Julio Enciso', 'Antonio Sanabria'] },
    { id: '5', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO B', local: 'CATAR', bandera_local: '🇶🇦', visitante: 'SUIZA', bandera_visitante: '🇨🇭', fecha: '13 de Junio', fecha_iso: '2026-06-13', hora: '16:00', jugadores: ['Akram Afif', 'Almoez Ali', 'Hassan Al-Haydos', 'Meshaal Barsham', 'Lucas Mendes', 'Mohammed Waad', 'Boualem Khoukhi', 'Abdulaziz Hatem', 'Jassim Gaber', 'Tarek Salman', 'Pedro Miguel', 'Homam Ahmed', 'Yusuf Abdurisag', 'Mohammed Muntari', 
         'Granit Xhaka', 'Manuel Akanji', 'Breel Embolo', 'Gregor Kobel', 'Remo Freuler', 'Ruben Vargas', 'Dan Ndoye', 'Zeki Amdouni', 'Michel Aebischer', 'Denis Zakaria', 'Silvan Widmer', 'Ricardo Rodríguez', 'Noah Okafor', 'Marvin Keller', 'Yvon Mvogo', 'Aurele Amenda', 'Eray Comert', 'Nico Elvedi', 'Luca Jaquez', 'Miro Muheim', 'Christian Fassnacht', 'Johan Manzambi', 'Djibril Sow', 'Cedric Itten', 'Fabian Rieder', 'Ardon Jashari'] },
    { id: '6', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO C', local: 'BRASIL', bandera_local: '🇧🇷', visitante: 'MARRUECOS', bandera_visitante: '🇲🇦', fecha: '13 de Junio', fecha_iso: '2026-06-13', hora: '19:00', jugadores: ['Vinícius Júnior', 'Endrick Felipe', 'Neymar Júnior', 'Raphinha Dias', 'Gabriel Martinelli', 'Lucas Paquetá', 'Bruno Guimarães', 'Marquinhos', 'Gabriel Magalhães', 'Danilo da Silva', 'Alisson Becker', 'Ederson Moraes', 'Weverton', 'Alex Sandro', 'Gleison Bremer', 'Douglas Santos', 'Roger Ibáñez da Silva', 'Léo Pereira', 'Wesley Ribeiro Silva', 'Casemiro', 'Danilo dos Santos', 'Fabinho Tavares', 'Igor Thiago', 'Luiz Henrique', 'Matheus Cunha', 'Rayan', 
         'Yassine Bounou', 'Munir Mohand Mohamedi', 'Ahmed Reda Tagnaouti', 'Achraf Hakimi', 'Noussair Mazraoui', 'Anass Salah-Eddine', 'Youssef Belammari', 'Issa Diop', 'Chadi Riad', 'Zakaria El Ouahdi', 'Redouane Halhal', 'Nayef Aguerd', 'Neil El Aynaoui', 'Bilal El Khannouss', 'Azzedine Ounahi', 'Ayyoub Bouaddi', 'Ismael Saibari', 'Sofyan Amrabat', 'Samir El Mourabet', 'Brahim Díaz', 'Abde Ezzalzouli', 'Ayoube Amaimouni', 'Soufiane Rahimi', 'Chemsdine Talbi', 'Gessime Yassine', 'Ayoub El Kaabi'] },
    { id: '7', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO C', local: 'HAITÍ', bandera_local: '🇭🇹', visitante: 'ESCOCIA', bandera_visitante: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', fecha: '13 de Junio', fecha_iso: '2026-06-13', hora: '22:00', jugadores: ['Duckens Nazon', 'Frantzdy Pierrot', 'Johny Placide', 'Carlens Arcus', 'Leverton Pierre', 'Ricardo Adé', 'Jean-Kévin Duverne', 'Alexandre Pierre', 'Josué Duverger', 'Wilguens Paugain', 'Duke Lacroix', 'Martin Experiénce', 'Hannes Delcroix', 'Keeto Thermoncy', 'Carl Sainté', 'Danley Jean Jacques', 'Jean-Ricner Bellegarde', 'Woodensky Pierre', 'Dominique Simon', 'Louicius Don Deedson', 'Ruben Providence', 'Josué Casimir', 'Derrick Etienne', 'Wilson Isidor', 'Yassin Fortune', 'Lenny Joseph',
         'Scott McTominay', 'John Mcginn', 'Billy Gilmour', 'Kieran Tierney', 'Angus Gunn', 'Jack Hendry', 'Che Adams', 'Ryan Christie', 'Lawrence Shankland', 'Lewis Ferguson', 'Craig Gordon', 'Liam Kelly', 'Grant Hanley', 'Aaron Hickey', 'Dominic Hyam', 'Scott McKenna', 'Nathan Patterson', 'Anthony Ralston', 'Andy Robertson', 'John Souttar', 'Findlay Curtis', 'Ben Gannon-Doak', 'Kenny McLean', 'Lyndon Dykes', 'George Hirst', 'Ross Stewart'] },
    { id: '8', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO D', local: 'AUSTRALIA', bandera_local: '🇦🇺', visitante: 'TURQUIA', bandera_visitante: '🇹🇷', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '1:00', jugadores: ['Patrick Beach', 'Paul Izzo', 'Aziz Behich', 'Jordan Bos', 'Cameron Burgess', 'Alessandro Circati', 'Milos Degenek', 'Jason Geria', 'Lucas Herrington', 'Jacob Italiano', 'Harry Souttar', 'Kai Trewin', 'Cameron Devlin', 'Ajdin Hrustić', 'Jackson Irvine', 'Connor Metcalfe', 'Paul Okon-Engstler', 'Aiden ONeill', 'Nestory Irankunda', 'Mathew Leckie', 'Awer Mabil', 'Mohamed Touré', 'Nishan Velupillay', 'Cristian Volpato', 'Tete Yengi',
    ] },
    { id: '9', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO E', local: 'ALEMANIA', bandera_local: '🇩🇪', visitante: 'CURAZAO', bandera_visitante: '🇨🇼', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '14:00', jugadores: ['Florian Wirtz', 'Jamal Musiala', 'Kai Havertz', 'Joshua Kimmich', 'Antonio Rüdiger', 'Leroy Sané', 'Jonathan Tah', 'Deniz Undav', 'Oliver Baumann', 'Manuel Neuer', 'Alexander Nübel', 'Waldemar Anton', 'Nathaniel Brown', 'David Raum', 'Nico Schlotterbeck', 'Malick Thiaw', 'Pascal Groß', 'Felix Nmecha', 'Aleksandar Pavlović', 'Angelo Stiller', 'Nadiem Amiri', 'Leon Goretzka', 'Maximilian Beier', 'Lennart Karl', 'Jamie Leweling', 'Nick Woltemade', 
         'Tahith Chong', 'Leandro Bacuna', 'Juninho Bacuna', 'Eloy Room', 'Armando Obispo', 'Riechedly Bazoer', 'Shurandy Sambo', 'Sherel Floranus', 'Juriën Gaari', 'Jürgen Locadia', 'Sontje Hansen', 'Livano Comenencia', 'Kenji Gorré', 'Tyrick Bodak', 'Trevor Doornbusch', 'Joshua Brenet', 'Roshon Van Eijma', 'Deveron Fonville', 'Kevin Felida', 'Arjany Martha', 'Tyrese Noslin', 'Godfried Roemeratoe', 'Jeremy Antonisse', 'Gervane Kastaneer', 'Brandley Kuwas', 'Jearl Margaritha'] },
    { id: '10', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO F', local: 'PAISES BAJOS', bandera_local: '🇳🇱', visitante: 'JAPÓN', bandera_visitante: '🇯🇵', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '17:00', jugadores: ['Mark Flekken', 'Robin Roefs', 'Bart Verbruggen', 'Nathan Aké', 'Virgil van Dijk', 'Denzel Dumfries', 'Jorrel Hato', 'Jan Paul van Hecke', 'Jurriën Timber', 'Micky van de Ven', 'Ryan Gravenberch', 'Frenkie de Jong', 'Justin Kluivert', 'Teun Koopmeiners', 'Marten de Roon', 'Guus Til', 'Quinten Timber', 'Mats Wieffer', 'Brian Brobbey', 'Memphis Depay', 'Cody Gakpo', 'Noa Lang', 'Donyell Malen', 'Tijjani Reijnders', 'Crysencio Summerville', 'Wout Weghorst',
         'Takefusa Kubo', 'Wataru Endō', 'Zion Suzuki', 'Ritsu Dōan', 'Ayase Ueda', 'Hiroki Itō', 'Daichi Kamada', 'Yukinari Sugawara', 'Ao Tanaka', 'Kō Itakura', 'Daizen Maeda', 'Tomoki Hayakawa', 'Keisuke Ōsako', 'Yūto Nagatomo', 'Shōgo Taniguchi', 'Tsuyoshi Watanabe', 'Takehiro Tomiyasu', 'Ayumu Seko', 'Junnosuke Suzuki', 'Junya Itō', 'Keito Nakamura', 'Kaishū Sano', 'Yuito Suzuki', 'Kento Shiogai', 'Kōki Ogawa', 'Keisuke Gotō'] },
    { id: '11', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO E', local: 'COSTA DE MARFIL', bandera_local: '🇨🇮', visitante: 'ECUADOR', bandera_visitante: '🇪🇨', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '20:00', jugadores: ['Hernán Galíndez', 'Gonzalo Valle', 'Moisés Ramírez', 'Ángelo Preciado', 'Félix Torres', 'Jackson Porozo', 'Joel Ordóñez', 'Willian Pacho', 'Piero Hincapié', 'Yaimar Medina', 'Pervis Estupiñán', 'Alan Franco', 'Denil Castillo', 'John Yeboah', 'Jordy Alcívar', 'Kendry Páez', 'Moisés Caicedo', 'Pedro Vite', 'Alan Minda', 'Anthony Valencia', 'Gonzalo Plata', 'Enner Valencia', 'Jordy Caicedo', 'Jeremy Arévalo', 'Nilson Angulo', 'Kevin Rodríguez',
         'Simon Adingra', 'Amad Diallo', 'Seko Fofana', 'Ibrahim Sangaré', 'Ousmane Diomandé', 'Evan N’Dicka', 'Elye Wahi', 'Yahia Fofana', 'Wilfried Singo', 'Nicolas Pépé', 'Evann Guessand', 'Mohamed Koné', 'Alban Lafont', 'Emmanuel Agbadou', 'Clément Akpa', 'Guéla Doué', 'Ghislain Konan', 'Odilon Kossounou', 'Parfait Guiagon', 'Christ Inao Oulai', 'Franck Kessié', 'Jean Michaël Seri', 'Ange-Yoan Bonny', 'Oumar Diakité', 'Yan Diomande', 'Bazoumana Touré'] },
    { id: '12', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO F', local: 'SUECIA', bandera_local: '🇸🇪', visitante: 'TÚNEZ', bandera_visitante: '🇹🇳', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '23:00', jugadores: ['Viktor Gyökeres', 'Alexander Isak', 'Lucas Bergvall', 'Victor Lindelöf', 'Isak Hien', 'Anthony Elanga', 'Yasin Ayari', 'Daniel Svensson', 'Viktor Johansson', 'Kristoffer Nordfeldt', 'Jacob Widell Zetterström', 'Gabriel Gudmundsson', 'Emil Holm', 'Gustaf Lagerbielke', 'Eric Smith', 'Carl Starfelt', 'Elliot Stroud', 'Jesper Karlström', 'Mattias Svanberg', 'Besfort Zeneli', 'Ken Sema', 'Taha Ali', 'Alexander Bernhardsson', 'Gustaf Nilsson', 'Benjamin Nygren',
         'Hannibal Mejbri', 'Ellyes Skhiri', 'Elias Achouri', 'Ismaël Gharbi', 'Montassar Talbi', 'Aymen Dahmen', 'Elias Saad', 'Ali Abdi', 'Yan Valery', 'Rani Khedira', 'Marouane Chamakh', 'Sabri Ben Hassen', 'Moutaz Neffati', 'Dylan Bronn', 'Omar Rekik', 'Adem Arous', 'Raed Chikhaoui', 'Amine Ben Hamida', 'Hadj Mahmoud', 'Anis Ben Slimane', 'Mortadha Ben Ouanes', 'Khalil Ayari', 'Firas Chaouat', 'Hazem Mastouri', 'Rayan Elloumi', 'Sebastian Tounekti'] },
    { id: '13', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO H', local: 'ESPAÑA', bandera_local: '🇪🇸', visitante: 'CABO VERDE', bandera_visitante: '🇨🇻', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '13:00', jugadores: ['Unai Simón', 'David Raya', 'Joan García', 'Pedro Porro', 'Marcos Llorente', 'Aymeric Laporte', 'Pau Cubarsi', 'Marc Pubill', 'Eric García', 'Marc Cucurella', 'Alejandro Grimaldo', 'Rodrigo Hernández', 'Martín Zubimendi', 'Pedri', 'Fabían Ruiz', 'Dani Olmo', 'Mikel Merino', 'Gavi', 'Alex Baena', 'Lamine Yamal', 'Yeremy Pino', 'Ferrán Torres', 'Mikel Oyarzabal', 'Borja Iglesias', 'Nico Williams', 'Víctor Muñoz', 
         'Ryan Mendes', 'Logan Costa', 'Josimar Dias (Vozinha)', 'Garry Rodrigues', 'Kevin Pina', 'Jovane Cabral', 'Roberto Lopes', 'Jamiro Monteiro', 'Steven Moreira', 'Deroy Duarte', 'Márcio Rosa', 'Carlos Santos', 'Wagner Pina', 'João Paulo Fernandes', 'Sidny Lopes Cabral', 'Kelvin Pires', 'Ianique Tavares (Stopíra)', 'Edilson Borges (Diney)', 'Telmo Arcanjo', 'Yannick Semedo', 'Laros Duarte', 'Willy Semedo', 'Nuno da Costa', 'Dailon Livramento', 'Gilson Tavares', 'Hélio Varela'] },
    { id: '14', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO G', local: 'BÉLGICA', bandera_local: '🇧🇪', visitante: 'EGIPTO', bandera_visitante: '🇪🇬', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '16:00', jugadores: ['Kevin De Bruyne', 'Jérémy Doku', 'Romelu Lukaku', 'Leandro Trossard', 'Youri Tielemans', 'Thibaut Courtois', 'Amadou Onana', 'Arthur Theate', 'Charles De Ketelaere', 'Timothy Castagne', 'Zeno Debast', 'Senne Lammens', 'Mike Penders', 'Maxim De Cuyper', 'Koni De Winter', 'Brandon Mechele', 'Thomas Meunier', 'Nathan Ngoy', 'Joaquin Seys', 'Nicolas Raskin', 'Hans Vanaken', 'Axel Witsel', 'Matías Fernández-Pardo', 'Dodi Lukébakio', 'Diego Moreira', 'Alexis Saelemaekers', 
         'Mohamed Salah', 'Omar Marmoush', 'Mahmoud Trézéguet', 'Mohamed Abdelmonem', 'Mohamed El Shenawy', 'Emam Ashour', 'Ahmed Sayed', 'Mohamed Hany', 'Ahmed Fatouh', 'Mostafa Shobeir', 'Al-Mahdy Soliman', 'Mohamed Alaa', 'Tarek Alaa', 'Hamdy Fathy', 'Ramy Rabia', 'Yasser Ibrahim', 'Hossam Abdelmaguid', 'Karim Hafez', 'Marwan Attia', 'Mohanad Lasheen', 'Nabil Emad', 'Mahmoud Saber', 'Mostafa Ziko', 'Ibrahim Adel', 'Haissem Hassan'] },
    { id: '15', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO H', local: 'ARABIA SAUDITA', bandera_local: '🇸🇦', visitante: 'URUGUAY', bandera_visitante: '🇺🇾', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '19:00', jugadores: ['Sergio Rochet', 'Fernando Muslera', 'Santiago Mele', 'Ronald Araujo', 'Guillermo Varela', 'Jose María Giménez', 'Santiago Bueno', 'Sebatían Cáceres', 'Mathías Olivera', 'Matías Viña', 'Joaquín Piquerez', 'Manuel Ugarte', 'Rodrigo Bentancur', 'Federico Valverde', 'Giorgian De Arrascaeta', 'Rodrigo Zalazar', 'Nicolás de la Cruz', 'Agustín Canobbio', 'Facundo Pellistri', 'Brian Rodríguez', 'Juan Manuel Sanabria', 'Maximiliano Araujo', 'Darwin Núñez', 'Rodrigo Aguirre', 'Federico Viñas',
         'Salem Al-Dawsari', 'Firas Al-Buraikan', 'Mohammed Al-Owais', 'Saud Abdulhamid', 'Mohamed Kanno', 'Ali Al-Bulayhi', 'Faisal Al-Ghamdi', 'Abdulelah Al-Malki', 'Hassan Tambakti', 'Nasser Al-Dawsari', 'Ali Lajami', 'Saleh Al-Shehri'] },
    { id: '16', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO G', local: 'IRÁN', bandera_local: '🇮🇷', visitante: 'NUEVA ZELANDA', bandera_visitante: '🇳🇿', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '22:00', jugadores: ['Chris Wood', 'Liberato Cacace', 'Joe Bell', 'Michael Boxall', 'Sarpreet Singh', 'Tyler Bindon', 'Ben Waine', 'Kosta Barbarouses', 'Max Crocombe', 'Alex Paulsen', 'Michael Woud', 'Callan Elliot', 'Tim Payne', 'Nando Pijnaker', 'Tommy Smith', 'Finn Surman', 'Francis de Vries', 'Lachlan Bayliss', 'Matthew Garbett', 'Elijah Just', 'Ben Old', 'Alex Rufer', 'Marko Stamenić', 'Ryan Thomas', 'Callum McCowatt', 'Jesse Randall',
         'Alireza Beiranvand', 'Seyed Hossein Hosseini', 'Payam Niazmand', 'Danial ⁠Eiri', 'Ehsan Hajsafi', 'Saleh Hardani', 'Hossein Kanaani', 'Shoja Khalilzadeh', 'Milad Mohammadi', 'Ali Nemati', 'Ramin Rezaeian', 'Rouzbeh Cheshmi', 'Saeid Ezatolahi', 'Mehdi Ghaedi', 'Saman Ghoddos', 'Mohammad Ghorbani', 'Alireza Jahanbakhsh', 'Mohammad Mohebi', 'Amir Mohammad Razzaghinia', 'Mehdi Torabi', 'Aria Yousefi', 'Ali Alipour', 'Dennis Dargahi', 'Amirhossein Hosseinzadeh', 'Mehdi Taremi', 'Shahriar Moghanlou'] },
    { id: '17', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO I', local: 'FRANCIA', bandera_local: '🇫🇷', visitante: 'SENEGAL', bandera_visitante: '🇸🇳', fecha: '16 de Junio', fecha_iso: '2026-06-16', hora: '16:00', jugadores: ['Kylian Mbappé', 'Michael Olise', 'Mike Maignan', 'William Saliba', 'Aurélien Tchouaméni', 'Ousmane Dembélé', 'Theo Hernández', 'Bradley Barcola', 'Warren Zaïre-Emery', 'Marcus Thuram', 'Robin Risser', 'Brice Samba', 'Lucas Digne', 'Malo Gusto', 'Lucas Hernandez', 'Ibrahima Konate', 'Jules Kounde', 'Maxence Lacroix', 'Dayot Upamecano', 'NGolo Kante', 'Manu Kone', 'Adrien Rabiot', 'Maghnes Akliouche', 'Rayan Cherki', 'Desire Doue', 'Jean-Philippe Mateta',
         'Édouard Mendy', 'Ismaïla Sarr', 'Pape Matar Sarr', 'Lamine Camara', 'Idrissa Gana Gueye', 'Iliman Ndiaye', 'Moussa Niakhaté', 'Mory Diaw', 'Yehvann Diouf', 'Krépin Diatta', 'Antoine Mendy', 'Kalidou Koulibaly', 'El Hadji Malick Diouf', 'Mamadou Sarr', 'Moustapha Mbow', 'Abdoulaye Seck', 'Ismail Jakobs', 'Ilay Camara', 'Pape Gueye', 'Habib Diarra', 'Pathé Ciss', 'Bara Sapoko Ndiaye', 'Sadio Mané', 'Assane Diao', 'Ibrahim Mbaye', 'Nicolas Jackson', 'Bamba Dieng', 'Cherif Ndiaye'] },
    { id: '18', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO I', local: 'IRAK', bandera_local: '🇮🇶', visitante: 'NORUEGA', bandera_visitante: '🇳🇴', fecha: '16 de Junio', fecha_iso: '2026-06-16', hora: '19:00', jugadores: ['Jalal Hassan', 'Ahmed Basil', 'Fahad Talib', 'Akam Hashen', 'Rebin Sulaka', 'Zaid Tahseem', 'Manaf Younis', 'Merchas Doski', 'Ahmed Yahya', 'Hussein Ali', 'Mustafa Saadoon', 'Frans Putros', 'Zaid Ismail', 'Zidane Iqbal', 'Aimar Sher', 'Amir Almmari', 'Kevin Yakob', 'Ibrahim Bayesh', 'Marko Farji', 'Youssef Amyn', 'Ahmed Qasim', 'Ali Jassim', 'Mohanad Ali', 'Aymen Hussein', 'Ali Al Hamadi', 'Ali Yousef',
         'Erling Haaland', 'Martin Ødegaard', 'Alexander Sørloth', 'Antonio Nusa', 'Julian Ryerson', 'Sander Berge', 'Oscar Bobb', 'Ørjan Nyland', 'Leo Østigård', 'David Møller Wolfe', 'Jørgen Strand Larsen', 'Egil Selvik', 'Sander Tangvik', 'Kristoffer Vassbakk Ajer', 'Fredrik Bjorkan', 'Henrik Falchener', 'Sondre Langas', 'Torbjorn Heggem', 'Marcus Holmgren Pedersen', 'Thelonious Aasgaard', 'Fredrik Aursnes', 'Patrick Berg', 'Jens Petter Hauge', 'Andreas Schjelderup', 'Morten Thorsby', 'Kristian Thorstvedt'] },
    { id: '19', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO J', local: 'ARGENTINA', bandera_local: '🇦🇷', visitante: 'ARGELIA', bandera_visitante: '🇩🇿', fecha: '16 de Junio', fecha_iso: '2026-06-16', hora: '22:00', jugadores: ['Emiliano Martínez', 'Gerónimo Rulli', 'Juan Musso', 'Leonardo Balerdi', 'Nicolás Tagliafico', 'Gonzalo Montiel', 'Lisandro Martínez', 'Cristian Romero', 'Nicolás Otamendi', 'Facundo Medina', 'Nahuel Molina', 'Leandro Paredes', 'Rodrigo De Paul', 'Valentín Barco', 'Giovani Lo Celso', 'Exequiel Palacios', 'Alexis Mac Allister', 'Enzo Fernández', 'Julián Álvarez', 'Lionel Messi', 'Nico González', 'Thiago Almada', 'Giuliano Simeone', 'Nico Paz', 'José Manuel López', 'Lautaro Martínez',
         'Luca Zidane', 'Oussama Benbot', 'Melvin Mastil', 'Abdelatif Ramdane', 'Rafik Belghali', 'Samir Chergui', 'Rayan Aït-Nouri', 'Jaouen Hadjam', 'Aïssa Mandi', 'Ramy Bensebaini', 'Zineddine Belaïd', 'Achref Abada', 'Mohamed Amine Tougai', 'Nabil Bentaleb', 'Hicham Boudaoui', 'Houssem Aouar', 'Farès Chaïbi', 'Ibrahim Maza', 'Yacine Titraoui', 'Ramiz Zerrouki', 'Mohamed Amoura', 'Nadhir Benbouali', 'Adil Boulbina', 'Farès Ghedjemis', 'Amine Gouiri', 'Anis Hadj Moussa', 'Riyad Mahrez'] },
    { id: '20', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO J', local: 'AUSTRIA', bandera_local: '🇦🇹', visitante: 'JORDANIA', bandera_visitante: '🇯🇴', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '1:00', jugadores: ['Marcel Sabitzer', 'Konrad Laimer', 'David Alaba', 'Christoph Baumgartner', 'Kevin Danso', 'Michael Gregoritsch', 'Stefan Posch', 'Patrick Pentz', 'Patrick Wimmer', 'Nicolas Seiwald', 'Romano Schmid', 'Philipp Lienhart', 'Alexander Schlager', 'Florian Wiegele', 'David Affengruber', 'Phillipp Mwene', 'Alexander Prass', 'Marco Friedl', 'Michael Svoboda', 'Xaver Schlager', 'Florian Grillitsch', 'Carney Chukwuemeka', 'Paul Wanner', 'Alessandro Schöpf', 'Marko Arnautovic', 'Sasa Kalajdzic',
         ] },
    { id: '21', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO K', local: 'PORTUGAL', bandera_local: '🇵🇹', visitante: 'RD CONGO', bandera_visitante: '🇨🇩', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '14:00', jugadores: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva', 'Rafael Leão', 'Rúben Dias', 'Diogo Costa', 'João Félix', 'Vitinha', 'Nuno Mendes', 'João Neves', 'Gonçalo Ramos', 'José Sá', 'Rui Silva', 'Ricardo Velho', 'Diogo Dalot', 'Matheus Nunes', 'Nélson Semedo', 'Joao Cancelo', 'Gonçalo Inácio', 'Renato Veiga', 'Tomás Araújo', 'Rúben Neves', 'Samú Costa', 'Francisco Trincao', 'Francisco Conceiçao', 'Pedro Neto', 'Gonçalo Guedes',
         'Yoane Wissa', 'Théo Bongonda', 'Chancel Mbemba', 'Samuel Moutoussamy', 'Simon Banza', 'Elia Meschack', 'Arthur Masuaku', 'Charles Pickel', 'Dylan Batubinsika', 'Gédéon Kalulu', 'Gaël Kakuta', 'Timothy Fayulu', 'Matthieu Epolo', 'Lionel Mpasi', 'Aaron Wan-Bissaka', 'Joris Kayembe', 'Steve Kapuadi', 'Rocky Bushiri', 'Axel Tuanzebe', 'Noah Sadiki', 'Edo Kayembe', 'Ngalayel Mukau', 'Nathanaël Mbuku', 'Brian Cipenga', 'Fiston Mayele', 'Cédric Bakambu'] },
    { id: '22', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO L', local: 'INGLATERRA', bandera_local: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', visitante: 'CROACIA', bandera_visitante: '🇭🇷', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '17:00', jugadores: ['Harry Kane', 'Jude Bellingham', 'Bukayo Saka', 'Declan Rice', 'Jordan Pickford', 'John Stones', 'Reece James', 'Marcus Rashford', 'Kobbie Mainoo', 'Marc Guéhi', 'Dean Henderson', 'James Trafford', 'Dan Burn', 'Ezri Konsa', 'Tino Livramento', 'Nico O Reilly', 'Jarell Quansah', 'Djed Spence', 'Elliot Anderson', 'Eberechi Eze', 'Jordan Henderson', 'Morgan Rogers', 'Anthony Gordon', 'Noni Madueke', 'Ivan Toney', 'Ollie Watkins',
         'Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić', 'Dominik Livaković', 'Martin Baturina', 'Andrej Kramarić', 'Josip Šutalo', 'Josip Stanišić', 'Mario Pašalić', 'Dominik Kotarski', 'Ivor Pandur', 'Duje Ćaleta-Car', 'Marin Pongračić', 'Martin Erlić', 'Luka Vušković', 'Nikola Vlašić', 'Luka Sučić', 'Kristijan Jakić', 'Petar Sučić', 'Nikola Moro', 'Toni Fruk', 'Ivan Perišić', 'Ante Budimir', 'Marco Pašalić', 'Petar Musa', 'Igor Matanović'] },
    { id: '23', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO L', local: 'GHANA', bandera_local: '🇬🇭', visitante: 'PANAMÁ', bandera_visitante: '🇵🇦', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '20:00', jugadores: ['Benjamín Asare', 'Lawrence Ati-Zigi', 'Joseph Anang', 'Salomon Agbasi', 'Paul Reverson', 'Baba Abdul Rahman', 'Gideon Mensah', 'Marvin Senaya', 'Alidu Seidu', 'Abdul Mumin', 'Jerome Opoku', 'Jonas Adjetey', 'Kojo Oppong Preprah', 'Alexander Djiku', 'Elisha Owusu', 'Thomas Partey', 'Kwasi Sibo', 'Augustine Boakye', 'Caleb Yirenkyi', 'Abdul Fatawu Issahaku', 'Kamal Deen Sulemana', 'Christopher Bonsu Baah', 'Ernest Nuamah', 'Antoine Semenyo', 'Brandon Thomas-Asante', 'Prince Kwabena Adu', 'Iñaki Williams', 'Jordan Ayew',
         'Orlando Mosquera', 'Luis Mejía', 'César Samudio', 'César Blackman', 'Jorge Gutiérrez', 'Amir Murillo', 'Fidel Escobar', 'Andrés Andrade', 'Edgardo Fariña', 'José Córdoba', 'Eric Davis', 'Jiovany Ramos', 'Roderick Miller', 'Aníbal Godoy', 'Adalberto Carrasquilla', 'Carlos Harvey', 'Cristian Martínez', 'José Luis Rodríguez', 'César Yanis', 'Yoel Bárcenas', 'Alberto Quintero', 'Azarías Londoño', 'Ismael Díaz', 'Cecilio Waterman', 'José Fajardo', 'Tomás Rodríguez'] },
    { id: '24', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO K', local: 'UZBEKISTÁN', bandera_local: '🇺🇿', visitante: 'COLOMBIA', bandera_visitante: '🇨🇴', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '23:00', jugadores: ['Camilo Vargas', 'David Ospina', 'Álvaro Montero', 'Daniel Muñoz', 'Santiago Arias', 'Yerry Mina', 'Davinson Sánchez', 'Jhon Lucumí', 'Willer Ditta', 'Yohan Mojica', 'Déiver Machado', 'Richard Ríos', 'Jefferson Lerma', 'Gustavo Puerta', 'Kevin Castaño', 'Jhon Arias', 'James Rodríguez', 'Juan Fernando Quintero', 'Jorge Carrascal', 'Juan Camilo Portilla', 'Luis Díaz', 'Luis Suárez', 'Carlos Gómez', 'Jaminton Campaz', 'Jhon Córdoba', 'Juan Camilo Hernández',
         'Utkir Yusupov', 'Botirali Ergashev', 'Abdovkih Nematov', 'Rustamjon Ashurmatov', 'Umarbek Eshmurodov', 'Avazbek Ylmasaliev', 'Abduqodir Khusanov', 'Abdulla Abdulaev', 'Jakhongir Urozov', 'Khojiakbar Alijonov', 'Berhuz Karimov', 'Ruslanbek Jiyanov', 'Farrukh Sayfiev', 'Sherzos Nasrrulaev', 'Umarali Rakmonaliev', 'Azizjon Ganiev', 'Akmal Mozgovoy', 'Sherzod Ezanov', 'Otakeb Shukubov', 'Odiljon Khamrobekov', 'Dostonbek Khamdamov', 'Jamshid Iskanderov', 'Jasur Jaloliddinov', 'Abbosek Fayzullaev', 'Oston Urunov', 'Jaloliddin Masharipov', 'Azizbek Amonov', 'Eldor Shomurodov', 'Igor Sergeev', 'Sherdoz Temirov'] },
    

    { id: '25', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO A', local: 'REP CHECA', bandera_local: '🇨🇿', visitante: 'SUDÁFRICA', bandera_visitante: '🇿🇦', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '13:00', jugadores: ['Ronwen Williams', 'Ricardo Goss', 'Sipho Chaine', 'Khuliso Mudau', 'Olwethu Makhanya', 'Bradley Cross', 'Aubrey Modiba', 'Thabang Matuludi', 'Nkosinathi Sibisi', 'Ime Okon', 'Samukele Kabini', 'Mbekezeli Mbokazi', 'Kamolego Sebelebele', 'Khulumani Ndamane', 'Teboho Mokoena', 'Thalente Mbatha', 'Jayden Adams', 'Shephelo Sithole', 'Oswin Appollis', 'Tshepang Moremi', 'Evidence Makgopa', 'Lyle Foster', 'Ioraam Rayners', 'Relebohile Mofokeng', 'Themba Zawne', 'Thapelo Maseko',
         'Jindřich Staněk', 'Matěj Kovář', 'Lukáš Horníček', 'Vladimír Coufal', 'Tomáš Holeš', 'David Jurásek', 'Jaroslav Zelený', 'Ladislav Krejčí', 'Štěpán Chaloupek', 'Robin Hranáč', 'David Douděra', 'David Zima', 'Tomáš Souček', 'Lukáš Provod', 'Michal Sadílek', 'Pavel Šulc', 'Vladimír Darida', 'Alexandr Sojka', 'Lukáš Červ', 'Tomáš Ladra', 'Hugo Sochurek', 'Pavel Bucha', 'Denis Višinský', 'Tomáš Chorý', 'Patrik Schick', 'Mojmír Chytil', 'Jan Kuchta', 'Christophe Kabongo', 'Adam Hložek'] },
    { id: '26', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO B', local: 'SUIZA', bandera_local: '🇨🇭', visitante: 'BOSNIA Y HERZEGOVINA', bandera_visitante: '🇧🇦', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '16:00', jugadores: ['Edin Džeko', 'Sead Kolašinac', 'Ermedin Demirovic', 'Amar Dedić', 'Benjamin Tahirović', 'Nikola Vasilj', 'Martin Zlomislić', 'Osman Hadžikić', 'Nihad Mujakić', 'Nikola Katić', 'Tarik Muharemović', 'Stjepan Radeljić', 'Dennis Hadžikadunić', 'Nidal Čelik', 'Amir Hadžiahmetović', 'Ivan Šunjić', 'Ivan Bašić', 'Dženis Burnić', 'Ermin Mahmić', 'Amar Memić', 'Armin Gigović', 'Kerim Alajbegović', 'Esmir Bajraktarević', 'Jovo Lukić', 'Samed Baždar', 'Haris Tabaković',
         'Granit Xhaka', 'Manuel Akanji', 'Breel Embolo', 'Gregor Kobel', 'Remo Freuler', 'Ruben Vargas', 'Dan Ndoye', 'Zeki Amdouni', 'Michel Aebischer', 'Denis Zakaria', 'Silvan Widmer', 'Ricardo Rodríguez', 'Noah Okafor', 'Marvin Keller', 'Yvon Mvogo', 'Aurele Amenda', 'Eray Comert', 'Nico Elvedi', 'Luca Jaquez', 'Miro Muheim', 'Christian Fassnacht', 'Johan Manzambi', 'Djibril Sow', 'Cedric Itten', 'Fabian Rieder', 'Ardon Jashari'] },
    { id: '27', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO B', local: 'CANADÁ', bandera_local: '🇨🇦', visitante: 'CATAR', bandera_visitante: '🇶🇦', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '19:00', jugadores: ['Maxime Crépeau', 'Owen Goodman', 'Dayne St. Claire', 'Moïse Bombito', 'Derek Cornelius', 'Alphonso Davies', 'Luc de Fougerolles', 'Alistair Johnston', 'Alfie Jones', 'Richie Laryea', 'Niko Sigur', 'Joel Waterman', 'Ali Ahmed', 'Tajon Buchanan', 'Mathieu Choinière', 'Stephen Eustáquio', 'Marcelo Flores', 'Ismaël Koné', 'Liam Millar', 'Jonathan Osorio', 'Nathan Saliba', 'Jacob Shaffelburg', 'Jonathan David', 'Promise David', 'Cyle Larin', 'Tani Oluwaseyi',
    ] },
    { id: '28', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO A', local: 'COREA DEL SUR', bandera_local: '🇰🇷', visitante: 'MÉXICO', bandera_visitante: '🇲🇽', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '22:00', jugadores: ['Raúl Rangel', 'Carlos Acevedo', 'Guillermo Ochoa', 'César Montes', 'Johan Vásquez', 'Mateo Chávez', 'Jesús Gallardo', 'Israel Reyes', 'Jorge Sánchez', 'Erik Lira', 'Luis Romo', 'Obed Vargas', 'Brian Gutiérrez', 'Oberlín Pineda', 'Edson Álvarez', 'Gilberto Mora', 'César Huerta', 'Álvaro Fidalgo', 'Luis Chávez', 'Roberto Alvarado', 'Alexis Vega', 'Julián Quiñones', 'Santiago Gimenez', 'Guillermo Martínez', 'Armando González', 'Raúl Jiménez',
         'Son Heung-Min', 'Kim Min-jae', 'Cho Gue-sung', 'Hwang In-beom', 'Jo Hyeon-woo', 'Lee Jae-sung', 'Paik Seung-ho', 'Oh Hyeon-gyu', 'Seol Young-woo', 'Kim Seung-Gyu', 'Song Bum-keun', 'Kim Moon-hwan', 'Kim Tae-hyeon', 'Park Jin-seop', 'Jens Castrop', 'Lee Ki-hyuk', 'Lee Tae-seok', 'Lee Han-beom', 'Cho Yu-min', 'Kim Jin-gyu', 'Jun-Ho Bae', 'Yang Hyun-jun', 'Eom Ji-sung', 'Lee Kang-in', 'Lee Dong-gyeong', 'Hwang Hee-chan'] },
    { id: '29', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO D', local: 'ESTADOS UNIDOS', bandera_local: '🇺🇸', visitante: 'AUSTRALIA', bandera_visitante: '🇦🇺', fecha: '19 de Junio', fecha_iso: '2026-06-19', hora: '16:00', jugadores: ['Matt Freese', 'Matt Turner', 'Chris Brady', 'Max Arfsten', 'Sergiño Dest', 'Alex Freeman', 'Mark McKenzie', 'Tim Ream', 'Chris Richards', 'Antonee Robinson', 'Miles Robinson', 'Joe Scally', 'Auston Trusty', 'Tyler Adams', 'Sebastian Berhalter', 'Weston McKennie', 'Cristian Roldán', 'Brenden Aaronson', 'Christian Pulisic', 'Gio Reyna', 'Malik Tillman', 'Tim Weah', 'Alejandro Zendejas', 'Folarin Balogun', 'Ricardo Pepi', 'Haji Wright',
         'Patrick Beach', 'Paul Izzo', 'Aziz Behich', 'Jordan Bos', 'Cameron Burgess', 'Alessandro Circati', 'Milos Degenek', 'Jason Geria', 'Lucas Herrington', 'Jacob Italiano', 'Harry Souttar', 'Kai Trewin', 'Cameron Devlin', 'Ajdin Hrustić', 'Jackson Irvine', 'Connor Metcalfe', 'Paul Okon-Engstler', 'Aiden ONeill', 'Nestory Irankunda', 'Mathew Leckie', 'Awer Mabil', 'Mohamed Touré', 'Nishan Velupillay', 'Cristian Volpato', 'Tete Yengi'] },
    { id: '30', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO C', local: 'ESCOCIA', bandera_local: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', visitante: 'MARRUECOS', bandera_visitante: '🇲🇦', fecha: '19 de Junio', fecha_iso: '2026-06-19', hora: '19:00', jugadores: ['Yassine Bounou', 'Munir Mohand Mohamedi', 'Ahmed Reda Tagnaouti', 'Achraf Hakimi', 'Noussair Mazraoui', 'Anass Salah-Eddine', 'Youssef Belammari', 'Issa Diop', 'Chadi Riad', 'Zakaria El Ouahdi', 'Redouane Halhal', 'Nayef Aguerd', 'Neil El Aynaoui', 'Bilal El Khannouss', 'Azzedine Ounahi', 'Ayyoub Bouaddi', 'Ismael Saibari', 'Sofyan Amrabat', 'Samir El Mourabet', 'Brahim Díaz', 'Abde Ezzalzouli', 'Ayoube Amaimouni', 'Soufiane Rahimi', 'Chemsdine Talbi', 'Gessime Yassine', 'Ayoub El Kaabi',
         'Scott McTominay', 'John Mcginn', 'Billy Gilmour', 'Kieran Tierney', 'Angus Gunn', 'Jack Hendry', 'Che Adams', 'Ryan Christie', 'Lawrence Shankland', 'Lewis Ferguson', 'Craig Gordon', 'Liam Kelly', 'Grant Hanley', 'Aaron Hickey', 'Dominic Hyam', 'Scott McKenna', 'Nathan Patterson', 'Anthony Ralston', 'Andrew Robertson', 'John Souttar', 'Findlay Curtis', 'Ben Gannon-Doak', 'Kenny McLean', 'Lyndon Dykes', 'George Hirst', 'Ross Stewart'] },
    { id: '31', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO C', local: 'BRASIL', bandera_local: '🇧🇷', visitante: 'HAITÍ', bandera_visitante: '🇭🇹', fecha: '19 de Junio', fecha_iso: '2026-06-19', hora: '21:30', jugadores: ['Vinícius Júnior', 'Endrick Felipe', 'Neymar Júnior', 'Raphinha Dias', 'Gabriel Martinelli', 'Lucas Paquetá', 'Bruno Guimarães', 'Marquinhos', 'Gabriel Magalhães', 'Danilo da Silva', 'Alisson Becker', 'Ederson Moraes', 'Weverton', 'Alex Sandro', 'Gleison Bremer', 'Douglas Santos', 'Roger Ibáñez da Silva', 'Léo Pereira', 'Wesley Ribeiro Silva', 'Casemiro', 'Danilo dos Santos', 'Fabinho Tavares', 'Igor Thiago', 'Luiz Henrique', 'Matheus Cunha', 'Rayan', 
         'Duckens Nazon', 'Frantzdy Pierrot', 'Johny Placide', 'Carlens Arcus', 'Leverton Pierre', 'Ricardo Adé', 'Jean-Kévin Duverne', 'Alexandre Pierre', 'Josué Duverger', 'Wilguens Paugain', 'Duke Lacroix', 'Martin Experiénce', 'Hannes Delcroix', 'Keeto Thermoncy', 'Carl Sainté', 'Danley Jean Jacques', 'Jean-Ricner Bellegarde', 'Woodensky Pierre', 'Dominique Simon', 'Louicius Don Deedson', 'Ruben Providence', 'Josué Casimir', 'Derrick Etienne', 'Wilson Isidor', 'Yassin Fortune', 'Lenny Joseph'] },
    { id: '32', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO D', local: 'TURQUÍA', bandera_local: '🇹🇷', visitante: 'PARAGUAY', bandera_visitante: '🇵🇾', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '0:00', jugadores: [
         'Orlando Gill', 'Roberto Jr. Fernández', 'Gastón Olveira', 'Juan José Cáceres', 'José Canale', 'Fabián Balbuena', 'Omar Alderete', 'Gustavo Gómez', 'Alexandro Maidana', 'Junior Alonso', 'Gustavo Velázquez', 'Braian Ojeda', 'Damián Bobadilla', 'Andrés Cubas', 'Diego Gómez Gómez', 'Alejandro Romero Gamarra', 'Mauricio Prado', 'Matías Galarza', 'Ramón Sosa', 'Gustavo Caballero', 'Miguel Almirón', 'Gabriel Ávalos', 'Isidro Pitta', 'Álex Arce', 'Julio Enciso', 'Antonio Sanabria'] },
    { id: '33', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO F', local: 'PAISES BAJOS', bandera_local: '🇳🇱', visitante: 'SUECIA', bandera_visitante: '🇸🇪', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '14:00', jugadores: ['Mark Flekken', 'Robin Roefs', 'Bart Verbruggen', 'Nathan Aké', 'Virgil van Dijk', 'Denzel Dumfries', 'Jorrel Hato', 'Jan Paul van Hecke', 'Jurriën Timber', 'Micky van de Ven', 'Ryan Gravenberch', 'Frenkie de Jong', 'Justin Kluivert', 'Teun Koopmeiners', 'Marten de Roon', 'Guus Til', 'Quinten Timber', 'Mats Wieffer', 'Brian Brobbey', 'Memphis Depay', 'Cody Gakpo', 'Noa Lang', 'Donyell Malen', 'Tijjani Reijnders', 'Crysencio Summerville', 'Wout Weghorst',
         'Viktor Gyökeres', 'Alexander Isak', 'Lucas Bergvall', 'Victor Lindelöf', 'Isak Hien', 'Anthony Elanga', 'Yasin Ayari', 'Daniel Svensson', 'Viktor Johansson', 'Kristoffer Nordfeldt', 'Jacob Widell Zetterström', 'Gabriel Gudmundsson', 'Emil Holm', 'Gustaf Lagerbielke', 'Eric Smith', 'Carl Starfelt', 'Elliot Stroud', 'Jesper Karlström', 'Mattias Svanberg', 'Besfort Zeneli', 'Ken Sema', 'Taha Ali', 'Alexander Bernhardsson', 'Gustaf Nilsson', 'Benjamin Nygren'] },
    { id: '34', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO E', local: 'ALEMANIA', bandera_local: '🇩🇪', visitante: 'COSTA DE MARFIL', bandera_visitante: '🇨🇮', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '17:00', jugadores: ['Florian Wirtz', 'Jamal Musiala', 'Kai Havertz', 'Joshua Kimmich', 'Antonio Rüdiger', 'Leroy Sané', 'Jonathan Tah', 'Deniz Undav', 'Oliver Baumann', 'Manuel Neuer', 'Alexander Nübel', 'Waldemar Anton', 'Nathaniel Brown', 'David Raum', 'Nico Schlotterbeck', 'Malick Thiaw', 'Pascal Groß', 'Felix Nmecha', 'Aleksandar Pavlović', 'Angelo Stiller', 'Nadiem Amiri', 'Leon Goretzka', 'Maximilian Beier', 'Lennart Karl', 'Jamie Leweling', 'Nick Woltemade', 
         'Simon Adingra', 'Amad Diallo', 'Seko Fofana', 'Ibrahim Sangaré', 'Ousmane Diomandé', 'Evan N’Dicka', 'Elye Wahi', 'Yahia Fofana', 'Wilfried Singo', 'Nicolas Pépé', 'Evann Guessand', 'Mohamed Koné', 'Alban Lafont', 'Emmanuel Agbadou', 'Clément Akpa', 'Guéla Doué', 'Ghislain Konan', 'Odilon Kossounou', 'Parfait Guiagon', 'Christ Inao Oulai', 'Franck Kessié', 'Jean Michaël Seri', 'Ange-Yoan Bonny', 'Oumar Diakité', 'Yan Diomande', 'Bazoumana Touré'] },
    { id: '35', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO E', local: 'ECUADOR', bandera_local: '🇪🇨', visitante: 'CURAZAO', bandera_visitante: '🇨🇼', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '21:00', jugadores: ['Tahith Chong', 'Leandro Bacuna', 'Juninho Bacuna', 'Eloy Room', 'Armando Obispo', 'Riechedly Bazoer', 'Shurandy Sambo', 'Sherel Floranus', 'Juriën Gaari', 'Jürgen Locadia', 'Sontje Hansen', 'Livano Comenencia', 'Kenji Gorré', 'Tyrick Bodak', 'Trevor Doornbusch', 'Joshua Brenet', 'Roshon Van Eijma', 'Deveron Fonville', 'Kevin Felida', 'Arjany Martha', 'Tyrese Noslin', 'Godfried Roemeratoe', 'Jeremy Antonisse', 'Gervane Kastaneer', 'Brandley Kuwas', 'Jearl Margaritha',
         'Hernán Galíndez', 'Gonzalo Valle', 'Moisés Ramírez', 'Ángelo Preciado', 'Félix Torres', 'Jackson Porozo', 'Joel Ordóñez', 'Willian Pacho', 'Piero Hincapié', 'Yaimar Medina', 'Pervis Estupiñán', 'Alan Franco', 'Denil Castillo', 'John Yeboah', 'Jordy Alcívar', 'Kendry Páez', 'Moisés Caicedo', 'Pedro Vite', 'Alan Minda', 'Anthony Valencia', 'Gonzalo Plata', 'Enner Valencia', 'Jordy Caicedo', 'Jeremy Arévalo', 'Nilson Angulo', 'Kevin Rodríguez'] },
    { id: '36', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO F', local: 'TÚNEZ', bandera_local: '🇹🇳', visitante: 'JAPÓN', bandera_visitante: '🇯🇵', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '1:00', jugadores: ['Takefusa Kubo', 'Wataru Endō', 'Zion Suzuki', 'Ritsu Dōan', 'Ayase Ueda', 'Hiroki Itō', 'Daichi Kamada', 'Yukinari Sugawara', 'Ao Tanaka', 'Kō Itakura', 'Daizen Maeda', 'Tomoki Hayakawa', 'Keisuke Ōsako', 'Yūto Nagatomo', 'Shōgo Taniguchi', 'Tsuyoshi Watanabe', 'Takehiro Tomiyasu', 'Ayumu Seko', 'Junnosuke Suzuki', 'Junya Itō', 'Keito Nakamura', 'Kaishū Sano', 'Yuito Suzuki', 'Kento Shiogai', 'Kōki Ogawa', 'Keisuke Gotō',
         'Hannibal Mejbri', 'Ellyes Skhiri', 'Elias Achouri', 'Ismaël Gharbi', 'Montassar Talbi', 'Aymen Dahmen', 'Elias Saad', 'Ali Abdi', 'Yan Valery', 'Rani Khedira', 'Marouane Chamakh', 'Sabri Ben Hassen', 'Moutaz Neffati', 'Dylan Bronn', 'Omar Rekik', 'Adem Arous', 'Raed Chikhaoui', 'Amine Ben Hamida', 'Hadj Mahmoud', 'Anis Ben Slimane', 'Mortadha Ben Ouanes', 'Khalil Ayari', 'Firas Chaouat', 'Hazem Mastouri', 'Rayan Elloumi', 'Sebastian Tounekti'] },
    { id: '37', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO H', local: 'ESPAÑA', bandera_local: '🇪🇸', visitante: 'ARABIA SAUDITA', bandera_visitante: '🇸🇦', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '13:00', jugadores: ['Unai Simón', 'David Raya', 'Joan García', 'Pedro Porro', 'Marcos Llorente', 'Aymeric Laporte', 'Pau Cubarsi', 'Marc Pubill', 'Eric García', 'Marc Cucurella', 'Alejandro Grimaldo', 'Rodrigo Hernández', 'Martín Zubimendi', 'Pedri', 'Fabían Ruiz', 'Dani Olmo', 'Mikel Merino', 'Gavi', 'Alex Baena', 'Lamine Yamal', 'Yeremy Pino', 'Ferrán Torres', 'Mikel Oyarzabal', 'Borja Iglesias', 'Nico Williams', 'Víctor Muñoz', ] },
    { id: '38', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO G', local: 'BÉLGICA', bandera_local: '🇧🇪', visitante: 'IRÁN', bandera_visitante: '🇮🇷', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '16:00', jugadores: ['Kevin De Bruyne', 'Jérémy Doku', 'Romelu Lukaku', 'Leandro Trossard', 'Youri Tielemans', 'Thibaut Courtois', 'Amadou Onana', 'Arthur Theate', 'Charles De Ketelaere', 'Timothy Castagne', 'Zeno Debast', 'Senne Lammens', 'Mike Penders', 'Maxim De Cuyper', 'Koni De Winter', 'Brandon Mechele', 'Thomas Meunier', 'Nathan Ngoy', 'Joaquin Seys', 'Nicolas Raskin', 'Hans Vanaken', 'Axel Witsel', 'Matías Fernández-Pardo', 'Dodi Lukébakio', 'Diego Moreira', 'Alexis Saelemaekers', 
         'Alireza Beiranvand', 'Seyed Hossein Hosseini', 'Payam Niazmand', 'Danial ⁠Eiri', 'Ehsan Hajsafi', 'Saleh Hardani', 'Hossein Kanaani', 'Shoja Khalilzadeh', 'Milad Mohammadi', 'Ali Nemati', 'Ramin Rezaeian', 'Rouzbeh Cheshmi', 'Saeid Ezatolahi', 'Mehdi Ghaedi', 'Saman Ghoddos', 'Mohammad Ghorbani', 'Alireza Jahanbakhsh', 'Mohammad Mohebi', 'Amir Mohammad Razzaghinia', 'Mehdi Torabi', 'Aria Yousefi', 'Ali Alipour', 'Dennis Dargahi', 'Amirhossein Hosseinzadeh', 'Mehdi Taremi', 'Shahriar Moghanlou'] },
    { id: '39', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO H', local: 'URUGUAY', bandera_local: '🇺🇾', visitante: 'CABO VERDE', bandera_visitante: '🇨🇻', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '19:00', jugadores: ['Sergio Rochet', 'Fernando Muslera', 'Santiago Mele', 'Ronald Araujo', 'Guillermo Varela', 'Jose María Giménez', 'Santiago Bueno', 'Sebatían Cáceres', 'Mathías Olivera', 'Matías Viña', 'Joaquín Piquerez', 'Manuel Ugarte', 'Rodrigo Bentancur', 'Federico Valverde', 'Giorgian De Arrascaeta', 'Rodrigo Zalazar', 'Nicolás de la Cruz', 'Agustín Canobbio', 'Facundo Pellistri', 'Brian Rodríguez', 'Juan Manuel Sanabria', 'Maximiliano Araujo', 'Darwin Núñez', 'Rodrigo Aguirre', 'Federico Viñas',
         'Ryan Mendes', 'Logan Costa', 'Josimar Dias (Vozinha)', 'Garry Rodrigues', 'Kevin Pina', 'Jovane Cabral', 'Roberto Lopes', 'Jamiro Monteiro', 'Steven Moreira', 'Deroy Duarte', 'Márcio Rosa', 'Carlos Santos', 'Wagner Pina', 'João Paulo Fernandes', 'Sidny Lopes Cabral', 'Kelvin Pires', 'Ianique Tavares (Stopíra)', 'Edilson Borges (Diney)', 'Telmo Arcanjo', 'Yannick Semedo', 'Laros Duarte', 'Willy Semedo', 'Nuno da Costa', 'Dailon Livramento', 'Gilson Tavares', 'Hélio Varela'] },
    { id: '40', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO G', local: 'NUEVA ZELANDA', bandera_local: '🇳🇿', visitante: 'EGIPTO', bandera_visitante: '🇪🇬', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '22:00', jugadores: ['Mohamed Salah', 'Omar Marmoush', 'Mahmoud Trézéguet', 'Mohamed Abdelmonem', 'Mohamed El Shenawy', 'Emam Ashour', 'Ahmed Sayed', 'Mohamed Hany', 'Ahmed Fatouh', 'Mostafa Shobeir', 'Al-Mahdy Soliman', 'Mohamed Alaa', 'Tarek Alaa', 'Hamdy Fathy', 'Ramy Rabia', 'Yasser Ibrahim', 'Hossam Abdelmaguid', 'Karim Hafez', 'Marwan Attia', 'Mohanad Lasheen', 'Nabil Emad', 'Mahmoud Saber', 'Mostafa Ziko', 'Ibrahim Adel', 'Haissem Hassan',
         'Chris Wood', 'Liberato Cacace', 'Joe Bell', 'Michael Boxall', 'Sarpreet Singh', 'Tyler Bindon', 'Ben Waine', 'Kosta Barbarouses', 'Max Crocombe', 'Alex Paulsen', 'Michael Woud', 'Callan Elliot', 'Tim Payne', 'Nando Pijnaker', 'Tommy Smith', 'Finn Surman', 'Francis de Vries', 'Lachlan Bayliss', 'Matthew Garbett', 'Elijah Just', 'Ben Old', 'Alex Rufer', 'Marko Stamenić', 'Ryan Thomas', 'Callum McCowatt', 'Jesse Randall'] },
    { id: '41', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO J', local: 'ARGENTINA', bandera_local: '🇦🇷', visitante: 'AUSTRIA', bandera_visitante: '🇦🇹', fecha: '22 de Junio', fecha_iso: '2026-06-22', hora: '14:00', jugadores: ['Emiliano Martínez', 'Gerónimo Rulli', 'Juan Musso', 'Leonardo Balerdi', 'Nicolás Tagliafico', 'Gonzalo Montiel', 'Lisandro Martínez', 'Cristian Romero', 'Nicolás Otamendi', 'Facundo Medina', 'Nahuel Molina', 'Leandro Paredes', 'Rodrigo De Paul', 'Valentín Barco', 'Giovani Lo Celso', 'Exequiel Palacios', 'Alexis Mac Allister', 'Enzo Fernández', 'Julián Álvarez', 'Lionel Messi', 'Nico González', 'Thiago Almada', 'Giuliano Simeone', 'Nico Paz', 'José Manuel López', 'Lautaro Martínez',
         'Marcel Sabitzer', 'Konrad Laimer', 'David Alaba', 'Christoph Baumgartner', 'Kevin Danso', 'Michael Gregoritsch', 'Stefan Posch', 'Patrick Pentz', 'Patrick Wimmer', 'Nicolas Seiwald', 'Romano Schmid', 'Philipp Lienhart', 'Alexander Schlager', 'Florian Wiegele', 'David Affengruber', 'Phillipp Mwene', 'Alexander Prass', 'Marco Friedl', 'Michael Svoboda', 'Xaver Schlager', 'Florian Grillitsch', 'Carney Chukwuemeka', 'Paul Wanner', 'Alessandro Schöpf', 'Marko Arnautovic', 'Sasa Kalajdzic'] },
    { id: '42', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO I', local: 'FRANCIA', bandera_local: '🇫🇷', visitante: 'IRAK', bandera_visitante: '🇮🇶', fecha: '22 de Junio', fecha_iso: '2026-06-22', hora: '18:00', jugadores: ['Kylian Mbappé', 'Michael Olise', 'Mike Maignan', 'William Saliba', 'Aurélien Tchouaméni', 'Ousmane Dembélé', 'Theo Hernández', 'Bradley Barcola', 'Warren Zaïre-Emery', 'Marcus Thuram', 'Robin Risser', 'Brice Samba', 'Lucas Digne', 'Malo Gusto', 'Lucas Hernandez', 'Ibrahima Konate', 'Jules Kounde', 'Maxence Lacroix', 'Dayot Upamecano', 'NGolo Kante', 'Manu Kone', 'Adrien Rabiot', 'Maghnes Akliouche', 'Rayan Cherki', 'Desire Doue', 'Jean-Philippe Mateta',
         'Jalal Hassan', 'Ahmed Basil', 'Fahad Talib', 'Akam Hashen', 'Rebin Sulaka', 'Zaid Tahseem', 'Manaf Younis', 'Merchas Doski', 'Ahmed Yahya', 'Hussein Ali', 'Mustafa Saadoon', 'Frans Putros', 'Zaid Ismail', 'Zidane Iqbal', 'Aimar Sher', 'Amir Almmari', 'Kevin Yakob', 'Ibrahim Bayesh', 'Marko Farji', 'Youssef Amyn', 'Ahmed Qasim', 'Ali Jassim', 'Mohanad Ali', 'Aymen Hussein', 'Ali Al Hamadi', 'Ali Yousef'] },
    { id: '43', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO I', local: 'NORUEGA', bandera_local: '🇳🇴', visitante: 'SENEGAL', bandera_visitante: '🇸🇳', fecha: '22', fecha_iso: '2026-06-22', hora: '21:00', jugadores: ['Édouard Mendy', 'Ismaïla Sarr', 'Pape Matar Sarr', 'Lamine Camara', 'Idrissa Gana Gueye', 'Iliman Ndiaye', 'Moussa Niakhaté', 'Mory Diaw', 'Yehvann Diouf', 'Krépin Diatta', 'Antoine Mendy', 'Kalidou Koulibaly', 'El Hadji Malick Diouf', 'Mamadou Sarr', 'Moustapha Mbow', 'Abdoulaye Seck', 'Ismail Jakobs', 'Ilay Camara', 'Pape Gueye', 'Habib Diarra', 'Pathé Ciss', 'Bara Sapoko Ndiaye', 'Sadio Mané', 'Assane Diao', 'Ibrahim Mbaye', 'Nicolas Jackson', 'Bamba Dieng', 'Cherif Ndiaye',
         'Erling Haaland', 'Martin Ødegaard', 'Alexander Sørloth', 'Antonio Nusa', 'Julian Ryerson', 'Sander Berge', 'Oscar Bobb', 'Ørjan Nyland', 'Leo Østigård', 'David Møller Wolfe', 'Jørgen Strand Larsen', 'Egil Selvik', 'Sander Tangvik', 'Kristoffer Vassbakk Ajer', 'Fredrik Bjorkan', 'Henrik Falchener', 'Sondre Langas', 'Torbjorn Heggem', 'Marcus Holmgren Pedersen', 'Thelonious Aasgaard', 'Fredrik Aursnes', 'Patrick Berg', 'Jens Petter Hauge', 'Andreas Schjelderup', 'Morten Thorsby', 'Kristian Thorstvedt'] },
    { id: '44', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO J', local: 'JORDANIA', bandera_local: '🇯🇴', visitante: 'ARGELIA', bandera_visitante: '🇩🇿', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '0:00', jugadores: ['Luca Zidane', 'Oussama Benbot', 'Melvin Mastil', 'Abdelatif Ramdane', 'Rafik Belghali', 'Samir Chergui', 'Rayan Aït-Nouri', 'Jaouen Hadjam', 'Aïssa Mandi', 'Ramy Bensebaini', 'Zineddine Belaïd', 'Achref Abada', 'Mohamed Amine Tougai', 'Nabil Bentaleb', 'Hicham Boudaoui', 'Houssem Aouar', 'Farès Chaïbi', 'Ibrahim Maza', 'Yacine Titraoui', 'Ramiz Zerrouki', 'Mohamed Amoura', 'Nadhir Benbouali', 'Adil Boulbina', 'Farès Ghedjemis', 'Amine Gouiri', 'Anis Hadj Moussa', 'Riyad Mahrez',
    ] },
    { id: '45', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO K', local: 'PORTUGAL', bandera_local: '🇵🇹', visitante: 'UZBEKISTÁN', bandera_visitante: '🇺🇿', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '14:00', jugadores: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva', 'Rafael Leão', 'Rúben Dias', 'Diogo Costa', 'João Félix', 'Vitinha', 'Nuno Mendes', 'João Neves', 'Gonçalo Ramos', 'José Sá', 'Rui Silva', 'Ricardo Velho', 'Diogo Dalot', 'Matheus Nunes', 'Nélson Semedo', 'Joao Cancelo', 'Gonçalo Inácio', 'Renato Veiga', 'Tomás Araújo', 'Rúben Neves', 'Samú Costa', 'Francisco Trincao', 'Francisco Conceiçao', 'Pedro Neto', 'Gonçalo Guedes',
         'Utkir Yusupov', 'Botirali Ergashev', 'Abdovkih Nematov', 'Rustamjon Ashurmatov', 'Umarbek Eshmurodov', 'Avazbek Ylmasaliev', 'Abduqodir Khusanov', 'Abdulla Abdulaev', 'Jakhongir Urozov', 'Khojiakbar Alijonov', 'Berhuz Karimov', 'Ruslanbek Jiyanov', 'Farrukh Sayfiev', 'Sherzos Nasrrulaev', 'Umarali Rakmonaliev', 'Azizjon Ganiev', 'Akmal Mozgovoy', 'Sherzod Ezanov', 'Otakeb Shukubov', 'Odiljon Khamrobekov', 'Dostonbek Khamdamov', 'Jamshid Iskanderov', 'Jasur Jaloliddinov', 'Abbosek Fayzullaev', 'Oston Urunov', 'Jaloliddin Masharipov', 'Azizbek Amonov', 'Eldor Shomurodov', 'Igor Sergeev', 'Sherdoz Temirov'] },
    { id: '46', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO L', local: 'INGLATERRA', bandera_local: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', visitante: 'GHANA', bandera_visitante: '🇬🇭', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '17:00', jugadores: ['Harry Kane', 'Jude Bellingham', 'Bukayo Saka', 'Declan Rice', 'Jordan Pickford', 'John Stones', 'Reece James', 'Marcus Rashford', 'Kobbie Mainoo', 'Marc Guéhi', 'Dean Henderson', 'James Trafford', 'Dan Burn', 'Ezri Konsa', 'Tino Livramento', 'Nico O Reilly', 'Jarell Quansah', 'Djed Spence', 'Elliot Anderson', 'Eberechi Eze', 'Jordan Henderson', 'Morgan Rogers', 'Anthony Gordon', 'Noni Madueke', 'Ivan Toney', 'Ollie Watkins',
         'Benjamín Asare', 'Lawrence Ati-Zigi', 'Joseph Anang', 'Salomon Agbasi', 'Paul Reverson', 'Baba Abdul Rahman', 'Gideon Mensah', 'Marvin Senaya', 'Alidu Seidu', 'Abdul Mumin', 'Jerome Opoku', 'Jonas Adjetey', 'Kojo Oppong Preprah', 'Alexander Djiku', 'Elisha Owusu', 'Thomas Partey', 'Kwasi Sibo', 'Augustine Boakye', 'Caleb Yirenkyi', 'Abdul Fatawu Issahaku', 'Kamal Deen Sulemana', 'Christopher Bonsu Baah', 'Ernest Nuamah', 'Antoine Semenyo', 'Brandon Thomas-Asante', 'Prince Kwabena Adu', 'Iñaki Williams', 'Jordan Ayew'] },
    { id: '47', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO L', local: 'PANAMÁ', bandera_local: '🇵🇦', visitante: 'CROACIA', bandera_visitante: '🇭🇷', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '20:00', jugadores: ['Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić', 'Dominik Livaković', 'Martin Baturina', 'Andrej Kramarić', 'Josip Šutalo', 'Josip Stanišić', 'Mario Pašalić', 'Dominik Kotarski', 'Ivor Pandur', 'Duje Ćaleta-Car', 'Marin Pongračić', 'Martin Erlić', 'Luka Vušković', 'Nikola Vlašić', 'Luka Sučić', 'Kristijan Jakić', 'Petar Sučić', 'Nikola Moro', 'Toni Fruk', 'Ivan Perišić', 'Ante Budimir', 'Marco Pašalić', 'Petar Musa', 'Igor Matanović',
         'Orlando Mosquera', 'Luis Mejía', 'César Samudio', 'César Blackman', 'Jorge Gutiérrez', 'Amir Murillo', 'Fidel Escobar', 'Andrés Andrade', 'Edgardo Fariña', 'José Córdoba', 'Eric Davis', 'Jiovany Ramos', 'Roderick Miller', 'Aníbal Godoy', 'Adalberto Carrasquilla', 'Carlos Harvey', 'Cristian Martínez', 'José Luis Rodríguez', 'César Yanis', 'Yoel Bárcenas', 'Alberto Quintero', 'Azarías Londoño', 'Ismael Díaz', 'Cecilio Waterman', 'José Fajardo', 'Tomás Rodríguez'] },
    { id: '48', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO K', local: 'COLOMBIA', bandera_local: '🇨🇴', visitante: 'RD CONGO', bandera_visitante: '🇨🇩', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '23:00', jugadores: ['Camilo Vargas', 'David Ospina', 'Álvaro Montero', 'Daniel Muñoz', 'Santiago Arias', 'Yerry Mina', 'Davinson Sánchez', 'Jhon Lucumí', 'Willer Ditta', 'Yohan Mojica', 'Déiver Machado', 'Richard Ríos', 'Jefferson Lerma', 'Gustavo Puerta', 'Kevin Castaño', 'Jhon Arias', 'James Rodríguez', 'Juan Fernando Quintero', 'Jorge Carrascal', 'Juan Camilo Portilla', 'Luis Díaz', 'Luis Suárez', 'Carlos Gómez', 'Jaminton Campaz', 'Jhon Córdoba', 'Juan Camilo Hernández',
         'Yoane Wissa', 'Théo Bongonda', 'Chancel Mbemba', 'Samuel Moutoussamy', 'Simon Banza', 'Meschack Elia', 'Arthur Masuaku', 'Charles Pickel', 'Dylan Batubinsika', 'Gédéon Kalulu', 'Gaël Kakuta', 'Timothy Fayulu', 'Matthieu Epolo', 'Lionel Mpasi Nzau', 'Aaron Wan-Bissaka', 'Joris Kayembe', 'Steve Kapuadi', 'Rocky Bushiri', 'Axel Tuanzebe', 'Noah Sadiki', 'Edo Kayembe', 'Ngalayel Mukau', 'Nathanaël Mbuku', 'Brian Cipenga', 'Fiston Mayele', 'Cédric Bakambu'] },
    

    { id: '49', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO B', local: 'SUIZA', bandera_local: '🇨🇭', visitante: 'CANADÁ', bandera_visitante: '🇨🇦', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '16:00', jugadores: ['Maxime Crépeau', 'Owen Goodman', 'Dayne St. Claire', 'Moïse Bombito', 'Derek Cornelius', 'Alphonso Davies', 'Luc de Fougerolles', 'Alistair Johnston', 'Alfie Jones', 'Richie Laryea', 'Niko Sigur', 'Joel Waterman', 'Ali Ahmed', 'Tajon Buchanan', 'Mathieu Choinière', 'Stephen Eustáquio', 'Marcelo Flores', 'Ismaël Koné', 'Liam Millar', 'Jonathan Osorio', 'Nathan Saliba', 'Jacob Shaffelburg', 'Jonathan David', 'Promise David', 'Cyle Larin', 'Tani Oluwaseyi',
         'Granit Xhaka', 'Manuel Akanji', 'Breel Embolo', 'Gregor Kobel', 'Remo Freuler', 'Ruben Vargas', 'Dan Ndoye', 'Zeki Amdouni', 'Michel Aebischer', 'Denis Zakaria', 'Silvan Widmer', 'Ricardo Rodríguez', 'Noah Okafor', 'Marvin Keller', 'Yvon Mvogo', 'Aurele Amenda', 'Eray Comert', 'Nico Elvedi', 'Luca Jaquez', 'Miro Muheim', 'Christian Fassnacht', 'Johan Manzambi', 'Djibril Sow', 'Cedric Itten', 'Fabian Rieder', 'Ardon Jashari'] },
    { id: '50', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO B', local: 'BOSNIA Y HERZEGOVINA', bandera_local: '🇧🇦', visitante: 'CATAR', bandera_visitante: '🇶🇦', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '16:00', jugadores: ['Edin Džeko', 'Sead Kolašinac', 'Ermedin Demirovic', 'Amar Dedić', 'Benjamin Tahirović', 'Nikola Vasilj', 'Martin Zlomislić', 'Osman Hadžikić', 'Nihad Mujakić', 'Nikola Katić', 'Tarik Muharemović', 'Stjepan Radeljić', 'Dennis Hadžikadunić', 'Nidal Čelik', 'Amir Hadžiahmetović', 'Ivan Šunjić', 'Ivan Bašić', 'Dženis Burnić', 'Ermin Mahmić', 'Amar Memić', 'Armin Gigović', 'Kerim Alajbegović', 'Esmir Bajraktarević', 'Jovo Lukić', 'Samed Baždar', 'Haris Tabaković',
         'Akram Afif', 'Almoez Ali', 'Hassan Al-Haydos', 'Meshaal Barsham', 'Lucas Mendes', 'Mohammed Waad', 'Boualem Khoukhi', 'Abdulaziz Hatem', 'Jassim Gaber', 'Tarek Salman', 'Pedro Miguel', 'Homam Ahmed', 'Yusuf Abdurisag', 'Mohammed Muntari'] },
    { id: '51', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO C', local: 'ESCOCIA', bandera_local: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', visitante: 'BRASIL', bandera_visitante: '🇧🇷', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '19:00', jugadores: ['Vinícius Júnior', 'Endrick Felipe', 'Neymar Júnior', 'Raphinha Dias', 'Gabriel Martinelli', 'Lucas Paquetá', 'Bruno Guimarães', 'Marquinhos', 'Gabriel Magalhães', 'Danilo da Silva', 'Alisson Becker', 'Ederson Moraes', 'Weverton', 'Alex Sandro', 'Gleison Bremer', 'Douglas Santos', 'Roger Ibáñez da Silva', 'Léo Pereira', 'Wesley Ribeiro Silva', 'Casemiro', 'Danilo dos Santos', 'Fabinho Tavares', 'Igor Thiago', 'Luiz Henrique', 'Matheus Cunha', 'Rayan',
         'Scott McTominay', 'John Mcginn', 'Billy Gilmour', 'Kieran Tierney', 'Angus Gunn', 'Jack Hendry', 'Che Adams', 'Ryan Christie', 'Lawrence Shankland', 'Lewis Ferguson', 'Craig Gordon', 'Liam Kelly', 'Grant Hanley', 'Aaron Hickey', 'Dominic Hyam', 'Scott McKenna', 'Nathan Patterson', 'Anthony Ralston', 'Andrew Robertson', 'John Souttar', 'Findlay Curtis', 'Ben Gannon-Doak', 'Kenny McLean', 'Lyndon Dykes', 'George Hirst', 'Ross Stewart'] },
    { id: '52', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO C', local: 'MARRUECOS', bandera_local: '🇲🇦', visitante: 'HAITÍ', bandera_visitante: '🇭🇹', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '19:00', jugadores: ['Yassine Bounou', 'Munir Mohand Mohamedi', 'Ahmed Reda Tagnaouti', 'Achraf Hakimi', 'Noussair Mazraoui', 'Anass Salah-Eddine', 'Youssef Belammari', 'Issa Diop', 'Chadi Riad', 'Zakaria El Ouahdi', 'Redouane Halhal', 'Nayef Aguerd', 'Neil El Aynaoui', 'Bilal El Khannouss', 'Azzedine Ounahi', 'Ayyoub Bouaddi', 'Ismael Saibari', 'Sofyan Amrabat', 'Samir El Mourabet', 'Brahim Díaz', 'Abde Ezzalzouli', 'Ayoube Amaimouni', 'Soufiane Rahimi', 'Chemsdine Talbi', 'Gessime Yassine', 'Ayoub El Kaabi',
         'Duckens Nazon', 'Frantzdy Pierrot', 'Johny Placide', 'Carlens Arcus', 'Leverton Pierre', 'Ricardo Adé', 'Jean-Kévin Duverne', 'Alexandre Pierre', 'Josué Duverger', 'Wilguens Paugain', 'Duke Lacroix', 'Martin Experiénce', 'Hannes Delcroix', 'Keeto Thermoncy', 'Carl Sainté', 'Danley Jean Jacques', 'Jean-Ricner Bellegarde', 'Woodensky Pierre', 'Dominique Simon', 'Louicius Don Deedson', 'Ruben Providence', 'Josué Casimir', 'Derrick Etienne', 'Wilson Isidor', 'Yassin Fortune', 'Lenny Joseph'] },
    { id: '53', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO A', local: 'REP. CHECA', bandera_local: '🇨🇿', visitante: 'MÉXICO', bandera_visitante: '🇲🇽', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '22:00', jugadores: ['Raúl Rangel', 'Carlos Acevedo', 'Guillermo Ochoa', 'César Montes', 'Johan Vásquez', 'Mateo Chávez', 'Jesús Gallardo', 'Israel Reyes', 'Jorge Sánchez', 'Erik Lira', 'Luis Romo', 'Obed Vargas', 'Brian Gutiérrez', 'Oberlín Pineda', 'Edson Álvarez', 'Gilberto Mora', 'César Huerta', 'Álvaro Fidalgo', 'Luis Chávez', 'Roberto Alvarado', 'Alexis Vega', 'Julián Quiñones', 'Santiago Gimenez', 'Guillermo Martínez', 'Armando González', 'Raúl Jiménez',
         'Jindřich Staněk', 'Matěj Kovář', 'Lukáš Horníček', 'Vladimír Coufal', 'Tomáš Holeš', 'David Jurásek', 'Jaroslav Zelený', 'Ladislav Krejčí', 'Štěpán Chaloupek', 'Robin Hranáč', 'David Douděra', 'David Zima', 'Tomáš Souček', 'Lukáš Provod', 'Michal Sadílek', 'Pavel Šulc', 'Vladimír Darida', 'Alexandr Sojka', 'Lukáš Červ', 'Tomáš Ladra', 'Hugo Sochurek', 'Pavel Bucha', 'Denis Višinský', 'Tomáš Chorý', 'Patrik Schick', 'Mojmír Chytil', 'Jan Kuchta', 'Christophe Kabongo', 'Adam Hložek'] },
    { id: '54', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO A', local: 'SUDAFRICA', bandera_local: '🇿🇦', visitante: 'COREA DEL SUR', bandera_visitante: '🇰🇷', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '22:00', jugadores: ['Ronwen Williams', 'Ricardo Goss', 'Sipho Chaine', 'Khuliso Mudau', 'Olwethu Makhanya', 'Bradley Cross', 'Aubrey Modiba', 'Thabang Matuludi', 'Nkosinathi Sibisi', 'Ime Okon', 'Samukele Kabini', 'Mbekezeli Mbokazi', 'Kamolego Sebelebele', 'Khulumani Ndamane', 'Teboho Mokoena', 'Thalente Mbatha', 'Jayden Adams', 'Shephelo Sithole', 'Oswin Appollis', 'Tshepang Moremi', 'Evidence Makgopa', 'Lyle Foster', 'Ioraam Rayners', 'Relebohile Mofokeng', 'Themba Zawne', 'Thapelo Maseko',
         'Son Heung-Min', 'Kim Min-jae', 'Cho Gue-sung', 'Hwang In-beom', 'Jo Hyeon-woo', 'Lee Jae-sung', 'Paik Seung-ho', 'Oh Hyeon-gyu', 'Seol Young-woo', 'Kim Seung-Gyu', 'Song Bum-keun', 'Kim Moon-hwan', 'Kim Tae-hyeon', 'Park Jin-seop', 'Jens Castrop', 'Lee Ki-hyuk', 'Lee Tae-seok', 'Lee Han-beom', 'Cho Yu-min', 'Kim Jin-gyu', 'Jun-Ho Bae', 'Yang Hyun-jun', 'Eom Ji-sung', 'Lee Kang-in', 'Lee Dong-gyeong', 'Hwang Hee-chan'] },
    { id: '55', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO E', local: 'CURAZAO', bandera_local: '🇨🇼', visitante: 'COSTA DE MARFIL', bandera_visitante: '🇨🇮', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '17:00', jugadores: ['Tahith Chong', 'Leandro Bacuna', 'Juninho Bacuna', 'Eloy Room', 'Armando Obispo', 'Riechedly Bazoer', 'Shurandy Sambo', 'Sherel Floranus', 'Juriën Gaari', 'Jürgen Locadia', 'Sontje Hansen', 'Livano Comenencia', 'Kenji Gorré', 'Tyrick Bodak', 'Trevor Doornbusch', 'Joshua Brenet', 'Roshon Van Eijma', 'Deveron Fonville', 'Kevin Felida', 'Arjany Martha', 'Tyrese Noslin', 'Godfried Roemeratoe', 'Jeremy Antonisse', 'Gervane Kastaneer', 'Brandley Kuwas', 'Jearl Margaritha',
         'Simon Adingra', 'Amad Diallo', 'Seko Fofana', 'Ibrahim Sangaré', 'Ousmane Diomandé', 'Evan N’Dicka', 'Elye Wahi', 'Yahia Fofana', 'Wilfried Singo', 'Nicolas Pépé', 'Evann Guessand', 'Mohamed Koné', 'Alban Lafont', 'Emmanuel Agbadou', 'Clément Akpa', 'Guéla Doué', 'Ghislain Konan', 'Odilon Kossounou', 'Parfait Guiagon', 'Christ Inao Oulai', 'Franck Kessié', 'Jean Michaël Seri', 'Ange-Yoan Bonny', 'Oumar Diakité', 'Yan Diomande', 'Bazoumana Touré'] },
    { id: '56', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO E', local: 'ECUADOR', bandera_local: '🇪🇨', visitante: 'ALEMANIA', bandera_visitante: '🇩🇪', fecha: '25', fecha_iso: '2026-06-25', hora: '17:00', jugadores: ['Florian Wirtz', 'Jamal Musiala', 'Kai Havertz', 'Joshua Kimmich', 'Antonio Rüdiger', 'Leroy Sané', 'Jonathan Tah', 'Deniz Undav', 'Oliver Baumann', 'Manuel Neuer', 'Alexander Nübel', 'Waldemar Anton', 'Nathaniel Brown', 'David Raum', 'Nico Schlotterbeck', 'Malick Thiaw', 'Pascal Groß', 'Felix Nmecha', 'Aleksandar Pavlović', 'Angelo Stiller', 'Nadiem Amiri', 'Leon Goretzka', 'Maximilian Beier', 'Lennart Karl', 'Jamie Leweling', 'Nick Woltemade', 
         'Hernán Galíndez', 'Gonzalo Valle', 'Moisés Ramírez', 'Ángelo Preciado', 'Félix Torres', 'Jackson Porozo', 'Joel Ordóñez', 'Willian Pacho', 'Piero Hincapié', 'Yaimar Medina', 'Pervis Estupiñán', 'Alan Franco', 'Denil Castillo', 'John Yeboah', 'Jordy Alcívar', 'Kendry Páez', 'Moisés Caicedo', 'Pedro Vite', 'Alan Minda', 'Anthony Valencia', 'Gonzalo Plata', 'Enner Valencia', 'Jordy Caicedo', 'Jeremy Arévalo', 'Nilson Angulo', 'Kevin Rodríguez',] },
    { id: '57', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO F', local: 'JAPÓN', bandera_local: '🇯🇵', visitante: 'SUECIA', bandera_visitante: '🇸🇪', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '20:00', jugadores: ['Takefusa Kubo', 'Wataru Endō', 'Zion Suzuki', 'Ritsu Dōan', 'Ayase Ueda', 'Hiroki Itō', 'Daichi Kamada', 'Yukinari Sugawara', 'Ao Tanaka', 'Kō Itakura', 'Daizen Maeda', 'Tomoki Hayakawa', 'Keisuke Ōsako', 'Yūto Nagatomo', 'Shōgo Taniguchi', 'Tsuyoshi Watanabe', 'Takehiro Tomiyasu', 'Ayumu Seko', 'Junnosuke Suzuki', 'Junya Itō', 'Keito Nakamura', 'Kaishū Sano', 'Yuito Suzuki', 'Kento Shiogai', 'Kōki Ogawa', 'Keisuke Gotō',
         'Viktor Gyökeres', 'Alexander Isak', 'Lucas Bergvall', 'Victor Lindelöf', 'Isak Hien', 'Anthony Elanga', 'Yasin Ayari', 'Daniel Svensson', 'Viktor Johansson', 'Kristoffer Nordfeldt', 'Jacob Widell Zetterström', 'Gabriel Gudmundsson', 'Emil Holm', 'Gustaf Lagerbielke', 'Eric Smith', 'Carl Starfelt', 'Elliot Stroud', 'Jesper Karlström', 'Mattias Svanberg', 'Besfort Zeneli', 'Ken Sema', 'Taha Ali', 'Alexander Bernhardsson', 'Gustaf Nilsson', 'Benjamin Nygren'] },
    { id: '58', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO F', local: 'TÚNEZ', bandera_local: '🇹🇳', visitante: 'PAISES BAJOS', bandera_visitante: '🇳🇱', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '20:00', jugadores: ['Mark Flekken', 'Robin Roefs', 'Bart Verbruggen', 'Nathan Aké', 'Virgil van Dijk', 'Denzel Dumfries', 'Jorrel Hato', 'Jan Paul van Hecke', 'Jurriën Timber', 'Micky van de Ven', 'Ryan Gravenberch', 'Frenkie de Jong', 'Justin Kluivert', 'Teun Koopmeiners', 'Marten de Roon', 'Guus Til', 'Quinten Timber', 'Mats Wieffer', 'Brian Brobbey', 'Memphis Depay', 'Cody Gakpo', 'Noa Lang', 'Donyell Malen', 'Tijjani Reijnders', 'Crysencio Summerville', 'Wout Weghorst',
         'Hannibal Mejbri', 'Ellyes Skhiri', 'Elias Achouri', 'Ismaël Gharbi', 'Montassar Talbi', 'Aymen Dahmen', 'Elias Saad', 'Ali Abdi', 'Yan Valery', 'Rani Khedira', 'Marouane Chamakh', 'Sabri Ben Hassen', 'Moutaz Neffati', 'Dylan Bronn', 'Omar Rekik', 'Adem Arous', 'Raed Chikhaoui', 'Amine Ben Hamida', 'Hadj Mahmoud', 'Anis Ben Slimane', 'Mortadha Ben Ouanes', 'Khalil Ayari', 'Firas Chaouat', 'Hazem Mastouri', 'Rayan Elloumi', 'Sebastian Tounekti'] },
    { id: '59', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO D', local: 'TURQUIA', bandera_local: '🇹🇷', visitante: 'ESTADOS UNIDOS', bandera_visitante: '🇺🇸', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '23:00', jugadores: ['Matt Freese', 'Matt Turner', 'Chris Brady', 'Max Arfsten', 'Sergiño Dest', 'Alex Freeman', 'Mark McKenzie', 'Tim Ream', 'Chris Richards', 'Antonee Robinson', 'Miles Robinson', 'Joe Scally', 'Auston Trusty', 'Tyler Adams', 'Sebastian Berhalter', 'Weston McKennie', 'Cristian Roldán', 'Brenden Aaronson', 'Christian Pulisic', 'Gio Reyna', 'Malik Tillman', 'Tim Weah', 'Alejandro Zendejas', 'Folarin Balogun', 'Ricardo Pepi', 'Haji Wright'] },
    { id: '60', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO D', local: 'PARAGUAY', bandera_local: '🇵🇾', visitante: 'AUSTRALIA', bandera_visitante: '🇦🇺', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '23:00', jugadores: ['Orlando Gill', 'Roberto Jr. Fernández', 'Gastón Olveira', 'Juan José Cáceres', 'José Canale', 'Fabián Balbuena', 'Omar Alderete', 'Gustavo Gómez', 'Alexandro Maidana', 'Junior Alonso', 'Gustavo Velázquez', 'Braian Ojeda', 'Damián Bobadilla', 'Andrés Cubas', 'Diego Gómez Gómez', 'Alejandro Romero Gamarra', 'Mauricio Prado', 'Matías Galarza', 'Ramón Sosa', 'Gustavo Caballero', 'Miguel Almirón', 'Gabriel Ávalos', 'Isidro Pitta', 'Álex Arce', 'Julio Enciso', 'Antonio Sanabria',
         'Patrick Beach', 'Paul Izzo', 'Aziz Behich', 'Jordan Bos', 'Cameron Burgess', 'Alessandro Circati', 'Milos Degenek', 'Jason Geria', 'Lucas Herrington', 'Jacob Italiano', 'Harry Souttar', 'Kai Trewin', 'Cameron Devlin', 'Ajdin Hrustić', 'Jackson Irvine', 'Connor Metcalfe', 'Paul Okon-Engstler', 'Aiden ONeill', 'Nestory Irankunda', 'Mathew Leckie', 'Awer Mabil', 'Mohamed Touré', 'Nishan Velupillay', 'Cristian Volpato', 'Tete Yengi'] },
    { id: '61', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO I', local: 'NORUEGA', bandera_local: '🇳🇴', visitante: 'FRANCIA', bandera_visitante: '🇫🇷', fecha: '26 de Junio', fecha_iso: '2026-06-26', hora: '16:00', jugadores: ['Kylian Mbappé', 'Michael Olise', 'Mike Maignan', 'William Saliba', 'Aurélien Tchouaméni', 'Ousmane Dembélé', 'Theo Hernández', 'Bradley Barcola', 'Warren Zaïre-Emery', 'Marcus Thuram', 'Robin Risser', 'Brice Samba', 'Lucas Digne', 'Malo Gusto', 'Lucas Hernandez', 'Ibrahima Konate', 'Jules Kounde', 'Maxence Lacroix', 'Dayot Upamecano', 'NGolo Kante', 'Manu Kone', 'Adrien Rabiot', 'Maghnes Akliouche', 'Rayan Cherki', 'Desire Doue', 'Jean-Philippe Mateta',
         'Erling Haaland', 'Martin Ødegaard', 'Alexander Sørloth', 'Antonio Nusa', 'Julian Ryerson', 'Sander Berge', 'Oscar Bobb', 'Ørjan Nyland', 'Leo Østigård', 'David Møller Wolfe', 'Jørgen Strand Larsen', 'Egil Selvik', 'Sander Tangvik', 'Kristoffer Vassbakk Ajer', 'Fredrik Bjorkan', 'Henrik Falchener', 'Sondre Langas', 'Torbjorn Heggem', 'Marcus Holmgren Pedersen', 'Thelonious Aasgaard', 'Fredrik Aursnes', 'Patrick Berg', 'Jens Petter Hauge', 'Andreas Schjelderup', 'Morten Thorsby', 'Kristian Thorstvedt'] },
    { id: '62', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO I', local: 'SENEGAL', bandera_local: '🇸🇳', visitante: 'IRAK', bandera_visitante: '🇮🇶', fecha: '26 de Junio', fecha_iso: '2026-06-26', hora: '16:00', jugadores: ['Jalal Hassan', 'Ahmed Basil', 'Fahad Talib', 'Akam Hashen', 'Rebin Sulaka', 'Zaid Tahseem', 'Manaf Younis', 'Merchas Doski', 'Ahmed Yahya', 'Hussein Ali', 'Mustafa Saadoon', 'Frans Putros', 'Zaid Ismail', 'Zidane Iqbal', 'Aimar Sher', 'Amir Almmari', 'Kevin Yakob', 'Ibrahim Bayesh', 'Marko Farji', 'Youssef Amyn', 'Ahmed Qasim', 'Ali Jassim', 'Mohanad Ali', 'Aymen Hussein', 'Ali Al Hamadi', 'Ali Yousef',
         'Édouard Mendy', 'Ismaïla Sarr', 'Pape Matar Sarr', 'Lamine Camara', 'Idrissa Gana Gueye', 'Iliman Ndiaye', 'Moussa Niakhaté', 'Mory Diaw', 'Yehvann Diouf', 'Krépin Diatta', 'Antoine Mendy', 'Kalidou Koulibaly', 'El Hadji Malick Diouf', 'Mamadou Sarr', 'Moustapha Mbow', 'Abdoulaye Seck', 'Ismail Jakobs', 'Ilay Camara', 'Pape Gueye', 'Habib Diarra', 'Pathé Ciss', 'Bara Sapoko Ndiaye', 'Sadio Mané', 'Assane Diao', 'Ibrahim Mbaye', 'Nicolas Jackson', 'Bamba Dieng', 'Cherif Ndiaye'] },
    { id: '63', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO H', local: 'CABO VERDE', bandera_local: '🇨🇻', visitante: 'ARABIA SAUDITA', bandera_visitante: '🇸🇦', fecha: '26', fecha_iso: '2026-06-26', hora: '21:00', jugadores: ['Ryan Mendes', 'Logan Costa', 'Josimar Dias (Vozinha)', 'Garry Rodrigues', 'Kevin Pina', 'Jovane Cabral', 'Roberto Lopes', 'Jamiro Monteiro', 'Steven Moreira', 'Deroy Duarte', 'Márcio Rosa', 'Carlos Santos', 'Wagner Pina', 'João Paulo Fernandes', 'Sidny Lopes Cabral', 'Kelvin Pires', 'Ianique Tavares (Stopíra)', 'Edilson Borges (Diney)', 'Telmo Arcanjo', 'Yannick Semedo', 'Laros Duarte', 'Willy Semedo', 'Nuno da Costa', 'Dailon Livramento', 'Gilson Tavares', 'Hélio Varela',
         'Salem Al-Dawsari', 'Firas Al-Buraikan', 'Mohammed Al-Owais', 'Saud Abdulhamid', 'Mohamed Kanno', 'Ali Al-Bulayhi', 'Faisal Al-Ghamdi', 'Abdulelah Al-Malki', 'Hassan Tambakti', 'Nasser Al-Dawsari', 'Ali Lajami', 'Saleh Al-Shehri'] },
    { id: '64', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO H', local: 'URUGUAY', bandera_local: '🇺🇾', visitante: 'ESPAÑA', bandera_visitante: '🇪🇸', fecha: '26 de Junio', fecha_iso: '2026-06-26', hora: '21:00', jugadores: ['Sergio Rochet', 'Fernando Muslera', 'Santiago Mele', 'Ronald Araujo', 'Guillermo Varela', 'Jose María Giménez', 'Santiago Bueno', 'Sebatían Cáceres', 'Mathías Olivera', 'Matías Viña', 'Joaquín Piquerez', 'Manuel Ugarte', 'Rodrigo Bentancur', 'Federico Valverde', 'Giorgian De Arrascaeta', 'Rodrigo Zalazar', 'Nicolás de la Cruz', 'Agustín Canobbio', 'Facundo Pellistri', 'Brian Rodríguez', 'Juan Manuel Sanabria', 'Maximiliano Araujo', 'Darwin Núñez', 'Rodrigo Aguirre', 'Federico Viñas',
         'Unai Simón', 'David Raya', 'Joan García', 'Pedro Porro', 'Marcos Llorente', 'Aymeric Laporte', 'Pau Cubarsi', 'Marc Pubill', 'Eric García', 'Marc Cucurella', 'Alejandro Grimaldo', 'Rodrigo Hernández', 'Martín Zubimendi', 'Pedri', 'Fabían Ruiz', 'Dani Olmo', 'Mikel Merino', 'Gavi', 'Alex Baena', 'Lamine Yamal', 'Yeremy Pino', 'Ferrán Torres', 'Mikel Oyarzabal', 'Borja Iglesias', 'Nico Williams', 'Víctor Muñoz'] },
    { id: '65', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO G', local: 'EGIPTO', bandera_local: '🇪🇬', visitante: 'IRÁN', bandera_visitante: '🇮🇷', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '0:00', jugadores: ['Mohamed Salah', 'Omar Marmoush', 'Mahmoud Trézéguet', 'Mohamed Abdelmonem', 'Mohamed El Shenawy', 'Emam Ashour', 'Ahmed Sayed', 'Mohamed Hany', 'Ahmed Fatouh', 'Mostafa Shobeir', 'Al-Mahdy Soliman', 'Mohamed Alaa', 'Tarek Alaa', 'Hamdy Fathy', 'Ramy Rabia', 'Yasser Ibrahim', 'Hossam Abdelmaguid', 'Karim Hafez', 'Marwan Attia', 'Mohanad Lasheen', 'Nabil Emad', 'Mahmoud Saber', 'Mostafa Ziko', 'Ibrahim Adel', 'Haissem Hassan',
         'Alireza Beiranvand', 'Seyed Hossein Hosseini', 'Payam Niazmand', 'Danial ⁠Eiri', 'Ehsan Hajsafi', 'Saleh Hardani', 'Hossein Kanaani', 'Shoja Khalilzadeh', 'Milad Mohammadi', 'Ali Nemati', 'Ramin Rezaeian', 'Rouzbeh Cheshmi', 'Saeid Ezatolahi', 'Mehdi Ghaedi', 'Saman Ghoddos', 'Mohammad Ghorbani', 'Alireza Jahanbakhsh', 'Mohammad Mohebi', 'Amir Mohammad Razzaghinia', 'Mehdi Torabi', 'Aria Yousefi', 'Ali Alipour', 'Dennis Dargahi', 'Amirhossein Hosseinzadeh', 'Mehdi Taremi', 'Shahriar Moghanlou'] },
    { id: '66', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO G', local: 'NUEVA ZELANDA', bandera_local: '🇳🇿', visitante: 'BÉLGICA', bandera_visitante: '🇧🇪', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '0:00', jugadores: ['Kevin De Bruyne', 'Jérémy Doku', 'Romelu Lukaku', 'Leandro Trossard', 'Youri Tielemans', 'Thibaut Courtois', 'Amadou Onana', 'Arthur Theate', 'Charles De Ketelaere', 'Timothy Castagne', 'Zeno Debast', 'Senne Lammens', 'Mike Penders', 'Maxim De Cuyper', 'Koni De Winter', 'Brandon Mechele', 'Thomas Meunier', 'Nathan Ngoy', 'Joaquin Seys', 'Nicolas Raskin', 'Hans Vanaken', 'Axel Witsel', 'Matías Fernández-Pardo', 'Dodi Lukébakio', 'Diego Moreira', 'Alexis Saelemaekers', 
         'Chris Wood', 'Liberato Cacace', 'Joe Bell', 'Michael Boxall', 'Sarpreet Singh', 'Tyler Bindon', 'Ben Waine', 'Kosta Barbarouses', 'Max Crocombe', 'Alex Paulsen', 'Michael Woud', 'Callan Elliot', 'Tim Payne', 'Nando Pijnaker', 'Tommy Smith', 'Finn Surman', 'Francis de Vries', 'Lachlan Bayliss', 'Matthew Garbett', 'Elijah Just', 'Ben Old', 'Alex Rufer', 'Marko Stamenić', 'Ryan Thomas', 'Callum McCowatt', 'Jesse Randall'] },
    { id: '67', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO L', local: 'PANAMÁ', bandera_local: '🇵🇦', visitante: 'INGLATERRA', bandera_visitante: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '18:00', jugadores: ['Harry Kane', 'Jude Bellingham', 'Bukayo Saka', 'Declan Rice', 'Jordan Pickford', 'John Stones', 'Reece James', 'Marcus Rashford', 'Kobbie Mainoo', 'Marc Guéhi', 'Dean Henderson', 'James Trafford', 'Dan Burn', 'Ezri Konsa', 'Tino Livramento', 'Nico O Reilly', 'Jarell Quansah', 'Djed Spence', 'Elliot Anderson', 'Eberechi Eze', 'Jordan Henderson', 'Morgan Rogers', 'Anthony Gordon', 'Noni Madueke', 'Ivan Toney', 'Ollie Watkins',
         'Orlando Mosquera', 'Luis Mejía', 'César Samudio', 'César Blackman', 'Jorge Gutiérrez', 'Amir Murillo', 'Fidel Escobar', 'Andrés Andrade', 'Edgardo Fariña', 'José Córdoba', 'Eric Davis', 'Jiovany Ramos', 'Roderick Miller', 'Aníbal Godoy', 'Adalberto Carrasquilla', 'Carlos Harvey', 'Cristian Martínez', 'José Luis Rodríguez', 'César Yanis', 'Yoel Bárcenas', 'Alberto Quintero', 'Azarías Londoño', 'Ismael Díaz', 'Cecilio Waterman', 'José Fajardo', 'Tomás Rodríguez'] },
    { id: '68', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO L', local: 'CROACIA', bandera_local: '🇭🇷', visitante: 'GHANA', bandera_visitante: '🇬🇭', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '18:00', jugadores: ['Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić', 'Dominik Livaković', 'Martin Baturina', 'Andrej Kramarić', 'Josip Šutalo', 'Josip Stanišić', 'Mario Pašalić', 'Dominik Kotarski', 'Ivor Pandur', 'Duje Ćaleta-Car', 'Marin Pongračić', 'Martin Erlić', 'Luka Vušković', 'Nikola Vlašić', 'Luka Sučić', 'Kristijan Jakić', 'Petar Sučić', 'Nikola Moro', 'Toni Fruk', 'Ivan Perišić', 'Ante Budimir', 'Marco Pašalić', 'Petar Musa', 'Igor Matanović',
         'Benjamín Asare', 'Lawrence Ati-Zigi', 'Joseph Anang', 'Salomon Agbasi', 'Paul Reverson', 'Baba Abdul Rahman', 'Gideon Mensah', 'Marvin Senaya', 'Alidu Seidu', 'Abdul Mumin', 'Jerome Opoku', 'Jonas Adjetey', 'Kojo Oppong Preprah', 'Alexander Djiku', 'Elisha Owusu', 'Thomas Partey', 'Kwasi Sibo', 'Augustine Boakye', 'Caleb Yirenkyi', 'Abdul Fatawu Issahaku', 'Kamal Deen Sulemana', 'Christopher Bonsu Baah', 'Ernest Nuamah', 'Antoine Semenyo', 'Brandon Thomas-Asante', 'Prince Kwabena Adu', 'Iñaki Williams', 'Jordan Ayew'] },
    { id: '69', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO K', local: 'COLOMBIA', bandera_local: '🇨🇴', visitante: 'PORTUGAL', bandera_visitante: '🇵🇹', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '20:30', jugadores: ['Camilo Vargas', 'David Ospina', 'Álvaro Montero', 'Daniel Muñoz', 'Santiago Arias', 'Yerry Mina', 'Davinson Sánchez', 'Jhon Lucumí', 'Willer Ditta', 'Yohan Mojica', 'Déiver Machado', 'Richard Ríos', 'Jefferson Lerma', 'Gustavo Puerta', 'Kevin Castaño', 'Jhon Arias', 'James Rodríguez', 'Juan Fernando Quintero', 'Jorge Carrascal', 'Juan Camilo Portilla', 'Luis Díaz', 'Luis Suárez', 'Carlos Gómez', 'Jaminton Campaz', 'Jhon Córdoba', 'Juan Camilo Hernández',
         'Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva', 'Rafael Leão', 'Rúben Dias', 'Diogo Costa', 'João Félix', 'Vitinha', 'Nuno Mendes', 'João Neves', 'Gonçalo Ramos', 'José Sá', 'Rui Silva', 'Ricardo Velho', 'Diogo Dalot', 'Matheus Nunes', 'Nélson Semedo', 'Joao Cancelo', 'Gonçalo Inácio', 'Renato Veiga', 'Tomás Araújo', 'Rúben Neves', 'Samú Costa', 'Francisco Trincao', 'Francisco Conceiçao', 'Pedro Neto', 'Gonçalo Guedes'] },
    { id: '70', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO K', local: 'RD CONGO', bandera_local: '🇨🇩', visitante: 'UZBEKISTÁN', bandera_visitante: '🇺🇿', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '20:30', jugadores: ['Yoane Wissa', 'Théo Bongonda', 'Chancel Mbemba', 'Samuel Moutoussamy', 'Simon Banza', 'Meschack Elia', 'Arthur Masuaku', 'Charles Pickel', 'Dylan Batubinsika', 'Gédéon Kalulu', 'Gaël Kakuta', 'Timothy Fayulu', 'Matthieu Epolo', 'Lionel Mpasi Nzau', 'Aaron Wan-Bissaka', 'Joris Kayembe', 'Steve Kapuadi', 'Rocky Bushiri', 'Axel Tuanzebe', 'Noah Sadiki', 'Edo Kayembe', 'Ngalayel Mukau', 'Nathanaël Mbuku', 'Brian Cipenga', 'Fiston Mayele', 'Cédric Bakambu',
         'Utkir Yusupov', 'Botirali Ergashev', 'Abdovkih Nematov', 'Rustamjon Ashurmatov', 'Umarbek Eshmurodov', 'Avazbek Ylmasaliev', 'Abduqodir Khusanov', 'Abdulla Abdulaev', 'Jakhongir Urozov', 'Khojiakbar Alijonov', 'Berhuz Karimov', 'Ruslanbek Jiyanov', 'Farrukh Sayfiev', 'Sherzos Nasrrulaev', 'Umarali Rakmonaliev', 'Azizjon Ganiev', 'Akmal Mozgovoy', 'Sherzod Ezanov', 'Otakeb Shukubov', 'Odiljon Khamrobekov', 'Dostonbek Khamdamov', 'Jamshid Iskanderov', 'Jasur Jaloliddinov', 'Abbosek Fayzullaev', 'Oston Urunov', 'Jaloliddin Masharipov', 'Azizbek Amonov', 'Eldor Shomurodov', 'Igor Sergeev', 'Sherdoz Temirov'] },
    { id: '71', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO J', local: 'ARGELIA', bandera_local: '🇩🇿', visitante: 'AUSTRIA', bandera_visitante: '🇦🇹', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '23:00', jugadores: ['Marcel Sabitzer', 'Konrad Laimer', 'David Alaba', 'Christoph Baumgartner', 'Kevin Danso', 'Michael Gregoritsch', 'Stefan Posch', 'Patrick Pentz', 'Patrick Wimmer', 'Nicolas Seiwald', 'Romano Schmid', 'Philipp Lienhart', 'Alexander Schlager', 'Florian Wiegele', 'David Affengruber', 'Phillipp Mwene', 'Alexander Prass', 'Marco Friedl', 'Michael Svoboda', 'Xaver Schlager', 'Florian Grillitsch', 'Carney Chukwuemeka', 'Paul Wanner', 'Alessandro Schöpf', 'Marko Arnautovic', 'Sasa Kalajdzic',
         'Luca Zidane', 'Oussama Benbot', 'Melvin Mastil', 'Abdelatif Ramdane', 'Rafik Belghali', 'Samir Chergui', 'Rayan Aït-Nouri', 'Jaouen Hadjam', 'Aïssa Mandi', 'Ramy Bensebaini', 'Zineddine Belaïd', 'Achref Abada', 'Mohamed Amine Tougai', 'Nabil Bentaleb', 'Hicham Boudaoui', 'Houssem Aouar', 'Farès Chaïbi', 'Ibrahim Maza', 'Yacine Titraoui', 'Ramiz Zerrouki', 'Mohamed Amoura', 'Nadhir Benbouali', 'Adil Boulbina', 'Farès Ghedjemis', 'Amine Gouiri', 'Anis Hadj Moussa', 'Riyad Mahrez'] },
    { id: '72', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO J', local: 'JORDANIA', bandera_local: '🇯🇴', visitante: 'ARGENTINA', bandera_visitante: '🇦🇷', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '23:00', jugadores: ['Emiliano Martínez', 'Gerónimo Rulli', 'Juan Musso', 'Leonardo Balerdi', 'Nicolás Tagliafico', 'Gonzalo Montiel', 'Lisandro Martínez', 'Cristian Romero', 'Nicolás Otamendi', 'Facundo Medina', 'Nahuel Molina', 'Leandro Paredes', 'Rodrigo De Paul', 'Valentín Barco', 'Giovani Lo Celso', 'Exequiel Palacios', 'Alexis Mac Allister', 'Enzo Fernández', 'Julián Álvarez', 'Lionel Messi', 'Nico González', 'Thiago Almada', 'Giuliano Simeone', 'Nico Paz', 'José Manuel López', 'Lautaro Martínez',] },

    { id: '1001', etapa: '16avos', local: '2A', bandera_local: '🏳️', visitante: '2B', bandera_visitante: '🏳️', fecha: '28 de Junio', fecha_iso: '2026-06-28', hora: '16:00', jugadores: [] }, 
    { id: '1002', etapa: '16avos', local: '1C', bandera_local: '🏳️', visitante: '2F', bandera_visitante: '🏳️', fecha: '29 de Junio', fecha_iso: '2026-06-29', hora: '14:00', jugadores: [] },  
    { id: '1003', etapa: '16avos', local: '1E', bandera_local: '🏳️', visitante: '3ABCDF', bandera_visitante: '🏳️', fecha: '29 de Junio', fecha_iso: '2026-06-29', hora: '17:30', jugadores: [] },  
    { id: '1004', etapa: '16avos', local: '1F', bandera_local: '🏳️', visitante: '2C', bandera_visitante: '🏳️', fecha: '29 de Junio', fecha_iso: '2026-06-29', hora: '22:00', jugadores: [] },  
    { id: '1005', etapa: '16avos', local: '2E', bandera_local: '🏳️', visitante: '2I', bandera_visitante: '🏳️', fecha: '30 de Junio', fecha_iso: '2026-06-30', hora: '14:00', jugadores: [] },  
    { id: '1006', etapa: '16avos', local: '1I', bandera_local: '🏳️', visitante: '3CDFGH', bandera_visitante: '🏳️', fecha: '30 de Junio', fecha_iso: '2026-06-30', hora: '18:00', jugadores: [] },  
    { id: '1007', etapa: '16avos', local: '1A', bandera_local: '🏳️', visitante: '3CEFHI', bandera_visitante: '🏳️', fecha: '30 de Junio', fecha_iso: '2026-06-30', hora: '22:00', jugadores: [] },  
    { id: '1008', etapa: '16avos', local: '1L', bandera_local: '🏳️', visitante: '3EHIJK', bandera_visitante: '🏳️', fecha: '1 de Julio', fecha_iso: '2026-07-01', hora: '13:00', jugadores: [] },  
    { id: '1009', etapa: '16avos', local: '1G', bandera_local: '🏳️', visitante: '3AEHIJ', bandera_visitante: '🏳️', fecha: '1 de Julio', fecha_iso: '2026-07-01', hora: '17:00', jugadores: [] },  
    { id: '1010', etapa: '16avos', local: '1D', bandera_local: '🏳️', visitante: '3BEFIJ', bandera_visitante: '🏳️', fecha: '1 de Julio', fecha_iso: '2026-07-01', hora: '21:00', jugadores: [] },
    { id: '1011', etapa: '16avos', local: '1H', bandera_local: '🏳️', visitante: '2J', bandera_visitante: '🏳️', fecha: '2 de Julio', fecha_iso: '2026-07-02', hora: '16:00', jugadores: [] },  
    { id: '1012', etapa: '16avos', local: '2K', bandera_local: '🏳️', visitante: '2L', bandera_visitante: '🏳️', fecha: '2 de Julio', fecha_iso: '2026-07-02', hora: '20:00', jugadores: [] },  
    { id: '1013', etapa: '16avos', local: '1B', bandera_local: '🏳️', visitante: '3EFGIJ', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '0:00', jugadores: [] },  
    { id: '1014', etapa: '16avos', local: '2D', bandera_local: '🏳️', visitante: '2G', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '15:00', jugadores: [] },  
    { id: '1015', etapa: '16avos', local: '1J', bandera_local: '🏳️', visitante: '2H', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '19:00', jugadores: [] },  
    { id: '1016', etapa: '16avos', local: '1K', bandera_local: '🏳️', visitante: '3DEIJL', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '22:30', jugadores: [] },  

    { id: '2001', etapa: '8avos', local: '1001', bandera_local: '🏳️', visitante: '1002', bandera_visitante: '🏳️', fecha: '4 de Julio', fecha_iso: '2026-07-04', hora: '18:00', jugadores: [] },  
    { id: '2002', etapa: '8avos', local: '1003', bandera_local: '🏳️', visitante: '1004', bandera_visitante: '🏳️', fecha: '4 de Julio', fecha_iso: '2026-07-04', hora: '14:00', jugadores: [] },  
    { id: '2003', etapa: '8avos', local: '1005', bandera_local: '🏳️', visitante: '1006', bandera_visitante: '🏳️', fecha: '5 de Julio', fecha_iso: '2026-07-05', hora: '17:00', jugadores: [] },  
    { id: '2004', etapa: '8avos', local: '1007', bandera_local: '🏳️', visitante: '1008', bandera_visitante: '🏳️', fecha: '5 de Julio', fecha_iso: '2026-07-05', hora: '21:00', jugadores: [] },  
    { id: '2005', etapa: '8avos', local: '1009', bandera_local: '🏳️', visitante: '1010', bandera_visitante: '🏳️', fecha: '6 de Julio', fecha_iso: '2026-07-06', hora: '16:00', jugadores: [] },  
    { id: '2006', etapa: '8avos', local: '1011', bandera_local: '🏳️', visitante: '1012', bandera_visitante: '🏳️', fecha: '6 de Julio', fecha_iso: '2026-07-06', hora: '21:00', jugadores: [] },  
    { id: '2007', etapa: '8avos', local: '1013', bandera_local: '🏳️', visitante: '1014', bandera_visitante: '🏳️', fecha: '7 de Julio', fecha_iso: '2026-07-07', hora: '13:00', jugadores: [] },  
    { id: '2008', etapa: '8avos', local: '1015', bandera_local: '🏳️', visitante: '1016', bandera_visitante: '🏳️', fecha: '7 de Julio', fecha_iso: '2026-07-07', hora: '17:00', jugadores: [] },  

    { id: '3001', etapa: 'cuartos', local: '2001', bandera_local: '🏳️', visitante: '2002', bandera_visitante: '🏳️', fecha: '9 de Julio', fecha_iso: '2026-07-09', hora: '17:00', jugadores: [] },  
    { id: '3002', etapa: 'cuartos', local: '2003', bandera_local: '🏳️', visitante: '2004', bandera_visitante: '🏳️', fecha: '10 de Julio', fecha_iso: '2026-07-10', hora: '16:00', jugadores: [] },  
    { id: '3003', etapa: 'cuartos', local: '2005', bandera_local: '🏳️', visitante: '2006', bandera_visitante: '🏳️', fecha: '11 de Julio', fecha_iso: '2026-07-11', hora: '18:00', jugadores: [] },  
    { id: '3004', etapa: 'cuartos', local: '2007', bandera_local: '🏳️', visitante: '2008', bandera_visitante: '🏳️', fecha: '11 de Julio', fecha_iso: '2026-07-11', hora: '22:00', jugadores: [] },  

    { id: '4001', etapa: 'semis', local: '3001', bandera_local: '🏳️', visitante: '3002', bandera_visitante: '🏳️', fecha: '14 de Julio', fecha_iso: '2026-07-14', hora: '16:00', jugadores: [] },  
    { id: '4002', etapa: 'semis', local: '3003', bandera_local: '🏳️', visitante: '3004', bandera_visitante: '🏳️', fecha: '15 de Julio', fecha_iso: '2026-07-15', hora: '16:00', jugadores: [] },  

    { id: '5001', etapa: 'final', local: '4001', bandera_local: '🏳️', visitante: '4002', bandera_visitante: '🏳️', fecha: '19 de Julio', fecha_iso: '2026-07-19', hora: '16:00', jugadores: [] },  
    { id: '5002', etapa: 'final', local: '4001', bandera_local: '🏳️', visitante: '4002', bandera_visitante: '🏳️', fecha: '18 de Julio', fecha_iso: '2026-07-18', hora: '18:00', jugadores: [] },  
  ];

export default function AdminPanel() {
  const [loading, setLoading] = useState<string | null>(null);
  const [resultados, setResultados] = useState<any>({});

  // 1. Cargar datos existentes al entrar
  useEffect(() => {
    const cargarDatosExistentes = async () => {
      const { data, error } = await supabase.from('resultados_reales').select('*');
      if (data && !error) {
        const inicial: any = {};
        data.forEach(res => {
          inicial[res.partido_id] = {
            goles_local: res.goles_local_real?.toString() || '',
            goles_visitante: res.goles_visitante_real?.toString() || '',
            mvp: res.mvp_real || ''
          };
        });
        setResultados(inicial);
      }
    };
    cargarDatosExistentes();
  }, []);

  const handleChange = (partidoId: string, campo: string, valor: any) => {
    setResultados({
      ...resultados,
      [partidoId]: { 
        ...resultados[partidoId], 
        [campo]: valor 
      }
    });
  };

  const guardarResultadoOficial = async (partidoId: string) => {
    setLoading(partidoId);
    const res = resultados[partidoId];

    try {
      const { error } = await supabase
        .from('resultados_reales')
        .upsert({
          partido_id: partidoId,
          goles_local_real: parseInt(res?.goles_local) || 0,
          goles_visitante_real: parseInt(res?.goles_visitante) || 0,
          mvp_real: res?.mvp || ''
        }, { onConflict: 'partido_id' });

      if (error) throw error;
      alert("✅ Resultado oficial guardado. ¡Ranking actualizado!");
    } catch (err: any) {
      alert("Error: " + err.message);
    } finally {
      setLoading(null);
    }
  };

  return (
    <main className="min-h-screen p-8 bg-[#001D4A] text-white">
      <div className="max-w-4xl mx-auto">
        <div className="w-full flex justify-start mb-8">
          <Link href="/" className="text-[#F6C83E] font-bold uppercase text-[10px] tracking-widest hover:underline">
            ← Volver al inicio
          </Link>
        </div>
        
        <h1 className="text-4xl font-black my-8 text-[#F6C83E] italic uppercase tracking-tighter">Panel de Control</h1>
        <p className="mb-12 text-slate-400 font-medium">Cargá los resultados oficiales para actualizar el Prode.</p>

        <div className="space-y-6">
          {fixture.map((p) => (
            <div key={p.id} className="bg-[#002B71] p-6 rounded-3xl border border-[#003C9E] flex flex-col md:flex-row items-center gap-6">
              <div className="flex-1 font-bold">
                <span className="text-[#F6C83E] block text-[10px] mb-1 text-left uppercase tracking-widest">PARTIDO #{p.id}</span>
                <div className="text-left text-lg italic">{p.local} vs {p.visitante}</div>
              </div>

              <div className="flex gap-4 items-center">
                <input 
                  type="number" 
                  placeholder="L" 
                  value={resultados[p.id]?.goles_local ?? ''} 
                  className="w-14 h-14 bg-[#001D4A] border border-[#003C9E] rounded-xl text-center font-black text-xl text-[#F6C83E] outline-none focus:border-[#F6C83E]"
                  onChange={(e) => handleChange(p.id, 'goles_local', e.target.value)}
                />
                <span className="text-slate-500 font-black italic">VS</span>
                <input 
                  type="number" 
                  placeholder="V" 
                  value={resultados[p.id]?.goles_visitante ?? ''} 
                  className="w-14 h-14 bg-[#001D4A] border border-[#003C9E] rounded-xl text-center font-black text-xl text-[#F6C83E] outline-none focus:border-[#F6C83E]"
                  onChange={(e) => handleChange(p.id, 'goles_visitante', e.target.value)}
                />
              </div>

              <select 
                value={resultados[p.id]?.mvp ?? ''}
                className="bg-[#001D4A] border border-[#003C9E] p-3 rounded-xl text-sm font-bold flex-1 text-white outline-none focus:border-[#F6C83E]"
                onChange={(e) => handleChange(p.id, 'mvp', e.target.value)}
              >
                <option value="">MVP Oficial</option>
                {p.jugadores.map(j => (
                  <option key={j} value={j}>{j}</option>
                ))}
              </select>

              <button 
                onClick={() => guardarResultadoOficial(p.id)}
                disabled={loading === p.id}
                className="bg-[#F6C83E] text-[#001D4A] px-6 py-4 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:brightness-110 disabled:opacity-50 transition-all shadow-lg active:scale-95"
              >
                {loading === p.id ? "GUARDANDO..." : "CARGAR"}
              </button>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}