'use client';
import { supabase } from '@/lib/supabase';
import React, { useState, useEffect } from 'react';
import Link from 'next/link';

// Asegurate de que este fixture sea igual al de predicciones
const fixture = [
    { id: '1', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO A', local: 'MÉXICO', bandera_local: '🇲🇽', visitante: 'SUDÁFRICA', bandera_visitante: '🇿🇦', fecha: '11 de Junio', fecha_iso: '2026-06-11', hora: '16:00', jugadores: ['Guillermo Ochoa', 'Luis Malagón', 'Julio González', 'Edson Álvarez', 'César Montes', 'Johan Vásquez', 'Jorge Sánchez', 'Gerardo Arteaga', 'Israel Reyes', 'Jesús Orozco Chiquete', 'Luis Chávez', 'Orbelín Pineda', 'Erik Sánchez', 'Marcel Ruiz', 'Roberto Alvarado', 'Luis Romo', 'Santiago Giménez', 'Hirving Lozano', 'Julián Quiñones', 'Henry Martín', 'Alexis Vega', 'Uriel Antuna', 'Ronwen Williams', 'Khuliso Mudau', 'Aubrey Modiba', 'Mothobi Mvala', 'Grant Kekana', 'Teboho Mokoena', 'Sphephelo Sithole', 'Themba Zwane', 'Percy Tau', 'Evidence Makgopa', 'Thapelo Morena'] },
    { id: '2', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO A', local: 'COREA DEL SUR', bandera_local: '🇰🇷', visitante: 'REP. CHECA', bandera_visitante: '🇨🇿', fecha: '11 de Junio', fecha_iso: '2026-06-11', hora: '23:00', jugadores: ['Heung-min Son', 'Kim Min-jae', 'Lee Kang-in', 'Hwang Hee-chan', 'Cho Gue-sung', 'Hwang In-beom', 'Jo Hyeon-woo', 'Lee Jae-sung', 'Paik Seung-ho', 'Jeong Woo-yeong', 'Hong Hyun-seok', 'Oh Hyeon-gyu', 'Yang Min-hyeok', 'Seol Young-woo', 'Kim Jin-su', 'Kim Seung-gyu', 'Patrik Schick', 'Tomáš Souček', 'Vladimir Coufal', 'Adam Hložek', 'Antonín Barák', 'Ladislav Krejčí', 'Václav Cerny', 'David Zima', 'Robin Hranáč', 'David Jurásek', 'Lukáš Provod', 'Ondřej Lingr', 'Pavel Sulc', 'Jan Kuchta', 'Mojmír Chytil'] },
    { id: '3', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO B', local: 'CANADÁ', bandera_local: '🇨🇦', visitante: 'BOSNIA Y HERZEGOVINA', bandera_visitante: '🇧🇦', fecha: '12 de Junio', fecha_iso: '2026-06-12', hora: '16:00', jugadores: ['Alphonso Davies', 'Jonathan David', 'Stephen Eustáquio', 'Tajon Buchanan', 'Cyle Larin', 'Ismael Koné', 'Alistair Johnston', 'Milan Borjan', 'Jacob Shaffelburg',
          'Edin Džeko', 'Sead Kolašinac', 'Ermedin Demirovic', 'Amar Dedic', 'Benjamín Tahirovic', 'Nikola Vasilj', 'Martin Zlomislić', ' Osman Hadžikić', 'Nihad Mujakić', ' Nikola Katić', 'Tarik Muharemović', 'Stjepan Radeljić', ' Dennis Hadžikadunić', 'Nidal Čelik', 'Amir Hadžiahmetović', 'Ivan Šunjić', 'Ivan Bašić', 'Dženis Burnić', 'Ermin Mahmić', 'Amar Memić', 'Armin Gigović', 'Kerim Alajbegović', 'Esmir Bajraktarević', 'Jovo Lukić', 'Samed Baždar', 'Haris Tabaković'] },
    { id: '4', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO D', local: 'ESTADOS UNIDOS', bandera_local: '🇺🇸', visitante: 'PARAGUAY', bandera_visitante: '🇵🇾', fecha: '12 de Junio', fecha_iso: '2026-06-12', hora: '22:00', jugadores: ['Christian Pulisic', 'Weston McKennie', 'Timothy Weah', 'Folarin Balogun', 'Giovanni Reyna', 'Matt Turner', 'Antonee Robinson', 'Yunus Musah', 'Tyler Adams', 'Brenden Aaronson', 'Ricardo Pepi', 'Cameron Carter-Vickers', 'Miguel Almirón', 'Julio Enciso', 'Gustavo Gómez', 'Ramón Sosa', 'Mathías Villasanti', 'Adam Bareiro', 'Omar Alderete', 'Antonio Sanabria', 'Andrés Cubas', 'Junior Alonso', 'Santiago Arzamendia', 'Alejandro Romero Gamarra'] },
    { id: '5', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO B', local: 'CATAR', bandera_local: '🇶🇦', visitante: 'SUIZA', bandera_visitante: '🇨🇭', fecha: '13 de Junio', fecha_iso: '2026-06-13', hora: '16:00', jugadores: ['Akram Afif', 'Almoez Ali', 'Hassan Al-Haydos', 'Meshaal Barsham', 'Lucas Mendes', 'Mohammed Waad', 'Boualem Khoukhi', 'Abdulaziz Hatem', 'Jassim Gaber', 'Tarek Salman', 'Pedro Miguel', 'Homam Ahmed', 'Yusuf Abdurisag', 'Mohammed Muntari', 'Granit Xhaka', 'Xherdan Shaqiri', 'Yann Sommer', 'Manuel Akanji', 'Breel Embolo', 'Gregor Kobel', 'Fabian Schar', 'Remo Freuler', 'Ruben Vargas', 'Dan Ndoye', 'Zeki Amdouni', 'Michel Aebischer', 'Denis Zakaria', 'Silvan Widmer', 'Ricardo Rodríguez', 'Noah Okafor'] },
    { id: '6', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO C', local: 'BRASIL', bandera_local: '🇧🇷', visitante: 'MARRUECOS', bandera_visitante: '🇲🇦', fecha: '13 de Junio', fecha_iso: '2026-06-13', hora: '19:00', jugadores: ['Vinícius Júnior', 'Rodrygo Goes', 'Endrick Felipe', 'Neymar Júnior', 'Raphina Dias', 'Gabriel Martinelli', 'Savio Moreira', 'Pedro Guilherme', 'Lucas Paquetá', 'Bruno Guimaraes', 'Douglas Luiz', 'Joao Gomes', 'Andreas Pereira', 'Ederson dos Santos', 'Marquinos', 'Éder Militao', 'Gabriel Magalhaes', 'Danilo Luiz da Silva', 'Guilherme Arana', 'Lucas Beraldo', 'Yan Couto', 'Alisson Becker', 'Ederson Moraes', 'Bento Matheus Krepski', 'Achraf Hakimi', 'Brahim Díaz', 'Hakim Ziyech', 'Yassine Bounou', 'Sofyan Amrabat', 'Azzedine Ounahi', 'Nayef Aguerd', 'Romain Saiss', 'Youssef En-Nesyri', 'Amine Adli', 'Abde Exxalzouli', 'Soufiane Rahimi'] },
    { id: '7', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO C', local: 'HAITÍ', bandera_local: '🇭🇹', visitante: 'ESCOCIA', bandera_visitante: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', fecha: '13 de Junio', fecha_iso: '2026-06-13', hora: '22:00', jugadores: ['Duckens Nazon', 'Frantzdy Pierrot', 'Johny Placide', 'Carlens Arcus', 'Leverton Pierre', 'Ricardo Adé', 'Jean-Kévin Duverne', 'Mondy Prunier',
         'Garissone Innocent', 'Alez Christian', 'Andrew Robertson', 'Scott McTominay', 'John Mcginn', 'Billy Gilmour', 'Kieran Tierney', 'Angus Gunn', 'Jack Hendry', 'Ryan Porteous', 'Che Adams', 'Ryan Christie', 'Lawrence Shankland', 'Lewis Ferguson'] },
    { id: '8', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO D', local: 'AUSTRALIA', bandera_local: '🇦🇺', visitante: 'TURQUIA', bandera_visitante: '🇹🇷', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '1:00', jugadores: ['Mathew Ryan', 'Harry Souttar', 'Jackson Irvine', 'Craig Goodwin', 'Martin Boyle', 'Nestory Irankunda', 'Mitchell Duke', 'Aziz Behich', 'Connor Metcalfe', 'Alessandro Circati', 'Kusini Yengi', 'Arda Güler', 'Hakan Çalhanoğlu', 'Kenan Yıldız', 'Barış Alper Yılmaz', 'Ferdi Kadıoğlu', 'Mert Günok', 'Abdülkerim Bardakcı', 'Merih Demiral', 'Kerem Aktürkoğlu', 'Orkun Kökçü', 'Semih Kılıçsoy'] },
    { id: '9', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO E', local: 'ALEMANIA', bandera_local: '🇩🇪', visitante: 'CURAZAO', bandera_visitante: '🇨🇼', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '14:00', jugadores: ['Florian Wirtz', 'Jamal Musiala', 'Kai Havertz', 'Joshua Kimmich', 'Antonio Rüdiger', 'Marc-André ter Stegen', 'Niclas Füllkrug', 'Leroy Sané', 'Jonathan Tah', 'İlkay Gündoğan', 'Deniz Undav', 'Tahith Chong', 'Leandro Bacuna', 'Juninho Bacuna', 'Eloy Room', 'Armando Obispo', 'Riechedly Bazoer', 'Shurandy Sambo', 'Sherel Floranus', 'Jurien Gaari', 'Jurgen Locadia', 'Sontje Hansen', 'Livano Comenencia', 'Kenji Gorré'] },
    { id: '10', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO F', local: 'PAISES BAJOS', bandera_local: '🇳🇱', visitante: 'JAPÓN', bandera_visitante: '🇯🇵', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '17:00', jugadores: ['Virgil van Dijk', 'Cody Gakpo', 'Xavi Simons', 'Ryan Gravenberch', 'Micky van de Ven', 'Denzel Dumfries', 'Memphis Depay', 'Tijjani Reijnders', 'Bart Verbruggen', 'Nathan Aké', 'Jeremie Frimpong', 'Wout Weghorst',
         'Takefusa Kubo', 'Wataru Endo', 'Zion Suzuki', 'Ritsu Doan', 'Ayase Ueda', 'Hiroki Ito', 'Daichi Kamada', 'Yukinari Sugawara', 'Ao Tanaka', 'Ko Itakura', 'Daizen Maeda', 'Tomoki Hayakawa', 'Keisuke Osako', 'Yuto Nagatomo', 'Shogo Taniguchi', 'Tsuyoshi Watanabe', 'Takehiro Tomiyasu', 'Ayumu Seko', 'Junnosuke Suzuki', 'Junya Ito', 'Keito Nakamura', 'Kaishu Sano', 'Yuito Suzuki', 'Kento Shioggi', 'Koki Ogawa', 'Keisuke Goto'] },
    { id: '11', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO E', local: 'COSTA DE MARFIL', bandera_local: '🇨🇮', visitante: 'ECUADOR', bandera_visitante: '🇪🇨', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '20:00', jugadores: ['Moisés Caicedo', 'Kendry Páez', 'Piero Hincapié', 'Willian Pacho', 'Enner Valencia', 'Pervis Estupiñán', 'Gonzalo Plata', 'Hernán Galíndez', 'Kevin Rodríguez', 'Jeremy Sarmiento', 'Joel Ordóñez', 'Franck Kessié', 'Simon Adingra', 'Amad Diallo', 'Seko Fofana', 'Ibrahim Sangaré', 'Ousmane Diomande', 'Evan Ndicka', 'Elye Wahi', 'Yahia Fofana', 'Wilfried Singo', 'Nicolas Pépé', 'Evann Guessand'] },
    { id: '12', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO F', local: 'SUECIA', bandera_local: '🇸🇪', visitante: 'TÚNEZ', bandera_visitante: '🇹🇳', fecha: '14 de Junio', fecha_iso: '2026-06-14', hora: '23:00', jugadores: ['Viktor Gyökeres', 'Alexander Isak', 'Lucas Bergvall', 'Victor Lindelöf', 'Isak Hien', 'Anthony Elanga', 'Yasin Ayari', 'Daniel Svensson', 'Viktor Johansson', 'Kristoffer Nordfeldt', 'Jacob Widell Zetterström', 'Gabriel Gudmundsson', 'Emil Holm', 'Gustaf Lagerbielke', 'Eric Smith', 'Carl Starfelt', 'Elliot Stroud', 'Jesper Karlström', 'Mattias Svanberg', 'Besfort Zeneli', 'Ken Sema', 'Taha Ali', 'Alexander Bernhardsson', 'Gustaf Nilsson', 'Benjamin Nygren',
         'Hannibal Mejbri', 'Ellyes Skhiri', 'Elias Achouri', 'Ismaël Gharbi', 'Aïssa Laïdouni', 'Montassar Talbi', 'Aymen Dahmen', 'Elias Saad', 'Ali Abdi', 'Yan Valery', 'Anis Saidi', 'Rani Khedira'] },
    { id: '13', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO H', local: 'ESPAÑA', bandera_local: '🇪🇸', visitante: 'CABO VERDE', bandera_visitante: '🇨🇻', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '13:00', jugadores: ['Lamine Yamal', 'Rodri Hernández', 'Nico Williams', 'Pedri González', 'Dani Olmo', 'Unai Simón', 'Pau Cubarsí', 'Marc Cucurella', 'Dani Carvajal', 'Fabián Ruiz', 'Samu Aghehowa', 'Fermín López', 'Ryan Mendes', 'Logan Costa', 'Bebé', 'Vozinha', 'Garry Rodrigues', 'Kevin Pina', 'Jovane Cabral', 'Kenny Rocha Santos', 'Roberto Lopes', 'Jamiro Monteiro', 'Steven Moreira', 'Deroy Duarte'] },
    { id: '14', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO G', local: 'BÉLGICA', bandera_local: '🇧🇪', visitante: 'EGIPTO', bandera_visitante: '🇪🇬', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '16:00', jugadores: ['Kevin De Bruyne', 'Jérémy Doku', 'Romelu Lukaku', 'Leandro Trossard', 'Youri Tielemans', 'Thibaut Courtois', 'Amadou Onana', 'Arthur Theate', 'Charles De Ketelaere', 'Timothy Castagne', 'Zeno Debast', 'Senne Lammens', 'Mike Penders', 'Maxim De Cuyper', 'Koni De Winter', 'Brandon Mechele', 'Thomas Meunier', 'Nathan Nhoy', 'Joaquin Seys', 'Nicolas Raskin', 'Hans Vanaken', 'Axel Witsel', 'Matías Fernandez-Pardo', 'Dodi Lukebakio', 'Diego Moreira', 'Alexis Saelemaekers', 
          'Mohamed Salah', 'Omar Marmoush', 'Mostafa Mohamed', 'Trézéguet', 'Mohamed Abdelmonem', 'Mohamed El Shenawy', 'Emam Ashour', 'Zizo', 'Marwan Ateya', 'Hossam Abdelmaguid', 'Mohamed Hany', 'Ahmed Fatouh'] },
    { id: '15', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO H', local: 'ARABIA SAUDITA', bandera_local: '🇸🇦', visitante: 'URUGUAY', bandera_visitante: '🇺🇾', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '19:00', jugadores: ['Federico Valverde', 'Darwin Núñez', 'Nicolás de la Cruz', 'Ronald Araújo', 'Sergio Rochet', 'Giorgian de Arrascaeta', 'Manuel Ugarte', 'José María Giménez', 'Facundo Pellistri', 'Maximiliano Araújo', 'Matías Viña', 'Santiago Mele', 'Salem Al-Dawsari', 'Firas Al-Buraikan', 'Mohammed Al-Owais', 'Saud Abdulhamid', 'Mohamed Kanno', 'Ali Al-Bulayhi', 'Faisal Al-Ghamdi', 'Abdulelah Al-Malki', 'Hassan Tambakti', 'Nasser Al-Dawsari', 'Ali Lajami', 'Saleh Al-Shehri'] },
    { id: '16', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO G', local: 'IRÁN', bandera_local: '🇮🇷', visitante: 'NUEVA ZELANDA', bandera_visitante: '🇳🇿', fecha: '15 de Junio', fecha_iso: '2026-06-15', hora: '22:00', jugadores: ['Chris Wood', 'Liburato Cacace', 'Joe Bell', 'Michael Boxall', 'Sarpreet Singh', 'Tyler Bindon', 'Ben Waine', 'Kosta Barbarouses', 'Max Crocombe', 'Alex Paulsen', 'Michael Woud', 'Callan Elliot', 'Tim Payne', 'Nando Pijnaker', 'Tommy Smith', 'Finn Surman', 'Francis de Vries', 'Lachlan Bayliss', 'Matt Garbett', 'Elijah Just', 'Ben Old', 'Alex Rufer', 'Marko Stamenić', 'Ryan Thomas', 'Callum McCowatt', 'Jesse Randall',
         'Mehdi Taremi', 'Sardar Azmoun', 'Alireza Beiranvand', 'Alireza Jahanbakhsh', 'Saman Ghoddos', 'Mehdi Ghayedi', 'Saeid Ezatolahi', 'Shojae Khalilzadeh', 'Milad Mohammadi', 'Mehdi Torabi', 'Hossein Kanaani', 'Ramin Rezaeian'] },
    { id: '17', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO I', local: 'FRANCIA', bandera_local: '🇫🇷', visitante: 'SENEGAL', bandera_visitante: '🇸🇳', fecha: '16 de Junio', fecha_iso: '2026-06-16', hora: '16:00', jugadores: ['Kylian Mbappé', 'Michael Olise', 'Mike Maignan', 'William Saliba', 'Aurélien Tchouaméni', 'Ousmane Dembélé', 'Theo Hernández', 'Bradley Barcola', 'Warren Zaïre-Emery', 'Marcus Thuram', 'Robin Risser', 'Brice Samba', 'Lucas Digne', 'Malo Gusto', 'Lucas Hernandez', 'Ibrahima Konate', 'Jules Kounde', 'Maxence Lacroix', 'Dayot Upamecano', 'NGolo Kante', 'Manu Kone', 'Adrien Rabiot', 'Maghnes Akliouche', 'Rayan Cherki', 'Desire Doue', 'Jean-Philippe Mateta',
         'Edouard Mendy', 'Ismaïla Sarr', 'Pape Matar Sarr', 'Lamine Camara', 'Idrissa Gana Gueye', 'Abdou Diallo', 'Iliman Ndiaye', 'Moussa Niakhaté', 'Boulaye Dia'] },
    { id: '18', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO I', local: 'IRAK', bandera_local: '🇮🇶', visitante: 'NORUEGA', bandera_visitante: '🇳🇴', fecha: '16 de Junio', fecha_iso: '2026-06-16', hora: '19:00', jugadores: ['Aymen Hussein', 'Ali Jasim', 'Zidane Iqbal', 'Ali Al-Hamadi', 'Ibrahim Bayesh', 'Amir Al-Ammari', 'Youssef Amyn', 'Mohanad Ali', 'Rebin Sulaka', 'Merchas Doski', 'Ahmed Basil', 'Manaf Younis', 'Erling Haaland', 'Martin Ødegaard', 'Alexander Sørloth', 'Antonio Nusa', 'Julian Ryerson', 'Sander Berge', 'Oscar Bobb', 'Kristoffer Ajer', 'Ørjan Nyland', 'Leo Østigård', 'David Møller Wolfe', 'Jørgen Strand Larsen'] },
    { id: '19', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO J', local: 'ARGENTINA', bandera_local: '🇦🇷', visitante: 'ARGELIA', bandera_visitante: '🇩🇿', fecha: '16 de Junio', fecha_iso: '2026-06-16', hora: '22:00', jugadores: ['Lionel Messi', 'Emiliano Martínez', 'Julián Álvarez', 'Lautaro Martínez', 'Rodrigo De Paul', 'Alexis Mac Allister', 'Enzo Fernández', 'Cristian Romero', 'Alejandro Garnacho', 'Leandro Paredes', 'Nico Paz', 'Franco Mastantuono', 'Nicolás Otamendi', 'Riyad Mahrez', 'Mohamed Amoura', 'Ismaël Bennacer', 'Said Benrahma', 'Rayan Aït-Nouri', 'Houssem Aouar', 'Ramy Bensebaini', 'Anthony Mandrea', 'Ramiz Zerrouki', 'Aïssa Mandi', 'Farès Chaïbi', 'Youcef Atal'] },
    { id: '20', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO J', local: 'AUSTRIA', bandera_local: '🇦🇹', visitante: 'JORDANIA', bandera_visitante: '🇯🇴', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '1:00', jugadores: ['Marcel Sabitzer', 'Konrad Laimer', 'David Alaba', 'Christoph Baumgartner', 'Kevin Danso', 'Michael Gregoritsch', 'Stefan Posch', 'Patrick Pentz', 'Patrick Wimmer', 'Nicolas Seiwald', 'Romano Schmid', 'Philipp Lienhart', 'Musa Al-Taamari', 'Yazan Al-Naimat', 'Yazeed Abulaila', 'Mahmoud Al-Mardi', 'Yazan Al-Arab', 'Nizar Al-Rashdan', 'Noor Al-Rawabdeh', 'Ehsan Haddad', 'Abdallah Nasib', 'Salem Al-Ajalin', 'Ali Olwan', 'Ibrahim Sadeh'] },
    { id: '21', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO K', local: 'PORTUGAL', bandera_local: '🇵🇹', visitante: 'RD CONGO', bandera_visitante: '🇨🇩', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '14:00', jugadores: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva', 'Rafael Leão', 'Rúben Dias', 'Diogo Costa', 'João Félix', 'Vitinha', 'João Palhinha', 'Nuno Mendes', 'João Neves', 'Gonçalo Ramos', 'Yoane Wissa', 'Theo Bongonda', 'Chancel Mbemba', 'Samuel Moutoussamy', 'Simon Banza', 'Meschack Elia', 'Dimitry Bertaud', 'Arthur Masuaku', 'Charles Pickel', 'Dylan Batubinsika', 'Gédéon Kalulu', 'Gaël Kakuta'] },
    { id: '22', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO L', local: 'INGLATERRA', bandera_local: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', visitante: 'CROACIA', bandera_visitante: '🇭🇷', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '17:00', jugadores: ['Harry Kane', 'Jude Bellingham', 'Cole Palmer', 'Phil Foden', 'Bukayo Saka', 'Declan Rice', 'Jordan Pickford', 'John Stones', 'Reece James', 'Marcus Rashford', 'Kobbie Mainoo', 'Marc Guéhi', 'Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić', 'Dominik Livaković', 'Martin Baturina', 'Marcelo Brozović', 'Andrej Kramarić', 'Josip Šutalo', 'Lovro Majer', 'Borna Sosa', 'Josip Stanišić', 'Mario Pašalić'] },
    { id: '23', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO L', local: 'GHANA', bandera_local: '🇬🇭', visitante: 'PANAMÁ', bandera_visitante: '🇵🇦', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '20:00', jugadores: ['Mohammed Kudus', 'Antoine Semenyo', 'Iñaki Williams', 'Thomas Partey', 'Jordan Ayew', 'Kamaldeen Sulemana', 'Lawrence Ati-Zigi', 'Alexander Djiku', 'Abdul Fatawu', 'Gideon Mensah', 'Mohammed Salisu', 'Brandon Thomas-Asante', 'Adalberto Carrasquilla', 'Michael Amir Murillo', 'Ismael Díaz', 'Orlando Mosquera', 'José Córdoba', 'Aníbal Godoy', 'Andrés Andrade', 'Fidel Escobar', 'José Fajardo', 'Éric Davis', 'José Luis Rodríguez', 'Kahiser Lenis'] },
    { id: '24', etapa: 'grupos', fase_nro: 1, grupo: 'GRUPO K', local: 'UZBEKISTÁN', bandera_local: '🇺🇿', visitante: 'COLOMBIA', bandera_visitante: '🇨🇴', fecha: '17 de Junio', fecha_iso: '2026-06-17', hora: '23:00', jugadores: ['Luis Díaz', 'James Rodríguez', 'Richard Ríos', 'Jhon Durán', 'Jhon Arias', 'Rafael Santos Borré', 'Daniel Muñoz', 'Davinson Sánchez', 'Camilo Vargas', 'Luis Sinisterra', 'Álvaro Montero', 'Eldor Shomurodov', 'Abbosbek Fayzullaev', 'Abdukodir Khusanov', 'Jaloliddin Masharipov', 'Utkir Yusupov', 'Oston Urunov', 'Otabek Shukurov', 'Rustam Ashurmatov', 'Odiljon Hamrobekov', 'Husniddin Aliqulov', 'Farrukh Sayfiev', 'Azizbek Turgunboev'] },
    

    { id: '25', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO A', local: 'REP CHECA', bandera_local: '🇨🇿', visitante: 'SUDÁFRICA', bandera_visitante: '🇿🇦', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '13:00', jugadores: ['Ronwen Williams', 'Khuliso Mudau', 'Aubrey Modiba', 'Mothobi Mvala', 'Grant Kekana', 'Teboho Mokoena', 'Sphephelo Sithole', 'Themba Zwane', 'Percy Tau', 'Evidence Makgopa', 'Thapelo Morena', 'Patrik Schick', 'Tomáš Souček', 'Vladimir Coufal', 'Adam Hložek', 'Antonín Barák', 'Ladislav Krejčí', 'Václav Cerny', 'David Zima', 'Robin Hranáč', 'David Jurásek', 'Lukáš Provod', 'Ondřej Lingr', 'Pavel Sulc', 'Jan Kuchta', 'Mojmír Chytil'] },
    { id: '26', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO B', local: 'SUIZA', bandera_local: '🇨🇭', visitante: 'BOSNIA Y HERZEGOVINA', bandera_visitante: '🇧🇦', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '16:00', jugadores: ['Edin Džeko', 'Sead Kolašinac', 'Ermedin Demirovic', 'Amar Dedic', 'Benjamín Tahirovic', 'Nikola Vasilj', 'Martin Zlomislić', ' Osman Hadžikić', 'Nihad Mujakić', ' Nikola Katić', 'Tarik Muharemović', 'Stjepan Radeljić', ' Dennis Hadžikadunić', 'Nidal Čelik', 'Amir Hadžiahmetović', 'Ivan Šunjić', 'Ivan Bašić', 'Dženis Burnić', 'Ermin Mahmić', 'Amar Memić', 'Armin Gigović', 'Kerim Alajbegović', 'Esmir Bajraktarević', 'Jovo Lukić', 'Samed Baždar', 'Haris Tabaković',
         'Granit Xhaka', 'Xherdan Shaqiri', 'Yann Sommer', 'Manuel Akanji', 'Breel Embolo', 'Gregor Kobel', 'Fabian Schar', 'Remo Freuler', 'Ruben Vargas', 'Dan Ndoye', 'Zeki Amdouni', 'Michel Aebischer', 'Denis Zakaria', 'Silvan Widmer', 'Ricardo Rodríguez', 'Noah Okafor'] },
    { id: '27', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO B', local: 'CANADÁ', bandera_local: '🇨🇦', visitante: 'CATAR', bandera_visitante: '🇶🇦', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '19:00', jugadores: ['Alphonso Davies', 'Jonathan David', 'Stephen Eustáquio', 'Tajon Buchanan', 'Cyle Larin', 'Ismael Koné', 'Alistair Johnston', 'Milan Borjan', 'Jacob Shaffelburg', 'Akram Afif', 'Almoez Ali', 'Hassan Al-Haydos', 'Meshaal Barsham', 'Lucas Mendes', 'Mohammed Waad', 'Boualem Khoukhi', 'Abdulaziz Hatem', 'Jassim Gaber', 'Tarek Salman', 'Pedro Miguel', 'Homam Ahmed', 'Yusuf Abdurisag', 'Mohammed Muntari'] },
    { id: '28', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO A', local: 'COREA DEL SUR', bandera_local: '🇰🇷', visitante: 'MÉXICO', bandera_visitante: '🇲🇽', fecha: '18 de Junio', fecha_iso: '2026-06-18', hora: '22:00', jugadores: ['Guillermo Ochoa', 'Luis Malagón', 'Julio González', 'Edson Álvarez', 'César Montes', 'Johan Vásquez', 'Jorge Sánchez', 'Gerardo Arteaga', 'Israel Reyes', 'Jesús Orozco Chiquete', 'Luis Chávez', 'Orbelín Pineda', 'Erik Sánchez', 'Marcel Ruiz', 'Roberto Alvarado', 'Luis Romo', 'Santiago Giménez', 'Hirving Lozano', 'Julián Quiñones', 'Henry Martín', 'Alexis Vega', 'Uriel Antuna', 'Heung-min Son', 'Kim Min-jae', 'Lee Kang-in', 'Hwang Hee-chan', 'Cho Gue-sung', 'Hwang In-beom', 'Jo Hyeon-woo', 'Lee Jae-sung', 'Paik Seung-ho', 'Jeong Woo-yeong', 'Hong Hyun-seok', 'Oh Hyeon-gyu', 'Yang Min-hyeok', 'Seol Young-woo', 'Kim Jin-su', 'Kim Seung-gyu'] },
    { id: '29', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO D', local: 'ESTADOS UNIDOS', bandera_local: '🇺🇸', visitante: 'AUSTRALIA', bandera_visitante: '🇦🇺', fecha: '19 de Junio', fecha_iso: '2026-06-19', hora: '16:00', jugadores: ['Christian Pulisic', 'Weston McKennie', 'Timothy Weah', 'Folarin Balogun', 'Giovanni Reyna', 'Matt Turner', 'Antonee Robinson', 'Yunus Musah', 'Tyler Adams', 'Brenden Aaronson', 'Ricardo Pepi', 'Cameron Carter-Vickers', 'Mathew Ryan', 'Harry Souttar', 'Jackson Irvine', 'Craig Goodwin', 'Martin Boyle', 'Nestory Irankunda', 'Mitchell Duke', 'Aziz Behich', 'Connor Metcalfe', 'Alessandro Circati', 'Kusini Yengi'] },
    { id: '30', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO C', local: 'ESCOCIA', bandera_local: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', visitante: 'MARRUECOS', bandera_visitante: '🇲🇦', fecha: '19 de Junio', fecha_iso: '2026-06-19', hora: '19:00', jugadores: ['Achraf Hakimi', 'Brahim Díaz', 'Hakim Ziyech', 'Yassine Bounou', 'Sofyan Amrabat', 'Azzedine Ounahi', 'Nayef Aguerd', 'Romain Saiss', 'Youssef En-Nesyri', 'Amine Adli', 'Abde Exxalzouli', 'Soufiane Rahimi', 'Andrew Robertson', 'Scott McTominay', 'John Mcginn', 'Billy Gilmour', 'Kieran Tierney', 'Angus Gunn', 'Jack Hendry', 'Ryan Porteous', 'Che Adams', 'Ryan Christie', 'Lawrence Shankland', 'Lewis Ferguson'] },
    { id: '31', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO C', local: 'BRASIL', bandera_local: '🇧🇷', visitante: 'HAITÍ', bandera_visitante: '🇭🇹', fecha: '19 de Junio', fecha_iso: '2026-06-19', hora: '21:30', jugadores: ['Vinícius Júnior', 'Rodrygo Goes', 'Endrick Felipe', 'Neymar Júnior', 'Raphina Dias', 'Gabriel Martinelli', 'Savio Moreira', 'Pedro Guilherme', 'Lucas Paquetá', 'Bruno Guimaraes', 'Douglas Luiz', 'Joao Gomes', 'Andreas Pereira', 'Ederson dos Santos', 'Marquinos', 'Éder Militao', 'Gabriel Magalhaes', 'Danilo Luiz da Silva', 'Guilherme Arana', 'Lucas Beraldo', 'Yan Couto', 'Alisson Becker', 'Ederson Moraes', 'Bento Matheus Krepski', 'Duckens Nazon', 'Frantzdy Pierrot', 'Dany Jean', 'Johny Placide', 'Carlens Arcus', 'Leverton Pierre', 'Danley Jean Jacques', 'Ricardo Adé', 'Jean-Kévin Duverne', 'Mondy Prunier', 'Garissone Innocent', 'Alez Christian'] },
    { id: '32', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO D', local: 'TURQUÍA', bandera_local: '🇹🇷', visitante: 'PARAGUAY', bandera_visitante: '🇵🇾', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '0:00', jugadores: ['Miguel Almirón', 'Julio Enciso', 'Gustavo Gómez', 'Ramón Sosa', 'Mathías Villasanti', 'Adam Bareiro', 'Omar Alderete', 'Antonio Sanabria', 'Andrés Cubas', 'Junior Alonso', 'Santiago Arzamendia', 'Alejandro Romero Gamarra', 'Arda Güler', 'Hakan Çalhanoğlu', 'Kenan Yıldız', 'Barış Alper Yılmaz', 'Ferdi Kadıoğlu', 'Mert Günok', 'Abdülkerim Bardakcı', 'Merih Demiral', 'Kerem Aktürkoğlu', 'Orkun Kökçü', 'Semih Kılıçsoy'] },
    { id: '33', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO F', local: 'PAISES BAJOS', bandera_local: '🇳🇱', visitante: 'SUECIA', bandera_visitante: '🇸🇪', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '14:00', jugadores: ['Virgil van Dijk', 'Cody Gakpo', 'Xavi Simons', 'Ryan Gravenberch', 'Micky van de Ven', 'Denzel Dumfries', 'Memphis Depay', 'Tijjani Reijnders', 'Bart Verbruggen', 'Nathan Aké', 'Jeremie Frimpong', 'Wout Weghorst',
         'Viktor Gyökeres', 'Alexander Isak', 'Lucas Bergvall', 'Victor Lindelöf', 'Isak Hien', 'Anthony Elanga', 'Yasin Ayari', 'Daniel Svensson', 'Viktor Johansson', 'Kristoffer Nordfeldt', 'Jacob Widell Zetterström', 'Gabriel Gudmundsson', 'Emil Holm', 'Gustaf Lagerbielke', 'Eric Smith', 'Carl Starfelt', 'Elliot Stroud', 'Jesper Karlström', 'Mattias Svanberg', 'Besfort Zeneli', 'Ken Sema', 'Taha Ali', 'Alexander Bernhardsson', 'Gustaf Nilsson', 'Benjamin Nygren'] },
    { id: '34', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO E', local: 'ALEMANIA', bandera_local: '🇩🇪', visitante: 'COSTA DE MARFIL', bandera_visitante: '🇨🇮', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '17:00', jugadores: ['Florian Wirtz', 'Jamal Musiala', 'Kai Havertz', 'Joshua Kimmich', 'Antonio Rüdiger', 'Marc-André ter Stegen', 'Niclas Füllkrug', 'Leroy Sané', 'Jonathan Tah', 'İlkay Gündoğan', 'Deniz Undav', 'Franck Kessié', 'Simon Adingra', 'Amad Diallo', 'Seko Fofana', 'Ibrahim Sangaré', 'Ousmane Diomande', 'Evan Ndicka', 'Elye Wahi', 'Yahia Fofana', 'Wilfried Singo', 'Nicolas Pépé', 'Evann Guessand'] },
    { id: '35', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO E', local: 'ECUADOR', bandera_local: '🇪🇨', visitante: 'CURAZAO', bandera_visitante: '🇨🇼', fecha: '20 de Junio', fecha_iso: '2026-06-20', hora: '21:00', jugadores: ['Tahith Chong', 'Leandro Bacuna', 'Juninho Bacuna', 'Eloy Room', 'Armando Obispo', 'Riechedly Bazoer', 'Shurandy Sambo', 'Sherel Floranus', 'Jurien Gaari', 'Jurgen Locadia', 'Sontje Hansen', 'Livano Comenencia', 'Kenji Gorré', 'Moisés Caicedo', 'Kendry Páez', 'Piero Hincapié', 'Willian Pacho', 'Enner Valencia', 'Pervis Estupiñán', 'Gonzalo Plata', 'Hernán Galíndez', 'Kevin Rodríguez', 'Jeremy Sarmiento', 'Joel Ordóñez'] },
    { id: '36', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO F', local: 'TÚNEZ', bandera_local: '🇹🇳', visitante: 'JAPÓN', bandera_visitante: '🇯🇵', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '1:00', jugadores: ['Takefusa Kubo', 'Wataru Endo', 'Zion Suzuki', 'Ritsu Doan', 'Ayase Ueda', 'Hiroki Ito', 'Daichi Kamada', 'Yukinari Sugawara', 'Ao Tanaka', 'Ko Itakura', 'Daizen Maeda', 'Tomoki Hayakawa', 'Keisuke Osako', 'Yuto Nagatomo', 'Shogo Taniguchi', 'Tsuyoshi Watanabe', 'Takehiro Tomiyasu', 'Ayumu Seko', 'Junnosuke Suzuki', 'Junya Ito', 'Keito Nakamura', 'Kaishu Sano', 'Yuito Suzuki', 'Kento Shioggi', 'Koki Ogawa', 'Keisuke Goto',
          'Hannibal Mejbri', 'Ellyes Skhiri', 'Elias Achouri', 'Ismaël Gharbi', 'Aïssa Laïdouni', 'Montassar Talbi', 'Aymen Dahmen', 'Elias Saad', 'Ali Abdi', 'Yan Valery', 'Anis Saidi', 'Rani Khedira'] },
    { id: '37', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO H', local: 'ESPAÑA', bandera_local: '🇪🇸', visitante: 'ARABIA SAUDITA', bandera_visitante: '🇸🇦', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '13:00', jugadores: ['Lamine Yamal', 'Rodri Hernández', 'Nico Williams', 'Pedri González', 'Dani Olmo', 'Unai Simón', 'Pau Cubarsí', 'Marc Cucurella', 'Dani Carvajal', 'Fabián Ruiz', 'Samu Aghehowa', 'Fermín López', 'Salem Al-Dawsari', 'Firas Al-Buraikan', 'Mohammed Al-Owais', 'Saud Abdulhamid', 'Mohamed Kanno', 'Ali Al-Bulayhi', 'Faisal Al-Ghamdi', 'Abdulelah Al-Malki', 'Hassan Tambakti', 'Nasser Al-Dawsari', 'Ali Lajami', 'Saleh Al-Shehri'] },
    { id: '38', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO G', local: 'BÉLGICA', bandera_local: '🇧🇪', visitante: 'IRÁN', bandera_visitante: '🇮🇷', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '16:00', jugadores: ['Kevin De Bruyne', 'Jérémy Doku', 'Romelu Lukaku', 'Leandro Trossard', 'Youri Tielemans', 'Thibaut Courtois', 'Amadou Onana', 'Arthur Theate', 'Charles De Ketelaere', 'Timothy Castagne', 'Zeno Debast', 'Senne Lammens', 'Mike Penders', 'Maxim De Cuyper', 'Koni De Winter', 'Brandon Mechele', 'Thomas Meunier', 'Nathan Nhoy', 'Joaquin Seys', 'Nicolas Raskin', 'Hans Vanaken', 'Axel Witsel', 'Matías Fernandez-Pardo', 'Dodi Lukebakio', 'Diego Moreira', 'Alexis Saelemaekers', 
         'Mehdi Taremi', 'Sardar Azmoun', 'Alireza Beiranvand', 'Alireza Jahanbakhsh', 'Saman Ghoddos', 'Mehdi Ghayedi', 'Saeid Ezatolahi', 'Shojae Khalilzadeh', 'Milad Mohammadi', 'Mehdi Torabi', 'Hossein Kanaani', 'Ramin Rezaeian'] },
    { id: '39', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO H', local: 'URUGUAY', bandera_local: '🇺🇾', visitante: 'CABO VERDE', bandera_visitante: '🇨🇻', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '19:00', jugadores: ['Federico Valverde', 'Darwin Núñez', 'Nicolás de la Cruz', 'Ronald Araújo', 'Sergio Rochet', 'Giorgian de Arrascaeta', 'Manuel Ugarte', 'José María Giménez', 'Facundo Pellistri', 'Maximiliano Araújo', 'Matías Viña', 'Santiago Mele', 'Ryan Mendes', 'Logan Costa', 'Bebé', 'Vozinha', 'Garry Rodrigues', 'Kevin Pina', 'Jovane Cabral', 'Kenny Rocha Santos', 'Roberto Lopes', 'Jamiro Monteiro', 'Steven Moreira', 'Deroy Duarte'] },
    { id: '40', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO G', local: 'NUEVA ZELANDA', bandera_local: '🇳🇿', visitante: 'EGIPTO', bandera_visitante: '🇪🇬', fecha: '21 de Junio', fecha_iso: '2026-06-21', hora: '22:00', jugadores: ['Mohamed Salah', 'Omar Marmoush', 'Mostafa Mohamed', 'Trézéguet', 'Mohamed Abdelmonem', 'Mohamed El Shenawy', 'Emam Ashour', 'Zizo', 'Marwan Ateya', 'Hossam Abdelmaguid', 'Mohamed Hany', 'Ahmed Fatouh',
       'Chris Wood', 'Liburato Cacace', 'Joe Bell', 'Michael Boxall', 'Sarpreet Singh', 'Tyler Bindon', 'Ben Waine', 'Kosta Barbarouses', 'Max Crocombe', 'Alex Paulsen', 'Michael Woud', 'Callan Elliot', 'Tim Payne', 'Nando Pijnaker', 'Tommy Smith', 'Finn Surman', 'Francis de Vries', 'Lachlan Bayliss', 'Matt Garbett', 'Elijah Just', 'Ben Old', 'Alex Rufer', 'Marko Stamenić', 'Ryan Thomas', 'Callum McCowatt', 'Jesse Randall'] },
    { id: '41', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO J', local: 'ARGENTINA', bandera_local: '🇦🇷', visitante: 'AUSTRIA', bandera_visitante: '🇦🇹', fecha: '22 de Junio', fecha_iso: '2026-06-22', hora: '14:00', jugadores: ['Lionel Messi', 'Emiliano Martínez', 'Julián Álvarez', 'Lautaro Martínez', 'Rodrigo De Paul', 'Alexis Mac Allister', 'Enzo Fernández', 'Cristian Romero', 'Alejandro Garnacho', 'Leandro Paredes', 'Nico Paz', 'Franco Mastantuono', 'Nicolás Otamendi', 'Marcel Sabitzer', 'Konrad Laimer', 'David Alaba', 'Christoph Baumgartner', 'Kevin Danso', 'Michael Gregoritsch', 'Stefan Posch', 'Patrick Pentz', 'Patrick Wimmer', 'Nicolas Seiwald', 'Romano Schmid', 'Philipp Lienhart'] },
    { id: '42', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO I', local: 'FRANCIA', bandera_local: '🇫🇷', visitante: 'IRAK', bandera_visitante: '🇮🇶', fecha: '22 de Junio', fecha_iso: '2026-06-22', hora: '18:00', jugadores: ['Kylian Mbappé', 'Michael Olise', 'Mike Maignan', 'William Saliba', 'Aurélien Tchouaméni', 'Ousmane Dembélé', 'Theo Hernández', 'Bradley Barcola', 'Warren Zaïre-Emery', 'Marcus Thuram', 'Robin Risser', 'Brice Samba', 'Lucas Digne', 'Malo Gusto', 'Lucas Hernandez', 'Ibrahima Konate', 'Jules Kounde', 'Maxence Lacroix', 'Dayot Upamecano', 'NGolo Kante', 'Manu Kone', 'Adrien Rabiot', 'Maghnes Akliouche', 'Rayan Cherki', 'Desire Doue', 'Jean-Philippe Mateta',
         'Aymen Hussein', 'Ali Jasim', 'Zidane Iqbal', 'Ali Al-Hamadi', 'Ibrahim Bayesh', 'Amir Al-Ammari', 'Youssef Amyn', 'Mohanad Ali', 'Rebin Sulaka', 'Merchas Doski', 'Ahmed Basil', 'Manaf Younis'] },
    { id: '43', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO I', local: 'NORUEGA', bandera_local: '🇦🇷', visitante: 'SENEGAL', bandera_visitante: '🇸🇳', fecha: '22', fecha_iso: '2026-06-22', hora: '21:00', jugadores: ['Lionel Messi', 'Julián Álvarez', 'Riyad Mahrez', 'Sadio Mané', 'Nicolas Jackson', 'Kalidou Koulibaly', 'Edouard Mendy', 'Ismaïla Sarr', 'Pape Matar Sarr', 'Lamine Camara', 'Idrissa Gana Gueye', 'Abdou Diallo', 'Iliman Ndiaye', 'Moussa Niakhaté', 'Boulaye Dia', 'Erling Haaland', 'Martin Ødegaard', 'Alexander Sørloth', 'Antonio Nusa', 'Julian Ryerson', 'Sander Berge', 'Oscar Bobb', 'Kristoffer Ajer', 'Ørjan Nyland', 'Leo Østigård', 'David Møller Wolfe', 'Jørgen Strand Larsen'] },
    { id: '44', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO J', local: 'JORDANIA', bandera_local: '🇯🇴', visitante: 'ARGELIA', bandera_visitante: '🇩🇿', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '0:00', jugadores: ['Musa Al-Taamari', 'Yazan Al-Naimat', 'Yazeed Abulaila', 'Mahmoud Al-Mardi', 'Yazan Al-Arab', 'Nizar Al-Rashdan', 'Noor Al-Rawabdeh', 'Ehsan Haddad', 'Abdallah Nasib', 'Salem Al-Ajalin', 'Ali Olwan', 'Ibrahim Sadeh', 'Riyad Mahrez', 'Mohamed Amoura', 'Ismaël Bennacer', 'Said Benrahma', 'Rayan Aït-Nouri', 'Houssem Aouar', 'Ramy Bensebaini', 'Anthony Mandrea', 'Ramiz Zerrouki', 'Aïssa Mandi', 'Farès Chaïbi', 'Youcef Atal'] },
    { id: '45', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO K', local: 'PORTUGAL', bandera_local: '🇵🇹', visitante: 'UZBEKISTÁN', bandera_visitante: '🇺🇿', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '14:00', jugadores: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva', 'Rafael Leão', 'Rúben Dias', 'Diogo Costa', 'João Félix', 'Vitinha', 'João Palhinha', 'Nuno Mendes', 'João Neves', 'Gonçalo Ramos', 'Eldor Shomurodov', 'Abbosbek Fayzullaev', 'Abdukodir Khusanov', 'Jaloliddin Masharipov', 'Utkir Yusupov', 'Oston Urunov', 'Otabek Shukurov', 'Rustam Ashurmatov', 'Odiljon Hamrobekov', 'Husniddin Aliqulov', 'Farrukh Sayfiev', 'Azizbek Turgunboev'] },
    { id: '46', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO L', local: 'INGLATERRA', bandera_local: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', visitante: 'GHANA', bandera_visitante: '🇬🇭', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '17:00', jugadores: ['Harry Kane', 'Jude Bellingham', 'Cole Palmer', 'Phil Foden', 'Bukayo Saka', 'Declan Rice', 'Jordan Pickford', 'John Stones', 'Reece James', 'Marcus Rashford', 'Kobbie Mainoo', 'Marc Guéhi', 'Mohammed Kudus', 'Antoine Semenyo', 'Iñaki Williams', 'Thomas Partey', 'Jordan Ayew', 'Kamaldeen Sulemana', 'Lawrence Ati-Zigi', 'Alexander Djiku', 'Abdul Fatawu', 'Gideon Mensah', 'Mohammed Salisu', 'Brandon Thomas-Asante'] },
    { id: '47', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO L', local: 'PANAMÁ', bandera_local: '🇵🇦', visitante: 'CROACIA', bandera_visitante: '🇭🇷', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '20:00', jugadores: ['Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić', 'Dominik Livaković', 'Martin Baturina', 'Marcelo Brozović', 'Andrej Kramarić', 'Josip Šutalo', 'Lovro Majer', 'Borna Sosa', 'Josip Stanišić', 'Mario Pašalić', 'Adalberto Carrasquilla', 'Michael Amir Murillo', 'Ismael Díaz', 'Orlando Mosquera', 'José Córdoba', 'Aníbal Godoy', 'Andrés Andrade', 'Fidel Escobar', 'José Fajardo', 'Éric Davis', 'José Luis Rodríguez', 'Kahiser Lenis'] },
    { id: '48', etapa: 'grupos', fase_nro: 2, grupo: 'GRUPO K', local: 'COLOMBIA', bandera_local: '🇨🇴', visitante: 'RD CONGO', bandera_visitante: '🇨🇩', fecha: '23 de Junio', fecha_iso: '2026-06-23', hora: '23:00', jugadores: ['Luis Díaz', 'James Rodríguez', 'Richard Ríos', 'Jhon Durán', 'Jhon Arias', 'Rafael Santos Borré', 'Daniel Muñoz', 'Davinson Sánchez', 'Camilo Vargas', 'Luis Sinisterra', 'Álvaro Montero', 'Yoane Wissa', 'Theo Bongonda', 'Chancel Mbemba', 'Samuel Moutoussamy', 'Simon Banza', 'Meschack Elia', 'Dimitry Bertaud', 'Arthur Masuaku', 'Charles Pickel', 'Dylan Batubinsika', 'Gédéon Kalulu', 'Gaël Kakuta'] },
    

    { id: '49', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO B', local: 'SUIZA', bandera_local: '🇨🇭', visitante: 'CANADÁ', bandera_visitante: '🇨🇦', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '16:00', jugadores: ['Alphonso Davies', 'Jonathan David', 'Stephen Eustáquio', 'Tajon Buchanan', 'Cyle Larin', 'Ismael Koné', 'Alistair Johnston', 'Milan Borjan', 'Jacob Shaffelburg', 'Granit Xhaka', 'Xherdan Shaqiri', 'Yann Sommer', 'Manuel Akanji', 'Breel Embolo', 'Gregor Kobel', 'Fabian Schar', 'Remo Freuler', 'Ruben Vargas', 'Dan Ndoye', 'Zeki Amdouni', 'Michel Aebischer', 'Denis Zakaria', 'Silvan Widmer', 'Ricardo Rodríguez', 'Noah Okafor'] },
    { id: '50', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO B', local: 'BOSNIA Y HERZEGOVINA', bandera_local: '🇧🇦', visitante: 'CATAR', bandera_visitante: '🇶🇦', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '16:00', jugadores: ['Edin Džeko', 'Sead Kolašinac', 'Ermedin Demirovic', 'Amar Dedic', 'Benjamín Tahirovic', 'Nikola Vasilj', 'Martin Zlomislić', ' Osman Hadžikić', 'Nihad Mujakić', ' Nikola Katić', 'Tarik Muharemović', 'Stjepan Radeljić', ' Dennis Hadžikadunić', 'Nidal Čelik', 'Amir Hadžiahmetović', 'Ivan Šunjić', 'Ivan Bašić', 'Dženis Burnić', 'Ermin Mahmić', 'Amar Memić', 'Armin Gigović', 'Kerim Alajbegović', 'Esmir Bajraktarević', 'Jovo Lukić', 'Samed Baždar', 'Haris Tabaković',
         'Akram Afif', 'Almoez Ali', 'Hassan Al-Haydos', 'Meshaal Barsham', 'Lucas Mendes', 'Mohammed Waad', 'Boualem Khoukhi', 'Abdulaziz Hatem', 'Jassim Gaber', 'Tarek Salman', 'Pedro Miguel', 'Homam Ahmed', 'Yusuf Abdurisag', 'Mohammed Muntari'] },
    { id: '51', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO C', local: 'ESCOCIA', bandera_local: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', visitante: 'BRASIL', bandera_visitante: '🇧🇷', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '19:00', jugadores: ['Vinícius Júnior', 'Rodrygo Goes', 'Endrick Felipe', 'Neymar Júnior', 'Raphina Dias', 'Gabriel Martinelli', 'Savio Moreira', 'Pedro Guilherme', 'Lucas Paquetá', 'Bruno Guimaraes', 'Douglas Luiz', 'Joao Gomes', 'Andreas Pereira', 'Ederson dos Santos', 'Marquinos', 'Éder Militao', 'Gabriel Magalhaes', 'Danilo Luiz da Silva', 'Guilherme Arana', 'Lucas Beraldo', 'Yan Couto', 'Alisson Becker', 'Ederson Moraes', 'Bento Matheus Krepski', 'Andrew Robertson', 'Scott McTominay', 'John Mcginn', 'Billy Gilmour', 'Kieran Tierney', 'Angus Gunn', 'Jack Hendry', 'Ryan Porteous', 'Che Adams', 'Ryan Christie', 'Lawrence Shankland', 'Lewis Ferguson'] },
    { id: '52', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO C', local: 'MARRUECOS', bandera_local: '🇲🇦', visitante: 'HAITÍ', bandera_visitante: '🇭🇹', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '19:00', jugadores: ['Achraf Hakimi', 'Brahim Díaz', 'Hakim Ziyech', 'Yassine Bounou', 'Sofyan Amrabat', 'Azzedine Ounahi', 'Nayef Aguerd', 'Romain Saiss', 'Youssef En-Nesyri', 'Amine Adli', 'Abde Exxalzouli', 'Soufiane Rahimi', 'Duckens Nazon', 'Frantzdy Pierrot', 'Dany Jean', 'Johny Placide', 'Carlens Arcus', 'Leverton Pierre', 'Danley Jean Jacques', 'Ricardo Adé', 'Jean-Kévin Duverne', 'Mondy Prunier', 'Garissone Innocent', 'Alez Christian'] },
    { id: '53', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO A', local: 'REP. CHECA', bandera_local: '🇨🇿', visitante: 'MÉXICO', bandera_visitante: '🇲🇽', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '22:00', jugadores: ['Guillermo Ochoa', 'Luis Malagón', 'Julio González', 'Edson Álvarez', 'César Montes', 'Johan Vásquez', 'Jorge Sánchez', 'Gerardo Arteaga', 'Israel Reyes', 'Jesús Orozco Chiquete', 'Luis Chávez', 'Orbelín Pineda', 'Erik Sánchez', 'Marcel Ruiz', 'Roberto Alvarado', 'Luis Romo', 'Santiago Giménez', 'Hirving Lozano', 'Julián Quiñones', 'Henry Martín', 'Alexis Vega', 'Uriel Antuna', 'Patrik Schick', 'Tomáš Souček', 'Vladimir Coufal', 'Adam Hložek', 'Antonín Barák', 'Ladislav Krejčí', 'Václav Cerny', 'David Zima', 'Robin Hranáč', 'David Jurásek', 'Lukáš Provod', 'Ondřej Lingr', 'Pavel Sulc', 'Jan Kuchta', 'Mojmír Chytil'] },
    { id: '54', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO A', local: 'SUDAFRICA', bandera_local: '🇿🇦', visitante: 'COREA DEL SUR', bandera_visitante: '🇰🇷', fecha: '24 de Junio', fecha_iso: '2026-06-24', hora: '22:00', jugadores: ['Ronwen Williams', 'Khuliso Mudau', 'Aubrey Modiba', 'Mothobi Mvala', 'Grant Kekana', 'Teboho Mokoena', 'Sphephelo Sithole', 'Themba Zwane', 'Percy Tau', 'Evidence Makgopa', 'Thapelo Morena', 'Heung-min Son', 'Kim Min-jae', 'Lee Kang-in', 'Hwang Hee-chan', 'Cho Gue-sung', 'Hwang In-beom', 'Jo Hyeon-woo', 'Lee Jae-sung', 'Paik Seung-ho', 'Jeong Woo-yeong', 'Hong Hyun-seok', 'Oh Hyeon-gyu', 'Yang Min-hyeok', 'Seol Young-woo', 'Kim Jin-su', 'Kim Seung-gyu'] },
    { id: '55', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO E', local: 'CURAZAO', bandera_local: '🇨🇼', visitante: 'COSTA DE MARFIL', bandera_visitante: '🇨🇮', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '17:00', jugadores: ['Tahith Chong', 'Leandro Bacuna', 'Juninho Bacuna', 'Eloy Room', 'Armando Obispo', 'Riechedly Bazoer', 'Shurandy Sambo', 'Sherel Floranus', 'Jurien Gaari', 'Jurgen Locadia', 'Sontje Hansen', 'Livano Comenencia', 'Kenji Gorré', 'Franck Kessié', 'Simon Adingra', 'Amad Diallo', 'Seko Fofana', 'Ibrahim Sangaré', 'Ousmane Diomande', 'Evan Ndicka', 'Elye Wahi', 'Yahia Fofana', 'Wilfried Singo', 'Nicolas Pépé', 'Evann Guessand'] },
    { id: '56', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO E', local: 'ECUADOR', bandera_local: '🇪🇨', visitante: 'ALEMANIA', bandera_visitante: '🇩🇪', fecha: '25', fecha_iso: '2026-06-25', hora: '17:00', jugadores: ['Florian Wirtz', 'Jamal Musiala', 'Kai Havertz', 'Joshua Kimmich', 'Antonio Rüdiger', 'Marc-André ter Stegen', 'Niclas Füllkrug', 'Leroy Sané', 'Jonathan Tah', 'İlkay Gündoğan', 'Deniz Undav', 'Moisés Caicedo', 'Kendry Páez', 'Piero Hincapié', 'Willian Pacho', 'Enner Valencia', 'Pervis Estupiñán', 'Gonzalo Plata', 'Hernán Galíndez', 'Kevin Rodríguez', 'Jeremy Sarmiento', 'Joel Ordóñez'] },
    { id: '57', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO F', local: 'JAPÓN', bandera_local: '🇯🇵', visitante: 'SUECIA', bandera_visitante: '🇸🇪', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '20:00', jugadores: ['Takefusa Kubo', 'Wataru Endo', 'Zion Suzuki', 'Ritsu Doan', 'Ayase Ueda', 'Hiroki Ito', 'Daichi Kamada', 'Yukinari Sugawara', 'Ao Tanaka', 'Ko Itakura', 'Daizen Maeda', 'Tomoki Hayakawa', 'Keisuke Osako', 'Yuto Nagatomo', 'Shogo Taniguchi', 'Tsuyoshi Watanabe', 'Takehiro Tomiyasu', 'Ayumu Seko', 'Junnosuke Suzuki', 'Junya Ito', 'Keito Nakamura', 'Kaishu Sano', 'Yuito Suzuki', 'Kento Shioggi', 'Koki Ogawa', 'Keisuke Goto',
         'Viktor Gyökeres', 'Alexander Isak', 'Lucas Bergvall', 'Victor Lindelöf', 'Isak Hien', 'Anthony Elanga', 'Yasin Ayari', 'Daniel Svensson', 'Viktor Johansson', 'Kristoffer Nordfeldt', 'Jacob Widell Zetterström', 'Gabriel Gudmundsson', 'Emil Holm', 'Gustaf Lagerbielke', 'Eric Smith', 'Carl Starfelt', 'Elliot Stroud', 'Jesper Karlström', 'Mattias Svanberg', 'Besfort Zeneli', 'Ken Sema', 'Taha Ali', 'Alexander Bernhardsson', 'Gustaf Nilsson', 'Benjamin Nygren'] },
    { id: '58', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO F', local: 'TÚNEZ', bandera_local: '🇹🇳', visitante: 'PAISES BAJOS', bandera_visitante: '🇳🇱', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '20:00', jugadores: ['Virgil van Dijk', 'Cody Gakpo', 'Xavi Simons', 'Ryan Gravenberch', 'Micky van de Ven', 'Denzel Dumfries', 'Memphis Depay', 'Tijjani Reijnders', 'Bart Verbruggen', 'Nathan Aké', 'Jeremie Frimpong', 'Wout Weghorst', 'Hannibal Mejbri', 'Ellyes Skhiri', 'Elias Achouri', 'Ismaël Gharbi', 'Aïssa Laïdouni', 'Montassar Talbi', 'Aymen Dahmen', 'Elias Saad', 'Ali Abdi', 'Yan Valery', 'Anis Saidi', 'Rani Khedira'] },
    { id: '59', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO D', local: 'TURQUIA', bandera_local: '🇹🇷', visitante: 'ESTADOS UNIDOS', bandera_visitante: '🇺🇸', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '23:00', jugadores: ['Christian Pulisic', 'Weston McKennie', 'Timothy Weah', 'Folarin Balogun', 'Giovanni Reyna', 'Matt Turner', 'Antonee Robinson', 'Yunus Musah', 'Tyler Adams', 'Brenden Aaronson', 'Ricardo Pepi', 'Cameron Carter-Vickers', 'Arda Güler', 'Hakan Çalhanoğlu', 'Kenan Yıldız', 'Barış Alper Yılmaz', 'Ferdi Kadıoğlu', 'Mert Günok', 'Abdülkerim Bardakcı', 'Merih Demiral', 'Kerem Aktürkoğlu', 'Orkun Kökçü', 'Semih Kılıçsoy'] },
    { id: '60', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO D', local: 'PARAGUAY', bandera_local: '🇵🇾', visitante: 'AUSTRALIA', bandera_visitante: '🇦🇺', fecha: '25 de Junio', fecha_iso: '2026-06-25', hora: '23:00', jugadores: ['Miguel Almirón', 'Julio Enciso', 'Gustavo Gómez', 'Ramón Sosa', 'Mathías Villasanti', 'Adam Bareiro', 'Omar Alderete', 'Antonio Sanabria', 'Andrés Cubas', 'Junior Alonso', 'Santiago Arzamendia', 'Alejandro Romero Gamarra', 'Mathew Ryan', 'Harry Souttar', 'Jackson Irvine', 'Craig Goodwin', 'Martin Boyle', 'Nestory Irankunda', 'Mitchell Duke', 'Aziz Behich', 'Connor Metcalfe', 'Alessandro Circati', 'Kusini Yengi'] },
    { id: '61', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO I', local: 'NORUEGA', bandera_local: '🇳🇴', visitante: 'FRANCIA', bandera_visitante: '🇫🇷', fecha: '26 de Junio', fecha_iso: '2026-06-26', hora: '16:00', jugadores: ['Kylian Mbappé', 'Michael Olise', 'Mike Maignan', 'William Saliba', 'Aurélien Tchouaméni', 'Ousmane Dembélé', 'Theo Hernández', 'Bradley Barcola', 'Warren Zaïre-Emery', 'Marcus Thuram', 'Robin Risser', 'Brice Samba', 'Lucas Digne', 'Malo Gusto', 'Lucas Hernandez', 'Ibrahima Konate', 'Jules Kounde', 'Maxence Lacroix', 'Dayot Upamecano', 'NGolo Kante', 'Manu Kone', 'Adrien Rabiot', 'Maghnes Akliouche', 'Rayan Cherki', 'Desire Doue', 'Jean-Philippe Mateta',
         'Erling Haaland', 'Martin Ødegaard', 'Alexander Sørloth', 'Antonio Nusa', 'Julian Ryerson', 'Sander Berge', 'Oscar Bobb', 'Kristoffer Ajer', 'Ørjan Nyland', 'Leo Østigård', 'David Møller Wolfe', 'Jørgen Strand Larsen'] },
    { id: '62', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO I', local: 'SENEGAL', bandera_local: '🇸🇳', visitante: 'IRAK', bandera_visitante: '🇮🇶', fecha: '26 de Junio', fecha_iso: '2026-06-26', hora: '16:00', jugadores: ['Aymen Hussein', 'Ali Jasim', 'Zidane Iqbal', 'Ali Al-Hamadi', 'Ibrahim Bayesh', 'Amir Al-Ammari', 'Youssef Amyn', 'Mohanad Ali', 'Rebin Sulaka', 'Merchas Doski', 'Ahmed Basil', 'Manaf Younis', 'Sadio Mané', 'Nicolas Jackson', 'Kalidou Koulibaly', 'Edouard Mendy', 'Ismaïla Sarr', 'Pape Matar Sarr', 'Lamine Camara', 'Idrissa Gana Gueye', 'Abdou Diallo', 'Iliman Ndiaye', 'Moussa Niakhaté', 'Boulaye Dia'] },
    { id: '63', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO H', local: 'CABO VERDE', bandera_local: '🇨🇻', visitante: 'ARABIA SAUDITA', bandera_visitante: '🇸🇦', fecha: '26', fecha_iso: '2026-06-26', hora: '21:00', jugadores: ['Ryan Mendes', 'Logan Costa', 'Bebé', 'Vozinha', 'Garry Rodrigues', 'Kevin Pina', 'Jovane Cabral', 'Kenny Rocha Santos', 'Roberto Lopes', 'Jamiro Monteiro', 'Steven Moreira', 'Deroy Duarte', 'Salem Al-Dawsari', 'Firas Al-Buraikan', 'Mohammed Al-Owais', 'Saud Abdulhamid', 'Mohamed Kanno', 'Ali Al-Bulayhi', 'Faisal Al-Ghamdi', 'Abdulelah Al-Malki', 'Hassan Tambakti', 'Nasser Al-Dawsari', 'Ali Lajami', 'Saleh Al-Shehri'] },
    { id: '64', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO H', local: 'URUGUAY', bandera_local: '🇺🇾', visitante: 'ESPAÑA', bandera_visitante: '🇪🇸', fecha: '26 de Junio', fecha_iso: '2026-06-26', hora: '21:00', jugadores: ['Federico Valverde', 'Darwin Núñez', 'Nicolás de la Cruz', 'Ronald Araújo', 'Sergio Rochet', 'Giorgian de Arrascaeta', 'Manuel Ugarte', 'José María Giménez', 'Facundo Pellistri', 'Maximiliano Araújo', 'Matías Viña', 'Santiago Mele', 'Lamine Yamal', 'Rodri Hernández', 'Nico Williams', 'Pedri González', 'Dani Olmo', 'Unai Simón', 'Pau Cubarsí', 'Marc Cucurella', 'Dani Carvajal', 'Fabián Ruiz', 'Samu Aghehowa', 'Fermín López'] },
    { id: '65', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO G', local: 'EGIPTO', bandera_local: '🇪🇬', visitante: 'IRÁN', bandera_visitante: '🇮🇷', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '0:00', jugadores: ['Mohamed Salah', 'Omar Marmoush', 'Mostafa Mohamed', 'Trézéguet', 'Mohamed Abdelmonem', 'Mohamed El Shenawy', 'Emam Ashour', 'Zizo', 'Marwan Ateya', 'Hossam Abdelmaguid', 'Mohamed Hany', 'Ahmed Fatouh', 'Mehdi Taremi', 'Sardar Azmoun', 'Alireza Beiranvand', 'Alireza Jahanbakhsh', 'Saman Ghoddos', 'Mehdi Ghayedi', 'Saeid Ezatolahi', 'Shojae Khalilzadeh', 'Milad Mohammadi', 'Mehdi Torabi', 'Hossein Kanaani', 'Ramin Rezaeian'] },
    { id: '66', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO G', local: 'NUEVA ZELANDA', bandera_local: '🇳🇿', visitante: 'BÉLGICA', bandera_visitante: '🇧🇪', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '0:00', jugadores: ['Kevin De Bruyne', 'Jérémy Doku', 'Romelu Lukaku', 'Leandro Trossard', 'Youri Tielemans', 'Thibaut Courtois', 'Amadou Onana', 'Arthur Theate', 'Charles De Ketelaere', 'Timothy Castagne', 'Zeno Debast', 'Senne Lammens', 'Mike Penders', 'Maxim De Cuyper', 'Koni De Winter', 'Brandon Mechele', 'Thomas Meunier', 'Nathan Nhoy', 'Joaquin Seys', 'Nicolas Raskin', 'Hans Vanaken', 'Axel Witsel', 'Matías Fernandez-Pardo', 'Dodi Lukebakio', 'Diego Moreira', 'Alexis Saelemaekers', 
         'Chris Wood', 'Liburato Cacace', 'Joe Bell', 'Michael Boxall', 'Sarpreet Singh', 'Tyler Bindon', 'Ben Waine', 'Kosta Barbarouses', 'Max Crocombe', 'Alex Paulsen', 'Michael Woud', 'Callan Elliot', 'Tim Payne', 'Nando Pijnaker', 'Tommy Smith', 'Finn Surman', 'Francis de Vries', 'Lachlan Bayliss', 'Matt Garbett', 'Elijah Just', 'Ben Old', 'Alex Rufer', 'Marko Stamenić', 'Ryan Thomas', 'Callum McCowatt', 'Jesse Randall',] },
    { id: '67', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO L', local: 'PANAMÁ', bandera_local: '🇵🇦', visitante: 'INGLATERRA', bandera_visitante: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '18:00', jugadores: ['Harry Kane', 'Jude Bellingham', 'Cole Palmer', 'Phil Foden', 'Bukayo Saka', 'Declan Rice', 'Jordan Pickford', 'John Stones', 'Reece James', 'Marcus Rashford', 'Kobbie Mainoo', 'Marc Guéhi', 'Adalberto Carrasquilla', 'Michael Amir Murillo', 'Ismael Díaz', 'Orlando Mosquera', 'José Córdoba', 'Aníbal Godoy', 'Andrés Andrade', 'Fidel Escobar', 'José Fajardo', 'Éric Davis', 'José Luis Rodríguez', 'Kahiser Lenis'] },
    { id: '68', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO L', local: 'CROACIA', bandera_local: '🇭🇷', visitante: 'GHANA', bandera_visitante: '🇬🇭', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '18:00', jugadores: ['Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić', 'Dominik Livaković', 'Martin Baturina', 'Marcelo Brozović', 'Andrej Kramarić', 'Josip Šutalo', 'Lovro Majer', 'Borna Sosa', 'Josip Stanišić', 'Mario Pašalić', 'Mohammed Kudus', 'Antoine Semenyo', 'Iñaki Williams', 'Thomas Partey', 'Jordan Ayew', 'Kamaldeen Sulemana', 'Lawrence Ati-Zigi', 'Alexander Djiku', 'Abdul Fatawu', 'Gideon Mensah', 'Mohammed Salisu', 'Brandon Thomas-Asante'] },
    { id: '69', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO K', local: 'COLOMBIA', bandera_local: '🇨🇴', visitante: 'PORTUGAL', bandera_visitante: '🇵🇹', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '20:30', jugadores: ['Luis Díaz', 'James Rodríguez', 'Richard Ríos', 'Jhon Durán', 'Jhon Arias', 'Rafael Santos Borré', 'Daniel Muñoz', 'Davinson Sánchez', 'Camilo Vargas', 'Luis Sinisterra', 'Álvaro Montero', 'Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva', 'Rafael Leão', 'Rúben Dias', 'Diogo Costa', 'João Félix', 'Vitinha', 'João Palhinha', 'Nuno Mendes', 'João Neves', 'Gonçalo Ramos'] },
    { id: '70', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO K', local: 'RD CONGO', bandera_local: '🇨🇩', visitante: 'UZBEKISTÁN', bandera_visitante: '🇺🇿', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '20:30', jugadores: ['Yoane Wissa', 'Theo Bongonda', 'Chancel Mbemba', 'Samuel Moutoussamy', 'Simon Banza', 'Meschack Elia', 'Dimitry Bertaud', 'Arthur Masuaku', 'Charles Pickel', 'Dylan Batubinsika', 'Gédéon Kalulu', 'Gaël Kakuta', 'Eldor Shomurodov', 'Abbosbek Fayzullaev', 'Abdukodir Khusanov', 'Jaloliddin Masharipov', 'Utkir Yusupov', 'Oston Urunov', 'Otabek Shukurov', 'Rustam Ashurmatov', 'Odiljon Hamrobekov', 'Husniddin Aliqulov', 'Farrukh Sayfiev', 'Azizbek Turgunboev'] },
    { id: '71', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO J', local: 'ARGELIA', bandera_local: '🇩🇿', visitante: 'AUSTRIA', bandera_visitante: '🇦🇹', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '23:00', jugadores: ['Marcel Sabitzer', 'Konrad Laimer', 'David Alaba', 'Christoph Baumgartner', 'Kevin Danso', 'Michael Gregoritsch', 'Stefan Posch', 'Patrick Pentz', 'Patrick Wimmer', 'Nicolas Seiwald', 'Romano Schmid', 'Philipp Lienhart', 'Riyad Mahrez', 'Mohamed Amoura', 'Ismaël Bennacer', 'Said Benrahma', 'Rayan Aït-Nouri', 'Houssem Aouar', 'Ramy Bensebaini', 'Anthony Mandrea', 'Ramiz Zerrouki', 'Aïssa Mandi', 'Farès Chaïbi', 'Youcef Atal'] },
    { id: '72', etapa: 'grupos', fase_nro: 3, grupo: 'GRUPO J', local: 'JORDANIA', bandera_local: '🇯🇴', visitante: 'ARGENTINA', bandera_visitante: '🇦🇷', fecha: '27 de Junio', fecha_iso: '2026-06-27', hora: '23:00', jugadores: ['Lionel Messi', 'Emiliano Martínez', 'Julián Álvarez', 'Lautaro Martínez', 'Rodrigo De Paul', 'Alexis Mac Allister', 'Enzo Fernández', 'Cristian Romero', 'Alejandro Garnacho', 'Leandro Paredes', 'Nico Paz', 'Franco Mastantuono', 'Nicolás Otamendi', 'Musa Al-Taamari', 'Yazan Al-Naimat', 'Yazeed Abulaila', 'Mahmoud Al-Mardi', 'Yazan Al-Arab', 'Nizar Al-Rashdan', 'Noor Al-Rawabdeh', 'Ehsan Haddad', 'Abdallah Nasib', 'Salem Al-Ajalin', 'Ali Olwan', 'Ibrahim Sadeh'] },

    { id: '1001', etapa: '16avos', local: '2A', bandera_local: '🏳️', visitante: '2B', bandera_visitante: '🏳️', fecha: '28 de Junio', fecha_iso: '2026-06-28', hora: '16:00', jugadores: [] }, 
    { id: '1002', etapa: '16avos', local: '1C', bandera_local: '🏳️', visitante: '2F', bandera_visitante: '🏳️', fecha: '29 de Junio', fecha_iso: '2026-06-29', hora: '14:00', jugadores: [] },  
    { id: '1003', etapa: '16avos', local: '1E', bandera_local: '🏳️', visitante: '3ABCDF', bandera_visitante: '🏳️', fecha: '29 de Junio', fecha_iso: '2026-06-29', hora: '17:30', jugadores: [] },  
    { id: '1004', etapa: '16avos', local: '1F', bandera_local: '🏳️', visitante: '2C', bandera_visitante: '🏳️', fecha: '29 de Junio', fecha_iso: '2026-06-29', hora: '22:00', jugadores: [] },  
    { id: '1005', etapa: '16avos', local: '2E', bandera_local: '🏳️', visitante: '2I', bandera_visitante: '🏳️', fecha: '30 de Junio', fecha_iso: '2026-06-30', hora: '14:00', jugadores: [] },  
    { id: '1006', etapa: '16avos', local: '1I', bandera_local: '🏳️', visitante: '3CDFGH', bandera_visitante: '🏳️', fecha: '30 de Junio', fecha_iso: '2026-06-30', hora: '18:00', jugadores: [] },  
    { id: '1007', etapa: '16avos', local: '1A', bandera_local: '🏳️', visitante: '3CEFHI', bandera_visitante: '🏳️', fecha: '30 de Junio', fecha_iso: '2026-06-30', hora: '22:00', jugadores: [] },  
    { id: '1008', etapa: '16avos', local: '1L', bandera_local: '🏳️', visitante: '3EHIJK', bandera_visitante: '🏳️', fecha: '1 de Julio', fecha_iso: '2026-07-01', hora: '13:00', jugadores: [] },  
    { id: '1009', etapa: '16avos', local: '1G', bandera_local: '🏳️', visitante: '3AEHIJ', bandera_visitante: '🏳️', fecha: '1 de Julio', fecha_iso: '2026-07-01', hora: '17:00', jugadores: [] },  
    { id: '1010', etapa: '16avos', local: '1D', bandera_local: '🏳️', visitante: '3BEFIJ', bandera_visitante: '🏳️', fecha: '1 de Julio', fecha_iso: '2026-07-01', hora: '21:00', jugadores: [] },
    { id: '1011', etapa: '16avos', local: '1H', bandera_local: '🏳️', visitante: '2J', bandera_visitante: '🏳️', fecha: '2 de Julio', fecha_iso: '2026-07-02', hora: '16:00', jugadores: [] },  
    { id: '1012', etapa: '16avos', local: '2K', bandera_local: '🏳️', visitante: '2L', bandera_visitante: '🏳️', fecha: '2 de Julio', fecha_iso: '2026-07-02', hora: '20:00', jugadores: [] },  
    { id: '1013', etapa: '16avos', local: '1B', bandera_local: '🏳️', visitante: '3EFGIJ', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '0:00', jugadores: [] },  
    { id: '1014', etapa: '16avos', local: '2D', bandera_local: '🏳️', visitante: '2G', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '15:00', jugadores: [] },  
    { id: '1015', etapa: '16avos', local: '1J', bandera_local: '🏳️', visitante: '2H', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '19:00', jugadores: [] },  
    { id: '1016', etapa: '16avos', local: '1K', bandera_local: '🏳️', visitante: '3DEIJL', bandera_visitante: '🏳️', fecha: '3 de Julio', fecha_iso: '2026-07-03', hora: '22:30', jugadores: [] },  

    { id: '2001', etapa: '8avos', local: '1001', bandera_local: '🏳️', visitante: '1002', bandera_visitante: '🏳️', fecha: '4 de Julio', fecha_iso: '2026-07-04', hora: '18:00', jugadores: [] },  
    { id: '2002', etapa: '8avos', local: '1003', bandera_local: '🏳️', visitante: '1004', bandera_visitante: '🏳️', fecha: '4 de Julio', fecha_iso: '2026-07-04', hora: '14:00', jugadores: [] },  
    { id: '2003', etapa: '8avos', local: '1005', bandera_local: '🏳️', visitante: '1006', bandera_visitante: '🏳️', fecha: '5 de Julio', fecha_iso: '2026-07-05', hora: '17:00', jugadores: [] },  
    { id: '2004', etapa: '8avos', local: '1007', bandera_local: '🏳️', visitante: '1008', bandera_visitante: '🏳️', fecha: '5 de Julio', fecha_iso: '2026-07-05', hora: '21:00', jugadores: [] },  
    { id: '2005', etapa: '8avos', local: '1009', bandera_local: '🏳️', visitante: '1010', bandera_visitante: '🏳️', fecha: '6 de Julio', fecha_iso: '2026-07-06', hora: '16:00', jugadores: [] },  
    { id: '2006', etapa: '8avos', local: '1011', bandera_local: '🏳️', visitante: '1012', bandera_visitante: '🏳️', fecha: '6 de Julio', fecha_iso: '2026-07-06', hora: '21:00', jugadores: [] },  
    { id: '2007', etapa: '8avos', local: '1013', bandera_local: '🏳️', visitante: '1014', bandera_visitante: '🏳️', fecha: '7 de Julio', fecha_iso: '2026-07-07', hora: '13:00', jugadores: [] },  
    { id: '2008', etapa: '8avos', local: '1015', bandera_local: '🏳️', visitante: '1016', bandera_visitante: '🏳️', fecha: '7 de Julio', fecha_iso: '2026-07-07', hora: '17:00', jugadores: [] },  

    { id: '3001', etapa: 'cuartos', local: '2001', bandera_local: '🏳️', visitante: '2002', bandera_visitante: '🏳️', fecha: '9 de Julio', fecha_iso: '2026-07-09', hora: '17:00', jugadores: [] },  
    { id: '3002', etapa: 'cuartos', local: '2003', bandera_local: '🏳️', visitante: '2004', bandera_visitante: '🏳️', fecha: '10 de Julio', fecha_iso: '2026-07-10', hora: '16:00', jugadores: [] },  
    { id: '3003', etapa: 'cuartos', local: '2005', bandera_local: '🏳️', visitante: '2006', bandera_visitante: '🏳️', fecha: '11 de Julio', fecha_iso: '2026-07-11', hora: '18:00', jugadores: [] },  
    { id: '3004', etapa: 'cuartos', local: '2007', bandera_local: '🏳️', visitante: '2008', bandera_visitante: '🏳️', fecha: '11 de Julio', fecha_iso: '2026-07-11', hora: '22:00', jugadores: [] },  

    { id: '4001', etapa: 'semis', local: '3001', bandera_local: '🏳️', visitante: '3002', bandera_visitante: '🏳️', fecha: '14 de Julio', fecha_iso: '2026-07-14', hora: '16:00', jugadores: [] },  
    { id: '4002', etapa: 'semis', local: '3003', bandera_local: '🏳️', visitante: '3004', bandera_visitante: '🏳️', fecha: '15 de Julio', fecha_iso: '2026-07-15', hora: '16:00', jugadores: [] },  

    { id: '5001', etapa: 'final', local: '4001', bandera_local: '🏳️', visitante: '4002', bandera_visitante: '🏳️', fecha: '19 de Julio', fecha_iso: '2026-07-19', hora: '16:00', jugadores: [] },  
    { id: '5002', etapa: 'final', local: '4001', bandera_local: '🏳️', visitante: '4002', bandera_visitante: '🏳️', fecha: '18 de Julio', fecha_iso: '2026-07-18', hora: '18:00', jugadores: [] },  
  ];

export default function AdminPanel() {
  const [loading, setLoading] = useState<string | null>(null);
  const [resultados, setResultados] = useState<any>({});

  // 1. Cargar datos existentes al entrar
  useEffect(() => {
    const cargarDatosExistentes = async () => {
      const { data, error } = await supabase.from('resultados_reales').select('*');
      if (data && !error) {
        const inicial: any = {};
        data.forEach(res => {
          inicial[res.partido_id] = {
            goles_local: res.goles_local_real?.toString() || '',
            goles_visitante: res.goles_visitante_real?.toString() || '',
            mvp: res.mvp_real || ''
          };
        });
        setResultados(inicial);
      }
    };
    cargarDatosExistentes();
  }, []);

  const handleChange = (partidoId: string, campo: string, valor: any) => {
    setResultados({
      ...resultados,
      [partidoId]: { 
        ...resultados[partidoId], 
        [campo]: valor 
      }
    });
  };

  const guardarResultadoOficial = async (partidoId: string) => {
    setLoading(partidoId);
    const res = resultados[partidoId];

    try {
      const { error } = await supabase
        .from('resultados_reales')
        .upsert({
          partido_id: partidoId,
          goles_local_real: parseInt(res?.goles_local) || 0,
          goles_visitante_real: parseInt(res?.goles_visitante) || 0,
          mvp_real: res?.mvp || ''
        }, { onConflict: 'partido_id' });

      if (error) throw error;
      alert("✅ Resultado oficial guardado. ¡Ranking actualizado!");
    } catch (err: any) {
      alert("Error: " + err.message);
    } finally {
      setLoading(null);
    }
  };

  return (
    <main className="min-h-screen p-8 bg-[#001D4A] text-white">
      <div className="max-w-4xl mx-auto">
        <div className="w-full flex justify-start mb-8">
          <Link href="/" className="text-[#F6C83E] font-bold uppercase text-[10px] tracking-widest hover:underline">
            ← Volver al inicio
          </Link>
        </div>
        
        <h1 className="text-4xl font-black my-8 text-[#F6C83E] italic uppercase tracking-tighter">Panel de Control</h1>
        <p className="mb-12 text-slate-400 font-medium">Cargá los resultados oficiales para actualizar el Prode.</p>

        <div className="space-y-6">
          {fixture.map((p) => (
            <div key={p.id} className="bg-[#002B71] p-6 rounded-3xl border border-[#003C9E] flex flex-col md:flex-row items-center gap-6">
              <div className="flex-1 font-bold">
                <span className="text-[#F6C83E] block text-[10px] mb-1 text-left uppercase tracking-widest">PARTIDO #{p.id}</span>
                <div className="text-left text-lg italic">{p.local} vs {p.visitante}</div>
              </div>

              <div className="flex gap-4 items-center">
                <input 
                  type="number" 
                  placeholder="L" 
                  value={resultados[p.id]?.goles_local ?? ''} 
                  className="w-14 h-14 bg-[#001D4A] border border-[#003C9E] rounded-xl text-center font-black text-xl text-[#F6C83E] outline-none focus:border-[#F6C83E]"
                  onChange={(e) => handleChange(p.id, 'goles_local', e.target.value)}
                />
                <span className="text-slate-500 font-black italic">VS</span>
                <input 
                  type="number" 
                  placeholder="V" 
                  value={resultados[p.id]?.goles_visitante ?? ''} 
                  className="w-14 h-14 bg-[#001D4A] border border-[#003C9E] rounded-xl text-center font-black text-xl text-[#F6C83E] outline-none focus:border-[#F6C83E]"
                  onChange={(e) => handleChange(p.id, 'goles_visitante', e.target.value)}
                />
              </div>

              <select 
                value={resultados[p.id]?.mvp ?? ''}
                className="bg-[#001D4A] border border-[#003C9E] p-3 rounded-xl text-sm font-bold flex-1 text-white outline-none focus:border-[#F6C83E]"
                onChange={(e) => handleChange(p.id, 'mvp', e.target.value)}
              >
                <option value="">MVP Oficial</option>
                {p.jugadores.map(j => (
                  <option key={j} value={j}>{j}</option>
                ))}
              </select>

              <button 
                onClick={() => guardarResultadoOficial(p.id)}
                disabled={loading === p.id}
                className="bg-[#F6C83E] text-[#001D4A] px-6 py-4 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:brightness-110 disabled:opacity-50 transition-all shadow-lg active:scale-95"
              >
                {loading === p.id ? "GUARDANDO..." : "CARGAR"}
              </button>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}